#! /usr/bin/env python
import re

from waf_dynamo import apidoc_extract_task

def init(ctx):
    pass

def configure(conf):
    pass

def build(bld):
    source = 'iac_null.cpp'

    platforms = ['arm.*?ios', 'arm.*?android']
    for p in platforms:
        if re.match(p, bld.env.PLATFORM):
            source = 'iac_stub.cpp'
            break

    bld.stlib(features = 'cxx',
              includes = '.',
              source = source,
              target = 'iacext')

    apidoc_extract_task(bld, ['iac_doc.h'])
