#! /usr/bin/env python
import os, re

from waf_dynamo import apidoc_extract_task
from BuildUtility import create_build_utility

def init(ctx):
    pass

def configure(conf):
    pass

def build(bld):
    build_util  = create_build_utility(bld.env)
    source = 'iac_null.cpp'

    platforms = ['arm.*?darwin', 'arm.*?android']
    for p in platforms:
        if re.match(p, bld.env.PLATFORM):
            source = 'iac_stub.cpp'
            break

    bld.stlib(features = 'cxx',
              includes = '.',
              source = source,
              install_path = build_util.get_library_path(),
              target = 'iacext')

    apidoc_extract_task(bld, ['iac_doc.h'])
