-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.


function init(self)
    self.deleted_objects = {}
    self.done = false;
end

function update(self)
    if (self.done) then
        assert(self.deleted_objects[1] == hash("child_2_1"))
        assert(self.deleted_objects[2] == hash("child_2"))
        assert(self.deleted_objects[3] == hash("child_1_1"))
        assert(self.deleted_objects[4] == hash("child_1"))
        assert(self.deleted_objects[5] == hash("parent"))
        go.delete()
    else
        go.delete("parent", true)
        self.done = true
    end

end

function on_message(self, message_id, message, sender)
    if message_id == hash("delete_child") then
        table.insert(self.deleted_objects, message.id)
    end
end
