#! /usr/bin/env python
from waflib import Options

EXTRA_DEFINES = []

if bld.env.PLATFORM in ('arm64-ios', 'x86_64-ios'):
    # Note: LUA_NO_SYSTEM is our own invention, mimicking the LJ_NO_SYSTEM
    EXTRA_DEFINES = ['LUA_NO_SYSTEM']

LUA_DEFINES = ['LUA_ANSI', 'DM_LUA_USE_LUA51'] + EXTRA_DEFINES

lua_lib_source = ['lapi.c', 'lcode.c', 'ldebug.c', 'ldo.c',
                  'ldump.c', 'lfunc.c', 'lgc.c', 'llex.c',
                  'lmem.c', 'lobject.c', 'lopcodes.c', 'lparser.c',
                  'lstate.c', 'lstring.c', 'ltable.c', 'ltm.c',
                  'lundump.c', 'lvm.c', 'lzio.c', 'lauxlib.c',
                  'lbaselib.c', 'ldblib.c', 'liolib.c',
                  'lmathlib.c', 'loslib.c', 'ltablib.c',
                  'lstrlib.c', 'loadlib.c', 'linit.c']

lua_lib = bld.stlib(features = 'c cxx',
                    name = 'lua_static',
                    includes = '. ../',
                    target = 'lua',
                    source = lua_lib_source,
                    defines = LUA_DEFINES)

lua_asan_source = []
if Options.options.with_asan:
    lua_asan_source = ['../lua_asan.cpp']

if bld.env.IS_TARGET_DESKTOP:
    lua = bld.program(features = 'c cxx',
                      includes = '. ../',
                      source = ['lua.c'] + lua_asan_source,
                      target = 'lua',
                      use = 'lua_static',
                      defines = LUA_DEFINES)

    luac = bld.program(features = 'c cxx',
                       includes = '. ../',
                       source = ['luac.c', 'print.c'] + lua_asan_source,
                       target = 'luac',
                       use = 'lua_static',
                       defines = LUA_DEFINES)

bld.install_files('${PREFIX}/include/lua', 'lua.h')
bld.install_files('${PREFIX}/include/lua', 'lauxlib.h')
bld.install_files('${PREFIX}/include/lua', 'lualib.h')
bld.install_files('${PREFIX}/include/lua', 'luaconf.h')
