#! /usr/bin/env python

VERSION='0.1'
APPNAME='switch'

srcdir = '.'
blddir = 'build'

import waf_dynamo

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="SWITCH"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="SWITCH"')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
