#! /usr/bin/env python

def configure(conf):
    pass

def get_luau_codegen_target(platform):
    if platform in ('arm64-macos', 'arm64-linux', 'arm64-android'):
        return 'CODEGEN_TARGET_A64'
    if platform in ('x86_64-macos', 'x86_64-linux', 'x86_64-win32'):
        return 'CODEGEN_TARGET_X64'
    return None

def build(bld):
    bld.program(features = 'cxx test',
                includes = '.',
                use = 'DLIB PROFILE_NULL SOCKET dlua lua_static',
                target = 'test_lua',
                source = 'test_lua.cpp')

    if not 'web' in bld.env.PLATFORM:
        bld.env['STLIB_LUAJIT_TEST'] = ['luajit-5.1']
        bld.program(features = 'cxx test',
                    includes = '.',
                    use = 'DLIB PROFILE_NULL SOCKET dluajit LUAJIT_TEST',
                    defines = ['DM_LUA_TEST_LUAJIT'],
                    target = 'test_luajit',
                    source = 'test_lua.cpp')

    luau_test_use = 'DLIB PROFILE_NULL SOCKET dluau luaucompiler_static luaubytecode_static luauast_static luauvm_static luaucommon_static'
    luau_test_defines = ['DM_LUA_TEST_LUAU']

    if get_luau_codegen_target(bld.env.PLATFORM):
        luau_test_defines += ['DM_LUA_TEST_LUAU_CODEGEN',
                              'LUACODEGEN_API=extern "C"']

    bld.program(features = 'cxx test',
                includes = '.',
                use = luau_test_use,
                defines = luau_test_defines,
                target = 'test_luau',
                source = 'test_lua.cpp')

    if bld.env.DOTNET:
        bld.stlib(features= 'cs_stlib',
                  project = 'cs/test_lua_cs.csproj')
        bld.add_group()
        t = bld.program(features = 'cxx test',
                        includes = '../../src .',
                        use = 'TESTMAIN DLIB PROFILE_NULL SOCKET CSHARP LUA',
                        target = 'test_lua_csharp',
                        source = 'test_lua_csharp.cpp')
        t.env.append_value('LINKFLAGS', [t.env.LIB_ST % 'test_lua_cs'])
        t.env.append_value('LINKFLAGS', ['-Lsrc/test/cs'])
