#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    if bld.env.PLATFORM != "armv7-darwin" and bld.env.PLATFORM != "arm64-darwin" and bld.env.PLATFORM != 'armv7-android' and bld.env.PLATFORM != 'js-web' and bld.env.PLATFORM != 'wasm-web':
        bld.add_subdirs('gdc')
    bld.add_subdirs('launcher')
