#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    if not bld.env.PLATFORM in ('armv7-darwin', 'arm64-darwin', 'x86_64-ios', 'armv7-android', 'js-web', 'wasm-web'):
        bld.add_subdirs('gdc')
    bld.add_subdirs('launcher')
