#! /usr/bin/env python
import os, Options

def configure(conf):
    pass

def build(bld):
    if bld.env.PLATFORM in ('x86_64-win32', 'x86_64-linux', 'x86_64-darwin'):
        if not Options.options.with_vulkan:
            bld.add_subdirs('gdc')

        bld.add_subdirs('launcher')
