import Task, TaskGen
from TaskGen import extension, declare_extension

def build(bld):

    embedded_sounds = bld.new_task_gen(features = 'cxx cstaticlib embed',
                                       target = 'embedded_sounds',
                                       source = 'dummy.cpp',  # Make waf happy
                                       embed_source = 'drumloop.wav onefootstep.wav layer-guitar-a.ogg click-track.ogg osc2_sin_440hz.wav door_opening.wav')

    test_sound = bld.new_task_gen(features = 'cxx cprogram embed',
                                  includes = '../../../src .',
                                  uselib = 'GTEST DLIB PLATFORM_SOCKET OPENAL',
                                  uselib_local = 'sound alut embedded_sounds',
                                  target = 'test_sound',
                                  source = 'test_sound.cpp')

    test_sound.install_path = None

    test_sound_null = bld.new_task_gen(features = 'cxx cprogram embed',
                                  includes = '../../../src .',
                                  uselib = 'GTEST DLIB PLATFORM_SOCKET OPENAL',
                                  uselib_local = 'sound_null embedded_sounds',
                                  target = 'test_sound_null',
                                  source = 'test_sound.cpp')


    test_sound_null.install_path = None
