#! /usr/bin/env python
import os, sys, re

def configure(conf):
    pass

def build(bld):
    bld.add_subdirs('openal')

    source        = 'devices/device_null.cpp sound_codec.cpp sound_decoder.cpp sound.cpp'.split()
    source_null   = 'devices/device_null.cpp sound_null.cpp'.split()
    decoders      = 'decoders/decoder_stb_vorbis.cpp stb_vorbis/stb_vorbis.c decoders/decoder_wav.cpp'.split()


    if bld.env['PLATFORM'] not in ['js-web', 'win32', 'x86_64-win32']:
        decoders += 'decoders/decoder_tremolo.cpp'.split()

    source       += decoders

    defines, include = ('', '')
    if re.match('arm.*?android', bld.env['PLATFORM']):
        defines = 'TREMOLO_SCORE=10'
        include = 'openal/include'
        source += ['sound_android.cpp', 'devices/device_opensl.cpp']
    elif re.match('arm.*?darwin', bld.env['PLATFORM']) or bld.env['PLATFORM'] == 'sim-darwin':
        defines = 'TREMOLO_SCORE=10'
        source += ['sound_ios.mm', 'devices/device_openal.cpp']
    elif re.match('js-web', bld.env['PLATFORM']):
        defines = 'TREMOLO_SCORE=8'
        source += ['sound_generic.cpp', 'devices/device_js.cpp']
    else:
        defines = 'TREMOLO_SCORE=8'
        source += ['sound_generic.cpp', 'devices/device_openal.cpp']

    if re.match('js-web', bld.env['PLATFORM']):
        bld.install_files('${PREFIX}/lib/js-web/js', 'js/library_sound.js', postpone = False)
        bld.install_files('${PREFIX}/bin/js-web', 'flash/defold_sound.swf', postpone = False)
    elif re.match('arm.*?android', bld.env['PLATFORM']):
        classpath = os.path.join(bld.env['DYNAMO_HOME'], 'ext/share/java/android.jar')
        bld.env["JAVACFLAGS"] = '-g -source 1.6 -target 1.6'
        bld.new_task_gen(features='javac seq', classpath=classpath, source_root='java')
        bld.new_task_gen(features='jar seq', basedir='java', destfile='sound_android.jar')
        bld.install_files('${PREFIX}/share/java', 'sound_android.jar')


    sound = bld.new_task_gen(features = 'cc cxx cstaticlib ddf',
                             includes = '. %s' % include,
                             defines = defines,
                             target = 'sound',
                             source = source)

    sound_null = bld.new_task_gen(features = 'cc cxx cstaticlib ddf',
                                  includes = '.',
                                  defines = defines,
                                  target = 'sound_null',
                                  source = source_null)

    bld.install_files('${PREFIX}/include/sound', 'sound.h')

    if sys.platform == 'win32':
        #NOTE: _XBOX to get static lib and avoid dllimport/dllexport stuff
        sound.defines = '_XBOX'
        sound_null.defines = '_XBOX'

    bld.add_subdirs('test')
