#! /usr/bin/env python

VERSION='0.1'
APPNAME='facebook'

srcdir = '.'
blddir = 'build'

import waf_dynamo

def init():
    pass

def configure(conf):
    conf.sub_config('src')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    waf_dynamo.run_gtests(valgrind = True)

