#! /usr/bin/env python

from waf_dynamo import platform_supports_feature

def build(bld):

    bld.program(features = 'cxx cprogram test skip_test',
                includes = ['../../src'],
                source = 'platform_test_app.cpp',
                use = 'TESTMAIN APP DDF DLIB DMGLFW PROFILE VULKAN OPENGL graphics_vulkan_experimental platform'.split(),
                target = 'platform_test_app')

    """
    if platform_supports_feature(bld.env.PLATFORM, 'vulkan', {}) and not bld.env.PLATFORM in ('x86_64-linux','x86_64-ios'):

        extra_libs = []
        if bld.env.PLATFORM in ('armv7-android', 'arm64-android'):
            extra_libs += ['OPENGL']

        bld.program(features = 'cxx cprogram test skip_test',
                    includes = ['../../src', '../../proto'],
                    exported_symbols = ['GraphicsAdapterVulkan'],
                    source = 'test_app_vulkan.cpp',
                    use = 'TESTMAIN APP DDF DLIB DMGLFW PROFILE VULKAN graphics_vulkan_experimental graphics_transcoder_basisu'.split() + extra_libs,
                    target = 'test_app_vulkan')
    """
