#! /usr/bin/env python

from waf_dynamo import platform_supports_feature

def build(bld):

    bld.program(features = 'cxx cprogram test skip_test',
                includes = ['../../src'],
                source = 'platform_test_app.cpp',
                use = 'TESTMAIN APP DDF DLIB DMGLFW PROFILE OPENGL platform'.split(),
                target = 'platform_test_app')
