-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local test_counter = require("script_props.test_counter")

go.property("number", 0)
go.property("hash", hash(""))
go.property("url", msg.url())
go.property("vec3", vmath.vector3())
go.property("vec4", vmath.vector4(0, 0, 0, 0))
go.property("quat", vmath.quat())

function init(self, config)
    test_counter.start()
    assert(self.number == 100)
    assert(self.hash == hash("hash"))
    assert(self.url == msg.url("/path"))
    assert(self.vec3.x == 1)
    assert(self.vec3.y == 2)
    assert(self.vec3.z == 3)
    assert(self.vec4.x == 4)
    assert(self.vec4.y == 5)
    assert(self.vec4.z == 6)
    assert(self.vec4.w == 7)
    assert(self.quat.x == 8)
    assert(self.quat.y == 9)
    assert(self.quat.z == 10)
    assert(self.quat.w == 11)
    test_counter.done()
end
