import sys

def configure(conf):
    conf.env['CXXDEFINES_BULLET'] = ['NDEBUG']

def build(bld):
    bld.add_subdirs('BulletCollision')
    bld.add_subdirs('BulletDynamics')
    bld.add_subdirs('LinearMath')
