#ifndef DM_IAP_EXTENSION
#define DM_IAP_EXTENSION

// NOTE: Also defined in library_facebook_iap.js
// NOTE: Also defined in IapJNI.java

enum TransactionState
{
    TRANS_STATE_PURCHASING,
    TRANS_STATE_PURCHASED,
    TRANS_STATE_FAILED,
    TRANS_STATE_RESTORED,
    TRANS_STATE_UNVERIFIED,
};

enum ErrorReason
{
    REASON_UNSPECIFIED = 0,
    REASON_USER_CANCELED = 1,
};

enum BillingResponse
{
    BILLING_RESPONSE_RESULT_OK = 0,
    BILLING_RESPONSE_RESULT_USER_CANCELED = 1,
    BILLING_RESPONSE_RESULT_BILLING_UNAVAILABLE = 3,
    BILLING_RESPONSE_RESULT_ITEM_UNAVAILABLE = 4,
    BILLING_RESPONSE_RESULT_DEVELOPER_ERROR = 5,
    BILLING_RESPONSE_RESULT_ERROR = 6,
    BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED = 7,
    BILLING_RESPONSE_RESULT_ITEM_NOT_OWNED = 8,
};

enum StoreId
{
    STORE_ID_GOOGLE,
    STORE_ID_AMAZON,
    STORE_ID_APPLE,
    STORE_ID_FACEBOOK,
};

#endif
