#! /usr/bin/env python
import os, re

def configure(conf):
    pass

def build(bld):
    embed_source = ''
    source = []

    if re.match('arm.*?darwin', bld.env.PLATFORM):
        source += ['iap_ios.mm']
    else:
        source += ['iap_null.cpp']

    iap = bld.new_task_gen(features = 'cxx cstaticlib',
                           includes = '.',
                           source = source,
                           target = 'iapext')
