#! /usr/bin/env python
import re
from waf_dynamo import apidoc_extract_task

def configure(conf):
    pass

def build(bld):
    source = 'iap_null.cpp'

    platforms = ['arm.*?ios', 'arm.*?android', 'x86_64-ios', 'web']
    for p in platforms:
        if re.match(p, bld.env.PLATFORM):
            source = 'iap_stub.cpp'
            break

    bld.stlib(features = 'cxx',
              includes = '.',
              source = source,
              target = 'iapext')

    apidoc_extract_task(bld, ['iap_doc.h'])
