#! /usr/bin/env python
import os, re
from waf_dynamo import apidoc_extract_task

def configure(conf):
    pass

def build(bld):
    embed_source = ''

    source = ['gameroom_null.cpp']

    if re.match('.*win32', bld.env.PLATFORM):
        source = ['gameroom.cpp', 'gameroom_fb.cpp', 'gameroom_iap.cpp', 'FBG_PlatformLoader.cpp']

    iac = bld.new_task_gen(features = 'cxx cstaticlib',
                            includes = '.',
                            source = source,
                            target = 'gameroomext')

    # apidoc_extract_task(bld, ['iac.cpp'])


