#! /usr/bin/env python
import os, re

def configure(conf):
    pass

def build(bld):

    embed_source = ''
    source = ['gameroom_null.cpp']

    if re.match('.*win32', bld.env.PLATFORM):
        source = ['gameroom.cpp', 'faceboook_gameroom.cpp']

    gameroom = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                            includes = '.',
                            source = source,
                            target = 'gameroomext')

    source = ['facebook/facebook_null.cpp']
    if re.match('.*win32', bld.env.PLATFORM):
        source = ['facebook/facebook_analytics.cpp', 'facebook/facebook_private.cpp',
                'facebook/facebook_gameroom.cpp', 'facebook/facebook_util.cpp']

    gameroom = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                            includes = '.',
                            source = source,
                            target = 'facebookext_gr')

    if re.match('.*win32', bld.env.PLATFORM):
        bld.install_files('${PREFIX}/include/gameroom', 'gameroom.h')



