defold_log("features.cmake:")

option(BUILD_TESTS "Build unit tests" ON)
option(DEFOLD_TEST_COLORS "Use colored unit test output" ON)
set(DEFOLD_ENABLE_FEATURES "" CACHE STRING "Semicolon or comma separated list of enabled Defold features, e.g. mbedtls;wagyu")
set(DEFOLD_DISABLE_FEATURES "" CACHE STRING "Semicolon or comma separated list of disabled Defold features")
option(USE_VULKAN "Use Vulkan graphics adapter for app test" OFF)
option(WITH_ASAN "Enable AddressSanitizer (exclusive with other sanitizers)" OFF)
option(WITH_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(WITH_TSAN "Enable ThreadSanitizer" OFF)
option(WITH_VALGRIND "Enable Valgrind integration checks" OFF)
option(WITH_OPENAL "Enable OpenAL sound backend" OFF)
option(WITH_OPENGL "Enable OpenGL graphics backend" OFF)
option(WITH_VULKAN "Enable Vulkan graphics backend" OFF)
option(WITH_VULKAN_VALIDATION "Enable Vulkan validation layers" OFF)
option(WITH_DX12 "Enable DirectX 12 graphics backend" OFF)
option(WITH_METAL "Enable Metal graphics backend" OFF)
option(WITH_OPUS "Enable Opus audio support" OFF)
option(WITH_WEBGPU "Enable WebGPU graphics backend" OFF)
option(DEFOLD_CODESIGN "Enable code signing" OFF)

set(DEFOLD_CODESIGNING_IDENTITY "Developer ID Application: Stiftelsen Defold Foundation (26PW6SVA7H)" CACHE STRING "Codesigning identity for macOS")
set(DEFOLD_GCLOUD_PROJECTID "" CACHE STRING "Google Cloud project id where key ring is stored")
set(DEFOLD_GCLOUD_LOCATION "" CACHE STRING "Google Cloud region where key ring is located")
set(DEFOLD_GCLOUD_KEYRINGNAME "" CACHE STRING "Google Cloud key ring name")
set(DEFOLD_GCLOUD_KEYNAME "" CACHE STRING "Google Cloud key name")
set(DEFOLD_GCLOUD_CERTFILE "" CACHE STRING "Google Cloud certificate chain file")
set(DEFOLD_GCLOUD_KEYFILE "" CACHE STRING "Google Cloud service account key file")

function(defold_normalize_feature_list out_var)
    set(_features)
    set(_raw "${ARGN}")
    string(REPLACE "," ";" _raw "${_raw}")
    foreach(_feature IN LISTS _raw)
        string(STRIP "${_feature}" _feature)
        if(_feature)
            string(TOLOWER "${_feature}" _feature)
            list(APPEND _features "${_feature}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _features)
    set(${out_var} "${_features}" PARENT_SCOPE)
endfunction()

defold_normalize_feature_list(DEFOLD_ENABLED_FEATURES "${DEFOLD_ENABLE_FEATURES}")
defold_normalize_feature_list(DEFOLD_DISABLED_FEATURES "${DEFOLD_DISABLE_FEATURES}")

function(defold_feature_enabled feature out_var)
    string(TOLOWER "${feature}" _feature)
    string(REGEX REPLACE "[^A-Za-z0-9]" "_" _feature_var "${feature}")
    string(TOUPPER "${_feature_var}" _feature_var)
    set(_with_var "WITH_${_feature_var}")
    set(_enabled OFF)
    if(_feature IN_LIST DEFOLD_ENABLED_FEATURES)
        set(_enabled ON)
    endif()
    if(DEFINED ${_with_var})
        if(${_with_var})
            set(_enabled ON)
        endif()
    endif()
    if(_feature IN_LIST DEFOLD_DISABLED_FEATURES)
        set(_enabled OFF)
    endif()
    set(${out_var} ${_enabled} PARENT_SCOPE)
endfunction()

function(defold_feature_disabled feature out_var)
    string(TOLOWER "${feature}" _feature)
    set(_disabled OFF)
    if(_feature IN_LIST DEFOLD_DISABLED_FEATURES)
        set(_disabled ON)
    endif()
    set(${out_var} ${_disabled} PARENT_SCOPE)
endfunction()

defold_log("BUILD_TESTS: ${BUILD_TESTS}")
defold_log("DEFOLD_TEST_COLORS: ${DEFOLD_TEST_COLORS}")
defold_log("DEFOLD_ENABLE_FEATURES: ${DEFOLD_ENABLED_FEATURES}")
defold_log("DEFOLD_DISABLE_FEATURES: ${DEFOLD_DISABLED_FEATURES}")
defold_log("USE_VULKAN: ${USE_VULKAN}")
defold_log("WITH_ASAN: ${WITH_ASAN}")
defold_log("WITH_UBSAN: ${WITH_UBSAN}")
defold_log("WITH_TSAN: ${WITH_TSAN}")
defold_log("WITH_VALGRIND: ${WITH_VALGRIND}")
defold_log("WITH_OPENAL: ${WITH_OPENAL}")
defold_log("WITH_OPENGL: ${WITH_OPENGL}")
defold_log("WITH_VULKAN: ${WITH_VULKAN}")
defold_log("WITH_VULKAN_VALIDATION: ${WITH_VULKAN_VALIDATION}")
defold_log("WITH_DX12: ${WITH_DX12}")
defold_log("WITH_METAL: ${WITH_METAL}")
defold_log("WITH_OPUS: ${WITH_OPUS}")
defold_log("WITH_WEBGPU: ${WITH_WEBGPU}")

set(_DEFOLD_ACTIVE_SANITIZER "")
if(WITH_ASAN)
    set(_DEFOLD_ACTIVE_SANITIZER "ASAN")
elseif(WITH_UBSAN)
    set(_DEFOLD_ACTIVE_SANITIZER "UBSAN")
elseif(WITH_TSAN)
    set(_DEFOLD_ACTIVE_SANITIZER "TSAN")
endif()

function(defold_target_skip_sanitizer target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "defold_target_skip_sanitizer: target not found: ${target}")
    endif()
    set_property(TARGET "${target}" PROPERTY DEFOLD_SKIP_SANITIZER ON)
endfunction()

function(_defold_gate_sanitizer_options out_var)
    set(_enabled_expr "$<NOT:$<BOOL:$<TARGET_PROPERTY:DEFOLD_SKIP_SANITIZER>>>")
    set(_gated_options)
    foreach(_option IN LISTS ARGN)
        list(APPEND _gated_options "$<${_enabled_expr}:${_option}>")
    endforeach()
    set(${out_var} "${_gated_options}" PARENT_SCOPE)
endfunction()

if(_DEFOLD_ACTIVE_SANITIZER STREQUAL "ASAN")
    if(MSVC_CL)
        set(_DEFOLD_SAN_COMPILE "/fsanitize=address" "-D_DISABLE_VECTOR_ANNOTATION" "-DDM_SANITIZE_ADDRESS")
        set(_DEFOLD_SAN_LINK "/fsanitize=address")
    else()
        set(_DEFOLD_SAN_COMPILE "-fsanitize=address" "-fno-omit-frame-pointer" "-fsanitize-address-use-after-scope" "-DDM_SANITIZE_ADDRESS")
        set(_DEFOLD_SAN_LINK "-fsanitize=address" "-fno-omit-frame-pointer" "-fsanitize-address-use-after-scope")
    endif()
elseif(_DEFOLD_ACTIVE_SANITIZER STREQUAL "UBSAN")
    set(_DEFOLD_SAN_COMPILE "-fsanitize=undefined" "-DDM_SANITIZE_UNDEFINED")
    set(_DEFOLD_SAN_LINK "-fsanitize=undefined")
elseif(_DEFOLD_ACTIVE_SANITIZER STREQUAL "TSAN")
    set(_DEFOLD_SAN_COMPILE "-fsanitize=thread" "-DDM_SANITIZE_THREAD")
    set(_DEFOLD_SAN_LINK "-fsanitize=thread")
endif()

if(DEFINED _DEFOLD_SAN_COMPILE)
    _defold_gate_sanitizer_options(_DEFOLD_SAN_COMPILE_GATED ${_DEFOLD_SAN_COMPILE})
    target_compile_options(defold_sdk INTERFACE ${_DEFOLD_SAN_COMPILE_GATED})
    if(DEFINED _DEFOLD_SAN_LINK)
        _defold_gate_sanitizer_options(_DEFOLD_SAN_LINK_GATED ${_DEFOLD_SAN_LINK})
        target_link_options(defold_sdk INTERFACE ${_DEFOLD_SAN_LINK_GATED})
    endif()
endif()
