defold_log("functions_xcode.cmake:")

function(defold_xcode_get_engine_module path out_var)
  set(${out_var} "" PARENT_SCOPE)
  if(NOT path)
    return()
  endif()

  if(IS_ABSOLUTE "${path}")
    set(_abs_path "${path}")
  else()
    get_filename_component(_abs_path "${path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()

  file(RELATIVE_PATH _rel_path "${DEFOLD_HOME}/engine" "${_abs_path}")
  if(_rel_path MATCHES "^\\.\\.")
    return()
  endif()

  string(REGEX REPLACE "/.*$" "" _module "${_rel_path}")
  if(_module AND NOT _module STREQUAL "." AND NOT _module MATCHES "^\\.\\.")
    set(${out_var} "${_module}" PARENT_SCOPE)
  endif()
endfunction()

function(defold_xcode_collect_targets out_var directory)
  get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(_subdirs DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)

  foreach(_subdir IN LISTS _subdirs)
    defold_xcode_collect_targets(_subdir_targets "${_subdir}")
    list(APPEND _targets ${_subdir_targets})
  endforeach()

  set(${out_var} ${_targets} PARENT_SCOPE)
endfunction()

function(defold_xcode_source_group target target_folder)
  get_target_property(_target_sources ${target} SOURCES)
  get_target_property(_target_source_dir ${target} SOURCE_DIR)
  if(NOT _target_sources OR _target_sources STREQUAL "_target_sources-NOTFOUND")
    return()
  endif()

  foreach(_source IN LISTS _target_sources)
    if(_source MATCHES "^\\$<")
      continue()
    endif()

    if(IS_ABSOLUTE "${_source}")
      set(_source_path "${_source}")
    else()
      get_filename_component(_source_path "${_source}" ABSOLUTE BASE_DIR "${_target_source_dir}")
    endif()

    get_filename_component(_source_name "${_source_path}" NAME)
    if(_source_name STREQUAL "CMakeLists.txt" OR _source_path MATCHES "\\.cmake$")
      file(RELATIVE_PATH _source_rel_dir "${DEFOLD_HOME}" "${_source_path}")
      get_filename_component(_source_rel_dir "${_source_rel_dir}" DIRECTORY)
      if(_source_rel_dir)
        string(REPLACE "/" "\\" _source_rel_group "${_source_rel_dir}")
        source_group("CMake configs\\${_source_rel_group}" FILES "${_source_path}")
      else()
        source_group("CMake configs" FILES "${_source_path}")
      endif()
      continue()
    endif()

    defold_xcode_get_engine_module("${_source_path}" _source_module)
    if(_source_module)
      if(target_folder MATCHES "/tests$" OR _source_path MATCHES "/test(s)?(/|$)")
        source_group("Engine\\${_source_module}\\tests" FILES "${_source_path}")
      else()
        source_group("Engine\\${_source_module}\\sources" FILES "${_source_path}")
      endif()
    endif()
  endforeach()
endfunction()

function(defold_xcode_add_cmake_config_target)
  if(TARGET defold_cmake_configs)
    return()
  endif()

  set(_cmake_config_files "${DEFOLD_HOME}/CMakeLists.txt")
  file(GLOB_RECURSE _engine_cmake_txt CONFIGURE_DEPENDS "${DEFOLD_HOME}/engine/*/CMakeLists.txt")
  file(GLOB_RECURSE _cmake_modules CONFIGURE_DEPENDS "${DEFOLD_HOME}/scripts/cmake/*.cmake")
  list(FILTER _engine_cmake_txt EXCLUDE REGEX "/build/")

  foreach(_candidate IN LISTS _engine_cmake_txt)
    get_filename_component(_candidate_name "${_candidate}" NAME)
    if(_candidate_name STREQUAL "CMakeLists.txt")
      list(APPEND _cmake_config_files "${_candidate}")
    endif()
  endforeach()
  if(EXISTS "${DEFOLD_HOME}/share/extender/CMakeLists.txt")
    list(APPEND _cmake_config_files "${DEFOLD_HOME}/share/extender/CMakeLists.txt")
  endif()
  list(APPEND _cmake_config_files ${_cmake_modules})
  list(REMOVE_DUPLICATES _cmake_config_files)
  list(SORT _cmake_config_files)

  foreach(_cmake_config_file IN LISTS _cmake_config_files)
    file(RELATIVE_PATH _cmake_config_rel_dir "${DEFOLD_HOME}" "${_cmake_config_file}")
    get_filename_component(_cmake_config_rel_dir "${_cmake_config_rel_dir}" DIRECTORY)
    if(_cmake_config_rel_dir)
      string(REPLACE "/" "\\" _cmake_config_group "${_cmake_config_rel_dir}")
      source_group("CMake configs\\${_cmake_config_group}" FILES "${_cmake_config_file}")
    else()
      source_group("CMake configs" FILES "${_cmake_config_file}")
    endif()
  endforeach()

  add_custom_target(defold_cmake_configs SOURCES ${_cmake_config_files})
  set_target_properties(defold_cmake_configs PROPERTIES FOLDER "CMake configs")
endfunction()

function(defold_xcode_organize_project)
  if(NOT CMAKE_GENERATOR STREQUAL "Xcode")
    return()
  endif()

  set_property(GLOBAL PROPERTY USE_FOLDERS ON)
  set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMake configs")
  defold_finalize_xcode_run_tests()
  defold_xcode_collect_targets(_targets "${CMAKE_SOURCE_DIR}")
  list(REMOVE_DUPLICATES _targets)

  set(_engine_target_entries)
  set(_cmake_target_entries)
  set(_other_target_entries)
  foreach(_target IN LISTS _targets)
    get_target_property(_target_source_dir ${_target} SOURCE_DIR)
    get_target_property(_target_type ${_target} TYPE)
    defold_xcode_get_engine_module("${_target_source_dir}" _target_module)

    if(_target_module)
      if(_target_type STREQUAL "UTILITY")
        set(_target_folder "CMake configs/${_target_module}")
      elseif(_target MATCHES "^test_" OR _target MATCHES "^run_test_" OR _target_source_dir MATCHES "/test(s)?(/|$)")
        set(_target_folder "Engine/${_target_module}/tests")
      else()
        set(_target_folder "Engine/${_target_module}/sources")
      endif()
    elseif(_target_type STREQUAL "UTILITY")
      set(_target_folder "CMake configs")
    else()
      set(_target_folder "Engine")
    endif()

    set(_target_entry "${_target_folder}|${_target}")
    if(_target_folder MATCHES "^Engine(/|$)")
      list(APPEND _engine_target_entries "${_target_entry}")
    elseif(_target_folder MATCHES "^CMake configs(/|$)")
      list(APPEND _cmake_target_entries "${_target_entry}")
    else()
      list(APPEND _other_target_entries "${_target_entry}")
    endif()
  endforeach()

  list(SORT _engine_target_entries)
  list(SORT _cmake_target_entries)
  list(SORT _other_target_entries)

  foreach(_target_entry IN LISTS _engine_target_entries _cmake_target_entries _other_target_entries)
    string(REGEX REPLACE "^(.+)\\|[^|]+$" "\\1" _target_folder "${_target_entry}")
    string(REGEX REPLACE "^.+\\|([^|]+)$" "\\1" _target "${_target_entry}")
    set_target_properties(${_target} PROPERTIES FOLDER "${_target_folder}")
    defold_xcode_source_group(${_target} "${_target_folder}")
  endforeach()

  defold_xcode_add_cmake_config_target()
endfunction()
