defold_log("functions_codesigning.cmake:")

function(defold_codesign_target target entitlements)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "defold_codesign_target: target not found: ${target}")
    endif()

    if(NOT DEFOLD_CODESIGN)
        return()
    endif()
    if(NOT TARGET_PLATFORM MATCHES "macos|win32$")
        return()
    endif()

    if(DEFOLD_PYTHON)
        set(_defold_codesign_python "${DEFOLD_PYTHON}")
    else()
        find_program(_defold_codesign_python NAMES python3 python REQUIRED)
    endif()

    set(_defold_codesign_args
        --platform "${TARGET_PLATFORM}"
        --file "$<TARGET_FILE:${target}>")
    if(DEFINED ENV{GITHUB_WORKFLOW} AND TARGET_PLATFORM MATCHES "win32$")
        # Ninja includes POST_BUILD signing in the link task's duration. Time the
        # linker separately so CI can distinguish link cost from signing cost.
        get_target_property(_defold_link_launcher "${target}" CXX_LINKER_LAUNCHER)
        set(_defold_timed_link_launcher "${CMAKE_COMMAND}" -E time)
        if(_defold_link_launcher)
            list(APPEND _defold_timed_link_launcher ${_defold_link_launcher})
        endif()
        set_property(TARGET "${target}" PROPERTY CXX_LINKER_LAUNCHER "${_defold_timed_link_launcher}")
        list(APPEND _defold_codesign_args --timings)
    endif()
    if(DEFOLD_CODESIGNING_IDENTITY)
        list(APPEND _defold_codesign_args --codesigning-identity "${DEFOLD_CODESIGNING_IDENTITY}")
    endif()
    if(DEFOLD_GCLOUD_PROJECTID)
        list(APPEND _defold_codesign_args --gcloud-projectid "${DEFOLD_GCLOUD_PROJECTID}")
    endif()
    if(DEFOLD_GCLOUD_LOCATION)
        list(APPEND _defold_codesign_args --gcloud-location "${DEFOLD_GCLOUD_LOCATION}")
    endif()
    if(DEFOLD_GCLOUD_KEYRINGNAME)
        list(APPEND _defold_codesign_args --gcloud-keyringname "${DEFOLD_GCLOUD_KEYRINGNAME}")
    endif()
    if(DEFOLD_GCLOUD_KEYNAME)
        list(APPEND _defold_codesign_args --gcloud-keyname "${DEFOLD_GCLOUD_KEYNAME}")
    endif()
    if(DEFOLD_GCLOUD_CERTFILE)
        list(APPEND _defold_codesign_args --gcloud-certfile "${DEFOLD_GCLOUD_CERTFILE}")
    endif()
    if(DEFOLD_GCLOUD_KEYFILE)
        list(APPEND _defold_codesign_args --gcloud-keyfile "${DEFOLD_GCLOUD_KEYFILE}")
    endif()
    if(entitlements)
        if(IS_ABSOLUTE "${entitlements}")
            list(APPEND _defold_codesign_args --codesigning_entitlements "${entitlements}")
        else()
            list(APPEND _defold_codesign_args --codesigning_entitlements "${CMAKE_CURRENT_SOURCE_DIR}/${entitlements}")
        endif()
    endif()

    add_custom_command(TARGET "${target}" POST_BUILD
        COMMAND "${_defold_codesign_python}" "${DEFOLD_HOME}/build_tools/codesigning.py" ${_defold_codesign_args}
        COMMENT "Signing ${target}"
        VERBATIM)
endfunction()
