if(DEFINED DEFOLD_PRIVATE_REPOS_CMAKE_INCLUDED)
  return()
endif()
set(DEFOLD_PRIVATE_REPOS_CMAKE_INCLUDED ON)

if(NOT DEFINED DEFOLD_HOME)
  get_filename_component(DEFOLD_HOME "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()

set(DEFOLD_PRIVATE_REPO_ROOTS "")
set(_DEFOLD_PRIVATE_PLATFORMS_CONFIG "${DEFOLD_HOME}/.defold-platforms")
if(EXISTS "${_DEFOLD_PRIVATE_PLATFORMS_CONFIG}")
  file(READ "${_DEFOLD_PRIVATE_PLATFORMS_CONFIG}" _DEFOLD_PRIVATE_PLATFORMS_JSON)
  string(REGEX MATCHALL "\"[^\"]+\"[ \t\r\n]*:[ \t\r\n]*\\{[^\\}]*\"root\"[ \t\r\n]*:[ \t\r\n]*\"[^\"]+\"" _DEFOLD_PRIVATE_PLATFORM_ENTRIES "${_DEFOLD_PRIVATE_PLATFORMS_JSON}")
  foreach(_entry IN LISTS _DEFOLD_PRIVATE_PLATFORM_ENTRIES)
    string(REGEX MATCH "\"([^\"]+)\"[ \t\r\n]*:" _platform_match "${_entry}")
    set(_private_platform "${CMAKE_MATCH_1}")
    string(REGEX MATCH "\"root\"[ \t\r\n]*:[ \t\r\n]*\"([^\"]+)\"" _root_match "${_entry}")
    set(_private_root "${CMAKE_MATCH_1}")
    if(_private_platform AND _private_root)
      string(REPLACE "\\\\" "/" _private_root "${_private_root}")
      string(REPLACE "\\" "/" _private_root "${_private_root}")
      file(TO_CMAKE_PATH "${_private_root}" _private_root)
      if(EXISTS "${_private_root}")
        list(APPEND DEFOLD_PRIVATE_REPO_ROOTS "${_private_root}")
        string(TOUPPER "${_private_platform}" _private_platform_var)
        string(REPLACE "-" "_" _private_platform_var "${_private_platform_var}")
        set("DEFOLD_PRIVATE_REPO_ROOT_${_private_platform_var}" "${_private_root}" CACHE PATH "Private repository root for ${_private_platform}" FORCE)

        set(_private_cmake_dir "${_private_root}/scripts/cmake")
        if(EXISTS "${_private_cmake_dir}")
          list(FIND CMAKE_MODULE_PATH "${_private_cmake_dir}" _private_cmake_idx)
          if(_private_cmake_idx EQUAL -1)
            list(APPEND CMAKE_MODULE_PATH "${_private_cmake_dir}")
          endif()
        endif()
      endif()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES DEFOLD_PRIVATE_REPO_ROOTS)
endif()
