-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local function state(self)
    return self.states[self.state]
end

local function next_state(self)
    self.state = self.state + 1
end

local function delete_gameobjects()
    if first_instance ~= nil then
        go.delete(first_instance, true)
        first_instance = nil
    end

    if second_instance ~= nil then
        go.delete(second_instance, true)
        second_instance = nil
    end

    global_created = nil
end

local function create_gameobjects(url)
    first_instance = factory.create(url)
    second_instance = factory.create(url)
    global_created = true
end

local function handle_state(self)
    local current_state = state(self)

    if current_state == "load" then
        assert(factory.get_status("/go#factory") == factory.STATUS_UNLOADED)
        self.loading = true
        factory.load("/go#factory", load_complete)
        assert(factory.get_status("/go#factory") == factory.STATUS_LOADING)
    elseif current_state == "unload_delete" then
        assert(factory.get_status("/go#factory") == factory.STATUS_LOADED)
        factory.unload("/go#factory")
        delete_gameobjects()
        next_state(self)
    elseif current_state == "unload_keep" then
        assert(factory.get_status("/go#factory") == factory.STATUS_LOADED)
        factory.unload("/go#factory")
        next_state(self)
    elseif current_state == "unload" then
        factory.unload("/go#factory")
        next_state(self)
    elseif current_state == "delete" then
        delete_gameobjects()
        next_state(self)
    elseif current_state == "create" then
        create_gameobjects("/go#factory")
        next_state(self)
    elseif current_state == "load_prototype" then
        assert(prototype_path ~= nil)
        factory.set_prototype("/go#factory", prototype_path)
        self.loading = true
        factory.load("/go#factory", load_complete)
    elseif current_state == "unload_prototype" then
        factory.unload("/go#factory")
        factory.set_prototype("/go#factory", nil)
        next_state(self)
    end
end

function init(self)
    self.loading = false
    self.state = 1
    self.states = { "load", "unload_delete", "load", "unload_keep", "unload", "delete", "create" }

    if prototype_path ~= nil then
        table.insert(self.states, "unload")
        table.insert(self.states, "delete")
        table.insert(self.states, "load_prototype")
        table.insert(self.states, "unload_prototype")
        table.insert(self.states, "delete")
    end
end

function load_complete(self, url, result)
    assert(result == true)
    create_gameobjects(url)
    self.loading = false
    next_state(self)
end

function update(self, dt)
    if self.loading then
        return
    end

    handle_state(self)
end

function final(self)
    delete_gameobjects()
end
