-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.


function init(self)
    self.load = true
    self.loaded = false
    self.repeatloadunload = true
    self.testunloadtwice = false
    self.delete = false
    self.create = false
end

function load_complete(self, url, result)
    assert(result == true)
    first_instance = factory.create(url)
    second_instance = factory.create(url)
    self.loaded = true
    global_created = true
end

function update(self, dt)

    --- step 1 ---
    if self.load == true then
        self.load = false
        assert(factory.get_status("/go#factory") == factory.STATUS_UNLOADED)
        factory.load("/go#factory", load_complete)
        assert(factory.get_status("/go#factory") == factory.STATUS_LOADING)
        return
    end

    --- step 2 ---
    if self.loaded == true then
        self.loaded = false
        assert(factory.get_status("/go#factory") == factory.STATUS_LOADED)
        factory.unload("/go#factory")
        if self.repeatloadunload == true then
           self.repeatloadunload = false
           self.load = true
            go.delete(first_instance, true)
            go.delete(second_instance, true)
            global_created = nil
        else
            self.testunloadtwice = true
        end
        return
    end

    --- step 3 ---
    if self.testunloadtwice == true then
        self.testunloadtwice = false
        self.delete = true
        factory.unload("/go#factory")
        return
    end

    --- step 4 ---
    if self.delete == true then
        self.delete = false
        self.create = true
        go.delete(first_instance, true)
        go.delete(second_instance, true)
        global_created = nil
        return
    end

    --- step 5 ---
    if self.create == true then
        self.create = false
        first_instance = factory.create("/go#factory")
        second_instance = factory.create("/go#factory")
        global_created = true
        return
    end
end

function final(self)
    go.delete(first_instance, true)
    go.delete(second_instance, true)
    global_created = nil
    first_instance = nil
    second_instance = nil
end
