from waf_dynamo import dmsdk_add_files

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.recurse('gameobject')
    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')
