from waf_dynamo import dmsdk_add_files

def set_options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.add_subdirs('gameobject')
    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')
