#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    resource = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                                includes = '.',
                                target = 'gui')
    resource.find_sources_in_dirs('.')

    #bld.add_subdirs('test')
    bld.install_files('${PREFIX}/include/gui', 'gui.h')

    bld.new_task_gen(source = 'gui_script.cpp',
                     target = 'gui_doc.sdoc',
                     rule = '${SCRIPT_DOC} ${SRC} ${TGT}')

    bld.new_task_gen(source = 'gui_script.cpp',
                     target = 'gui_doc.json',
                     rule = '${SCRIPT_DOC} -t json ${SRC} ${TGT}')

    bld.install_files('${PREFIX}/share/doc', 'gui_doc.sdoc')
    bld.install_files('${PREFIX}/share/doc', 'gui_doc.json')
