#! /usr/bin/env python
import os
from waf_dynamo import dmsdk_add_files, apidoc_extract_task

def configure(conf):
    pass

def build(bld):
    resource = bld.__call__(features = 'cxx cstaticlib ddf',
                                includes = '.',
                                source = 'gui.cpp gui_script.cpp',
                                target = 'gui')

    resource = bld.__call__(features = 'cxx cstaticlib ddf',
                                includes = '.',
                                source = 'gui_null.cpp',
                                target = 'gui_null')

    bld.recurse('test')

    # the dmsdk_add_files needs to be after a build group for some reason
    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')

    bld.install_files('${PREFIX}/include/gui', 'gui.h')
    bld.install_files('${PREFIX}/include/gui', 'gui_script.h')

    apidoc_extract_task(bld, ['gui_script.cpp'])
