function Init(self)
	local p = self.Position
	assert( p.X == 0 )
	assert( p.Y == 0 )
	assert( p.Z == 0 )
	
	self.Counter = 0
	assert (self.Counter == 0)
	
	self.Counter = self.Counter +  1
	assert (self.Counter == 1)
	tmp = "1";
end

function Update(self)
	assert (self.Counter == 1)		

	local p = self.Position
	
	p.Y = 123.0
	self.Position = p
	
	p = self.Position
	assert(p.Y == 123.0)
	
	assert(self.UIntValue == 12345)
	assert(self.IntValue == -123)
	assert(self.StringValue == "string_value")

	assert(self.VecValue.X == 1.0)
	assert(self.VecValue.Y == 2.0)
	assert(self.VecValue.Z == 3.0)
	
	Post("Spawn", {Prototype = "test", Pos = { X=1, Y=2, Z=3 }} )
end

function OnEvent(self, type, event)
	assert(type == "SpawnResult")
	assert(event.Status == 1010)
end

functions = { Init = Init, Update = Update, OnEvent = OnEvent }

