function Init(self)
	local p = self.Position
	assert( p[0] == 0 )
	assert( p[1] == 0 )
	assert( p[2] == 0 )
	
	self.Counter = 0
	assert (self.Counter == 0)
	
	self.Counter = self.Counter +  1
	assert (self.Counter == 1)
	tmp = "1";
end

function Update(self)
	assert (self.Counter == 1)		

	local p = self.Position
	
	p[1] = 123.0
	self.Position = p
	
	p = self.Position
	assert(p[1] == 123.0)
	
	assert(self.UIntValue == 12345)
	assert(self.IntValue == -123)
	assert(self.StringValue == "string_value")

	assert(self.VecValue[0] == 1.0)
	assert(self.VecValue[1] == 2.0)
	assert(self.VecValue[2] == 3.0)
	
	post("Spawn", {Prototype = "test", X=1, Y=2, Z=3})
end

functions = { Init = Init, Update = Update }

