import sys, os

import Task, TaskGen
from TaskGen import extension, declare_extension

import waf_gamesys

def build(bld):
    dirs = ['camera', 'collision_object', 'convex_shape', 'vertex_program']
    exts = ['camera', 'collisionobject', 'convexshape', 'vp']
    test_task_gen = bld.new_task_gen(features = 'cxx cprogram',
                                     includes = '../../../src ../../../proto %s' % (dir),
                                     uselib = 'GTEST GAMEOBJECT DDF RESOURCE GRAPHICS_UTIL DLIB PHYSICS RENDER GRAPHICS_NULL PLATFORM_SOCKET LUA SCRIPT HID_NULL INPUT PARTICLE GUI SOUND_NULL',
                                     uselib_local = 'gamesys',
                                     proto_gen_py = True,
                                     content_root='.',
                                     target = 'test_gamesys')
    test_task_gen.find_sources_in_dirs('. ' + ' '.join(dirs), exts)
    test_task_gen.install_path = None

    bld.add_subdirs('fontview')

