import sys, os

import Task, TaskGen
from TaskGen import extension, declare_extension

import waf_gamesys

def build(bld):
    def new_test(dir, exts = ['.cpp', '.proto', '.go']):
        test_task_gen = bld.new_task_gen(features = 'cxx cprogram',
                                         includes = '../../../src ../../../proto %s' % (dir),
                                         uselib = 'GTEST GAMEOBJECT DDF RESOURCE GRAPHICS_UTIL DLIB PHYSICS RENDER GRAPHICS_NULL PLATFORM_SOCKET LUA SCRIPT HID_NULL INPUT PARTICLE GUI SOUND_NULL',
                                         uselib_local = 'gamesys',
                                         proto_gen_py = True,
                                         content_root=dir,
                                         target = '%s/test_gamesys_%s' % (dir, dir))
        test_task_gen.find_sources_in_dirs(dir + ' .', exts)
        test_task_gen.install_path = None

    new_test('camera', exts = ['.cpp'])
    new_test('collision_object', exts = ['.cpp', '.go', '.collisionobject', '.convexshape'])

    bld.add_subdirs('fontview')

