#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    bld.program(features         = 'c cprogram cxx',
                use              = 'DLIB TEXC PROFILE_NULL PLATFORM_NULL BASIS_ENCODER',
                source           = 'main.cpp',
                target           = 'texconvert')
