#! /usr/bin/env python

from waf_dynamo import dmsdk_add_files

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(features = 'cxx cstaticlib ddf',
                     includes = ['.', '..', '../proto'],
                     proto_gen_py = True,
                     protoc_includes = '../proto',
                     target = 'rig',
                     uselib = 'DDF DLIB PLATFORM_SOCKET',
                     source = 'rig.cpp ../proto/rig/rig_ddf.proto')

    bld.install_files('${PREFIX}/include/rig', 'rig.h')
    bld.install_files('${PREFIX}/share/proto', '../proto/rig/rig_ddf.proto')

    bld.add_subdirs('test')

    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')
