#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    rig = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                           includes = ['.', '../proto'],
                           proto_gen_py = True,
                           protoc_includes = '../proto',
                           target = 'rig',
                           uselib = 'DDF DLIB PLATFORM_SOCKET',
                           source = 'rig.cpp rig_util.cpp ../proto/rig/rig_ddf.proto')


    rig_shared = bld.new_task_gen(features = 'cxx cshlib ddf',
                                  includes = ['.', '../proto'],
                                  target = 'rig_shared',
                                  protoc_includes = '../proto',
                                  uselib = 'DDF DLIB PLATFORM_SOCKET',
                                  source = 'rig.cpp rig_util.cpp ../proto/rig/rig_ddf.proto')

    bld.install_files('${PREFIX}/include/rig', 'rig.h')
    bld.install_files('${PREFIX}/share/proto', '../proto/rig/rig_ddf.proto')

    bld.add_subdirs('test')
