#! /usr/bin/env python

def build(bld):
    bld.program(features = 'cxx test',
                includes = '. ..',
                use = 'DLIB PROFILE SPIRV_CROSS shaderc',
                target = 'test_shaderc',
                source = 'test_shaderc.cpp')
