#! /usr/bin/env python
import os

def build(bld):

    if 'darwin' in bld.env.PLATFORM:
        open_url_source = 'open_url.mm'
    else:
        open_url_source = 'open_url.cpp'

    open_url = bld.new_task_gen(features = 'cxx cprogram',
                                 source = open_url_source,
                                 uselib = 'THREAD SOL_RUNTIME SOL',
                                 uselib_local = "dlib",
                                 includes = ['../../src'],
                                 target = 'open_url')

    open_url.install_path = None
