#! /usr/bin/env python

VERSION = '0.1'
APPNAME = 'bob'

srcdir = '.'
blddir = 'build'

import os, sys
import Options

def init():
    pass

def set_options(opt):
    # Compatibility with waf_dynamo
    opt.add_option('--skip-tests', action='store_true', default=False, dest='skip_tests', help='skip unit tests')
    opt.add_option('--eclipse', action='store_true', default=False, dest='eclipse', help='print eclipse friendly command-line')

def configure(conf):
    conf.check_tool('waf_dynamo')

def build(bld):
    bld.new_task_gen(rule = 'protoc ${SRC} --python_out=${TGT[0].dir(env)} -I../test_data',
                     source = 'test_data/test_bob_ddf.proto',
                     target = 'test_bob_ddf_pb2.py')

    # copy bob.py to bob for later installation below
    bld.new_task_gen(rule = 'cat < ${SRC} > ${TGT}',
                     source = 'src/bob.py',
                     target = 'bob')

    bld.add_group()

    bld.install_files('${PREFIX}/bin', 'bob', chmod=493)
    bld.install_files('${PREFIX}/lib/python', 'src/bob_pipeline.py')

def shutdown(ctx):
    if not Options.commands['build'] or getattr(Options.options, 'skip_tests', False):
        return

    # unit-test currently requires gcc
    if sys.platform == 'win32':
        return

    ret = os.system('python src/test/test_bob.py')
    if ret != 0: raise Exception('unit-test failed')

    dynamo_home = os.getenv('DYNAMO_HOME')
    classpath = [os.path.join(dynamo_home,'ext/share/java/jython.jar'),
                 'src',
                 os.path.join(dynamo_home, 'ext/lib/python/protobuf-2.3.0-py2.5.egg')]

    ret = os.system('java -cp %s org.python.util.jython src/test/test_bob.py' %
                    os.pathsep.join(classpath))
    if ret != 0: raise Exception('unit-test failed')

