function init(self)
    -- Add initialization code here
    -- Remove this function if not needed
    self.ticks = 0
end

function final(self)
    -- Add finalization code here
    -- Remove this function if not needed
end

function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
    self.ticks = self.ticks + 1
    if 10 == self.ticks then
        -- Validate that spine component position is applied to the bone position DEF-3132 
        local pos = go.get_world_position(spine.get_go("go#spinemodel", "root"))
        if pos.x ~= 200.0 then
            print("Invalid bone x pos: ", pos.x, " expected it to be 200")
        	msg.post("@system:", "exit", { code = 1 })
        else      
        	msg.post("@system:", "exit", { code = 0 })
        end
    end
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Remove this function if not needed
end

function on_input(self, action_id, action)
    -- Add input-handling code here
    -- Remove this function if not needed
end

function on_reload(self)
    -- Add reload-handling code here
    -- Remove this function if not needed
end
