#! /usr/bin/env python
import os

def configure(conf):
    conf.sub_config('test')

def build(bld):
    resource = bld.new_task_gen(features = 'cxx cstaticlib ddf embed',
                                includes = '. ../../proto',
                                proto_gen_py = True,
                                protoc_includes = '../../proto',
                                target = 'gamesys',
                                embed_source='../../content/materials/gui.vpc ../../content/materials/gui.fpc')

    resource.find_sources_in_dirs(['.', 'resources', 'components', 'scripts', '../../proto'])
    bld.add_group()

    for d, source in [('camera', ('../../proto/camera_ddf.proto')),
                      ('collection_proxy', ('components/comp_collection_proxy.cpp')),
                      ('factory', ('scripts/script_factory.cpp')),
                      ('collection_factory', ('scripts/script_collection_factory.cpp')),
                      ('particlefx', ('scripts/script_particlefx.cpp')),
                      ('collision_object', ('../../proto/physics_ddf.proto', 'scripts/script_physics.cpp')),
                      ('sound', ('components/comp_sound.cpp', 'scripts/script_sound.cpp')),
                      ('sprite', ('../../proto/sprite_ddf.proto', 'scripts/script_sprite.cpp')),
                      ('tilemap', ('../../proto/tile_ddf.proto', 'scripts/script_tilemap.cpp')),
                      ('spine', ('../../proto/spine_ddf.proto', 'scripts/script_spine_model.cpp'))
                      ]:
        bld.new_task_gen(source = source,
                         target = '%s_doc.sdoc' % d,
                         rule = '${SCRIPT_DOC} ${SRC} ${TGT}')
        bld.new_task_gen(source = source,
                         target = '%s_doc.json' % d,
                         rule = '${SCRIPT_DOC} -t json ${SRC} ${TGT}')
        bld.install_files('${PREFIX}/share/doc', '%s_doc.sdoc' % d)
        bld.install_files('${PREFIX}/share/doc', '%s_doc.json' % d)

    bld.add_group()
    #bld.add_subdirs('test')

    bld.install_files('${PREFIX}/include/gamesys', 'gamesys.h')
    bld.install_files('${PREFIX}/share/proto', '../../proto/physics_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../../proto/gui_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../../proto/gamesys_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../../proto/model_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../../proto/mesh_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../../proto/sprite_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../../proto/spine_ddf.proto')
