local checked_lua = require "checked"

go.property("boolean", false)
go.property("number", 0)
go.property("text", "")
go.property("vector3", vmath.vector3())
go.property("vector4", vmath.vector4())
go.property("quat", vmath.quat())
go.property("matrix4", vmath.matrix4())
go.property("url", msg.url())
go.property("texture", resource.texture("/referenced/images/white.png"))

function init(self)
	print("init() called from `/checked.script`.")
end
