#! /usr/bin/env python
import os

from waf_dynamo import apidoc_extract_task

def set_options(opt):
    pass

def configure(conf):
    conf.env.append_value('CPPPATH', "../src")

def build(bld):
    apidoc_extract_task(bld, ['lua_base.doc_h', 'lua_string.doc_h', 'lua_coroutine.doc_h',
                            'lua_debug.doc_h', 'lua_io.doc_h', 'lua_math.doc_h', 'lua_os.doc_h',
                            'lua_package.doc_h', 'lua_table.doc_h'])
    bld.add_subdirs('lua')

    bld.install_files('${PREFIX}/sdk/include/dmsdk/lua', 'dmsdk/lua/lua.h')
    bld.install_files('${PREFIX}/sdk/include/dmsdk/lua', 'dmsdk/lua/lauxlib.h')
    bld.install_files('${PREFIX}/sdk/include/dmsdk/lua', 'dmsdk/lua/luaconf.h')
