-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
	self.child_id   = go.get_id("child")
	self.parent_id  = go.get_id("parent")
	self.stage      = -1
end

function update(self)
	self.stage = self.stage + 1
	if self.stage == 0 then
		go.set_parent(self.child_id,self.parent_id)
	elseif self.stage == 1 then
		go.set_parent(self.child_id)
	elseif self.stage == 2 then
		go.set_parent(self.child_id, self.parent_id, true)
	elseif self.stage == 3 then
		go.set_parent(self.child_id, "not-found")
	elseif self.stage == 4 then
		go.set_parent()
	end
end