function update(self)
    post("game_object_transform_query", { game_object_id = ident(self, "target") })
    if self.target_pos then
        local pos = get_position(self)
        local dir = vec_math.normalize(self.target_pos - pos)
        spawn("bullet.goc", vec_math.point3(pos.x, pos.y, pos.z), vec_math.quat_from_start_to_end(vec_math.vector3(1, 0, 0), dir))
    end
end

function on_message(self, message_id, message)
    if message_id == hash("game_object_transform_result") then
        self.target_pos = message.position
    end
end