function update(self)
    go.post("game_object_transform_query", { game_object_id = go.get_id(self, "target") })
    if self.target_pos then
        local pos = go.get_position(self)
        local dir = vmath.normalize(self.target_pos - pos)
        go.spawn("bullet.goc", pos, vmath.quat_from_to(vmath.vector3(1, 0, 0), dir))
    end
end

function on_message(self, message_id, message)
    if message_id == hash("game_object_transform_result") then
        self.target_pos = message.position
    end
end