#! /usr/bin/env python

def build(bld):
    test_hashtable = bld.new_task_gen(features = 'cxx cprogram',
                                      source = 'test_hashtable.cpp',
                                      uselib = 'GTEST',
                                      includes = ['../../src'],
                                      target = 'test_hashtable')

    test_hashtable.install_path = None

    test_array = bld.new_task_gen(features = 'cxx cprogram',
                                      source = 'test_array.cpp',
                                      uselib = 'GTEST',
                                      uselib_local = "dlib",
                                      includes = ['../../src'],
                                      target = 'test_array')

    test_array.install_path = None

    test_iterator = bld.new_task_gen(features = 'cxx cprogram',
                                      source = 'test_iterator.cpp',
                                      uselib = 'GTEST',
                                      uselib_local = "dlib",
                                      includes = ['../../src'],
                                      target = 'test_iterator')

    test_iterator.install_path = None

    test_dlib = bld.new_task_gen(features = 'cxx cprogram',
                                      source = 'test_dlib.cpp',
                                      uselib = 'GTEST',
                                      uselib_local = "dlib",
                                      includes = ['../../src'],
                                      target = 'test_dlib')

    test_dlib.install_path = None

