#! /usr/bin/env python
import os

def build(bld):
    test_graphics = bld.new_task_gen(features = 'cxx cprogram',
                                 source = 'test_graphics.cpp',
                                 uselib = 'GTEST DLIB',
                                 uselib_local = "graphics_null",
                                 includes = ['../../src'],
                                 target = 'test_graphics',
                                 defines = 'DM_NULL')

    test_graphics.install_path = None
