-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

go.property("number", 1)
go.property("hash", hash("hash"))
go.property("url", msg.url())
go.property("vec3", vmath.vector3())
go.property("vec4", vmath.vector4())
go.property("quat", vmath.quat())
go.property("bool", false)

function init(self)
    assert(self.number == 3)
    assert(self.hash == hash("hash3"))
    assert(self.url == msg.url("url3"))
    assert(self.vec3 == vmath.vector3(11, 12, 13))
    assert(self.vec4 == vmath.vector4(14, 15, 16, 17))
    assert(self.quat == vmath.quat(18, 19, 20, 21))
    assert(self.bool == true)
end
