function init(self)
    assert(go.exists("a"), "Expected go 'a' to exist")
    assert(go.exists("b"), "Expected go 'b' to exist")
    assert(go.exists(hash("a")), "Expected go hash('a') to exist")
    assert(go.exists(hash("b")), "Expected go hash('b') to exist")
    assert(go.exists(msg.url(nil, "a", nil)), "Expected go msg.url(nil, 'a', nil) to exist")
    assert(go.exists(msg.url(nil, "b", nil)), "Expected go msg.url(nil, 'b', nil) to exist")
    assert(not go.exists("unknown"), "Expected go 'unknown' to not exist")
    if pcall(go.exists, nil) then
        assert(false, "Error expected when calling go.exists with nil")
    end
    assert(not go.exists("foo:/bar"), "Expected go 'foo:/bar' (non-existent collection) to not exist")
    assert(go.exists(), "Object itself always exists")
end
