function init(self)
    assert(go.get_id() == hash("my_object01"), "init id mismatch")
    local p = go.get_position()
    assert(p.x == 0)
    assert(p.y == 0)
    assert(p.z == 0)

    local s = go.get_scale()
    assert(s == 1)

    self.counter = 0
    assert(self.counter == 0)

    self.counter = self.counter +  1
    assert(self.counter == 1)
    tmp = "1";
end

function update(self, dt)
    assert(go.get_id() == hash("my_object01"), "update id mismatch")
    assert(dt > 0, "no dt in update")
    assert(self.counter == 1)

    local p = go.get_position()

    p.y = 123.0
    go.set_position(p)

    p = go.get_position()
    assert(p.y == 123.0)

    p = go.get_position("my_object01")
    assert(p.y == 123.0)

    p = go.get_position(hash("my_object01"))
    assert(p.y == 123.0)

    go.set_scale(2)
    local s = go.get_scale()
    assert(s == 2)

    msg.post("@system:", "factory", {prototype = "test", pos = vmath.vector3(1, 2, 3)})
end

function on_message(self, message_id, message)
    assert(go.get_id() == hash("my_object01"), "on_message id mismatch")
    assert(message_id == hash("factory_result"))
    assert(message.status == 1010)
end

function on_input(self, action_id, action)
    assert(go.get_id() == hash("my_object01"), "on_input id mismatch")
    assert(action_id == hash("test_action"), "on_input action id mismatch")
end
