-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    -- string form
    assert(msg.url("") == msg.url(), "component mismatch")
    assert(msg.url(nil) == msg.url(), "component mismatch")
    assert(msg.url(".") == msg.url(go.get_id()), "instance mismatch")
    assert(msg.url("#") == msg.url(), "component mismatch")
    assert(msg.url("#script") == msg.url(), "component mismatch")
    assert(msg.url("test_id") == msg.url(go.get_id()), "component mismatch")
    assert(msg.url("test_id") == msg.url(go.get_id()), "component mismatch")
    -- 3-arg form
    assert(msg.url(nil, nil, nil) == msg.url(), "component mismatch")
    assert(msg.url(nil, nil, "script") == msg.url(), "instance mismatch")
    assert(msg.url(nil, "test_id", "script") == msg.url(), "collection mismatch")
    assert(msg.url("collection", "test_id", "script") == msg.url(), "complete mismatch")
    assert(msg.url("collection", "test_id", nil) == msg.url(go.get_id()), "complete mismatch")
    assert(msg.url("collection", nil, nil) == msg.url("collection:"), "complete mismatch")
end
