local function assert_near(label, exp, act, eps)
    assert(math.abs(exp - act) < eps, string.format("%s: expected %f but was %f", label, exp, act))
end

local eps = 0.0001

function update(self, dt)
    local result = go.world_to_local_position(_G.WORLD_POS_INPUT, hash("target"))
    assert_near("x", _G.EXPECTED_X, result.x, eps)
    assert_near("y", _G.EXPECTED_Y, result.y, eps)
    assert_near("z", _G.EXPECTED_Z, result.z, eps)
end
