#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    resource = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                                includes = '.',
                                target = 'gui',
                                install_path='${PREFIX}/lib')
    resource.find_sources_in_dirs('.')

    bld.add_subdirs('test')
    bld.install_files('${PREFIX}/include/gui', 'gui.h')
