#!/usr/bash

function _setjdk {
	export PATH=$JAVA_HOME/bin:$PATH
	java -version
}

function _jdk11 {
	export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
	export PATH=$JAVA_HOME/bin:$PATH
}

_jdk11

pyenv versions

echo "DEFOLD DOCKER"
