#! /usr/bin/env python
import os, sys, re

def configure(conf):
    pass

def build(bld):

    source = ["Alc/ALc.c",
              "Alc/alcConfig.c",
              "Alc/alcRing.c",
              "Alc/alcThread.c",
              "Alc/ALu.c",
              "Alc/backends/opensl.c",
              "Alc/backends/loopback.c",
              "Alc/backends/null.c",
              "Alc/backends/wave.c",
              "Alc/bs2b.c",
              "Alc/effects/chorus.c",
              "Alc/effects/dedicated.c",
              "Alc/effects/distortion.c",
              "Alc/effects/echo.c",
              "Alc/effects/equalizer.c",
              "Alc/effects/flanger.c",
              "Alc/effects/modulator.c",
              "Alc/effects/null.c",
              "Alc/effects/reverb.c",
              "Alc/helpers.c",
              "Alc/hrtf.c",
              "Alc/mixer.c",
              "Alc/mixer_c.c",
              "Alc/panning.c",
              "OpenAL32/alAuxEffectSlot.c",
              "OpenAL32/alBuffer.c",
              "OpenAL32/alEffect.c",
              "OpenAL32/alError.c",
              "OpenAL32/alExtension.c",
              "OpenAL32/alFilter.c",
              "OpenAL32/alListener.c",
              "OpenAL32/alSource.c",
              "OpenAL32/alState.c",
              "OpenAL32/alThunk.c"]

    if re.match('arm.*?android', bld.env['PLATFORM']):

        openal_soft = bld.new_task_gen(features = 'cc cstaticlib',
                                       includes = '. config/armv7-android include OpenAL32/Include',
                                       source = source,
                                       defines = 'AL_ALEXT_PROTOTYPES',
                                       target = 'openal_soft')

