#!/usr/bin/env python3
"""Regenerate checked-in capture shaders with Defold's host shader tools.

Edit graphics_capture.vert or graphics_capture*.frag, then run this command with
--glslang, --shaderc (shaderc_standalone) and --tint pointing to host executables.
See graphics_reference/README.md for build and invocation examples.
"""
import argparse
from pathlib import Path
import shutil
import subprocess
import tempfile


SOURCE_DIR = Path(__file__).resolve().parent
SHADERS = (('vert', 'vp'), ('frag', 'fp'), ('cube.frag', 'cube.fp'), ('texture.frag', 'texture.fp'))
WGSL_HELPER = SOURCE_DIR.parents[3] / 'com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/WgslShader.java'
GENERATED = '// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.\n'


def add_wgsl_flipped_entry_point(path, java):
    subprocess.run([java, str(WGSL_HELPER), str(path)], check=True)


def read_shader(path):
    source = path.read_text(encoding='utf-8').rstrip('\0\n')
    if not source.strip():
        raise ValueError('Compiler produced an empty shader: ' + path.name)
    return source + '\n'


def write_shaders(outputs, output_dir, check):
    if check:
        stale = [name for name, source in outputs.items()
                 if not (output_dir / name).is_file() or (output_dir / name).read_text(encoding='utf-8') != source]
        if stale:
            raise ValueError('Stale or missing generated shaders: ' + ', '.join(stale) + '. Run generate_graphics_shaders.py without --check.')
        return
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, source in outputs.items():
        (output_dir / name).write_text(source, encoding='utf-8')


def generate(glslang, shaderc, tint, output_dir, java='java', check=False):
    with tempfile.TemporaryDirectory() as temporary:
        work = Path(temporary)
        # Tint packages may lack execute permission. Keep the installed SDK untouched.
        tint_executable = work / Path(tint).name
        shutil.copyfile(shutil.which(tint) or tint, tint_executable)
        tint_executable.chmod(0o755)
        outputs = {}
        for source_suffix, output_suffix in SHADERS:
            source = SOURCE_DIR / ('graphics_capture.' + source_suffix)
            stage = 'vert' if source_suffix == 'vert' else 'frag'
            spirv = work / (source.name + '.spv')
            subprocess.run([glslang, '-V', '-S', stage, str(source), '-o', str(spirv)], check=True)
            for language, version, suffix in (('msl', '22', '.msl'), ('glsl', '330', '')):
                shader_input = spirv
                if language == 'glsl' and stage == 'vert':
                    # Capture vertices use [0, 1] depth; OpenGL's clip range is [-1, 1].
                    shader_input = work / 'opengl.vert.spv'
                    subprocess.run([glslang, '-V', '-S', stage, '-DCAPTURE_OPENGL', str(source), '-o', str(shader_input)], check=True)
                output = work / ('graphics_capture.' + output_suffix + suffix)
                subprocess.run([shaderc, str(shader_input), '--language', language, '--version', version,
                                '--stage', stage, '--out', str(output)], check=True)
                outputs[output.name] = GENERATED + read_shader(output)
            output = work / ('graphics_capture.' + output_suffix + '.wgsl')
            subprocess.run([str(tint_executable), '--format', 'wgsl', '-o', str(output), str(spirv)], check=True)
            if stage == 'vert':
                add_wgsl_flipped_entry_point(output, java)
            outputs[output.name] = GENERATED + read_shader(output)

        # Only replace checked-in files after every compiler invocation succeeds.
        write_shaders(outputs, output_dir, check)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--glslang', required=True)
    parser.add_argument('--shaderc', required=True)
    parser.add_argument('--tint', required=True)
    parser.add_argument('--java', default='java', help='Host Java runtime for Bob’s shared WGSL transformation')
    parser.add_argument('--output-dir', type=Path, default=SOURCE_DIR)
    parser.add_argument('--check', action='store_true', help='Fail on stale or missing variants without writing files')
    args = parser.parse_args()
    try:
        generate(args.glslang, args.shaderc, args.tint, args.output_dir, args.java, args.check)
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        parser.exit(1, str(error) + '\n')


if __name__ == '__main__':
    main()
