// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.
#version 330

uniform sampler2D SPIRV_Cross_Combinedtest_texturetest_sampler;

layout(location = 0) out vec4 fragment_color;
in vec3 vertex_color;

void main()
{
    fragment_color = vec4(textureLod(SPIRV_Cross_Combinedtest_texturetest_sampler, vertex_color.xy, 0.0).xyz, 1.0);
}
