// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.
var<private> fragment_color : vec4f;

@binding(0) @group(0) var cubemap : texture_cube<f32>;

@binding(1) @group(0) var cube_sampler : sampler;

var<private> vertex_color : vec3f;

fn main_1() {
  fragment_color = textureSampleLevel(cubemap, cube_sampler, vertex_color, 0.0f);
  return;
}

struct main_out {
  @location(0)
  fragment_color_1 : vec4f,
}

@fragment
fn main(@location(0) vertex_color_param : vec3f) -> main_out {
  vertex_color = vertex_color_param;
  main_1();
  return main_out(fragment_color);
}
