// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.
var<private> fragment_color : vec4f;

var<private> vertex_color : vec3f;

fn main_1() {
  fragment_color = vec4f(vertex_color.x, vertex_color.y, vertex_color.z, 1.0f);
  return;
}

struct main_out {
  @location(0)
  fragment_color_1 : vec4f,
}

@fragment
fn main(@location(0) vertex_color_param : vec3f) -> main_out {
  vertex_color = vertex_color_param;
  main_1();
  return main_out(fragment_color);
}
