// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.
var<private> position_1 : vec3f;

var<private> vertex_color : vec3f;

var<private> color : vec3f;

var<private> gl_Position : vec4f;

fn main_1() {
  gl_Position = vec4f(position_1.x, position_1.y, position_1.z, 1.0f);
  vertex_color = color;
  return;
}

struct main_out {
  @builtin(position)
  gl_Position : vec4f,
  @location(0)
  vertex_color_1 : vec3f,
}

@vertex
fn main(@location(0) position_1_param : vec3f, @location(1) color_param : vec3f) -> main_out {
  position_1 = position_1_param;
  color = color_param;
  main_1();
  return main_out(gl_Position, vertex_color);
}

// defold-webgpu-flipped-entry-point: _defold_webgpu_main_flipped
@vertex
fn _defold_webgpu_main_flipped(@location(0) position_1_param : vec3f, @location(1) color_param : vec3f) -> main_out {
  position_1 = position_1_param;
  color = color_param;
  main_1();
  gl_Position.y = -gl_Position.y;
  return main_out(gl_Position, vertex_color);
}
