// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.
var<private> fragment_color : vec4f;

@binding(0) @group(0) var test_texture : texture_2d<f32>;

@binding(1) @group(0) var test_sampler : sampler;

var<private> vertex_color : vec3f;

fn main_1() {
  let x_28 = textureSampleLevel(test_texture, test_sampler, vertex_color.xy, 0.0f).xyz;
  fragment_color = vec4f(x_28.x, x_28.y, x_28.z, 1.0f);
  return;
}

struct main_out {
  @location(0)
  fragment_color_1 : vec4f,
}

@fragment
fn main(@location(0) vertex_color_param : vec3f) -> main_out {
  vertex_color = vertex_color_param;
  main_1();
  return main_out(fragment_color);
}
