// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.
#version 330

uniform samplerCube SPIRV_Cross_Combinedcubemapcube_sampler;

layout(location = 0) out vec4 fragment_color;
in vec3 vertex_color;

void main()
{
    fragment_color = textureLod(SPIRV_Cross_Combinedcubemapcube_sampler, vertex_color, 0.0);
}
