// Generated by generate_graphics_shaders.py; edit the .vert/.frag source instead.
#version 330

layout(location = 0) out vec4 fragment_color;
in vec3 vertex_color;

void main()
{
    fragment_color = vec4(vertex_color, 1.0);
}
