#!/usr/bin/env python3
"""Regenerate the checked-in capture shader header (requires glslangValidator)."""
from pathlib import Path
import subprocess
import struct
import tempfile


def main():
    root = Path(__file__).resolve().parent
    sources = {}
    for suffix in ('vp', 'fp', 'vp.msl', 'fp.msl', 'vp.wgsl', 'fp.wgsl', 'hlsl',
                   'cube.fp', 'cube.fp.msl', 'cube.fp.wgsl',
                   'texture.fp', 'texture.fp.msl', 'texture.fp.wgsl'):
        sources[suffix.replace('.', '_')] = (root / ('graphics_capture.' + suffix)).read_bytes() + b'\0'
    with tempfile.TemporaryDirectory() as directory:
        for stage in ('vert', 'frag', 'cube.frag', 'texture.frag'):
            output = Path(directory) / (stage + '.spv')
            subprocess.run(['glslangValidator', '-V', str(root / ('graphics_capture.' + stage)),
                            '-o', str(output)], check=True)
            sources[stage.replace('.', '_') + '_spv'] = output.read_bytes()
    text = '// Generated by package_capture_shaders.py. Edit the shader sources instead.\n'
    for name, source in sources.items():
        if name.endswith('_spv'):
            # Vulkan requires pCode to be aligned to a uint32_t boundary.
            words = struct.unpack('<%dI' % (len(source) // 4), source)
            text += 'static const uint32_t capture_%s[] = {\n' % name
            text += '\n'.join('    ' + ', '.join('0x%08x' % word for word in words[i:i+8]) + ','
                              for i in range(0, len(words), 8))
            text += '\n};\n'
            continue
        text += 'static const unsigned char capture_%s[] = {\n' % name
        text += '\n'.join('    ' + ', '.join('0x%02x' % b for b in source[i:i+16]) + ','
                          for i in range(0, len(source), 16))
        text += '\n};\n'
    (root / 'graphics_capture_shaders.h').write_text(text)


if __name__ == '__main__':
    main()
