#! /usr/bin/env python

from waf_dynamo import platform_supports_feature

def build(bld):
    for name in ['test_graphics', 'test_glsl_uniform_parser']:
        bld.program(features = 'cxx cprogram test',
                    includes = ['../../src', '../../proto'],
                    exported_symbols = ['GraphicsAdapterNull'],
                    source = name + '.cpp',
                    use = 'TESTMAIN DDF DLIB SOCKET PROFILE_NULL PLATFORM_NULL graphics_null graphics_transcoder_null',
                    target = name)

    if platform_supports_feature(bld.env.PLATFORM, 'vulkan', {}) and not bld.env.PLATFORM in ('x86_64-linux','x86_64-ios'):

        extra_libs = []
        if bld.env.PLATFORM in ('armv7-android', 'arm64-android'):
            extra_libs += ['OPENGL']

        bld.program(features = 'cxx cprogram test skip_test',
                    includes = ['../../src', '../../proto'],
                    exported_symbols = ['GraphicsAdapterVulkan', 'GraphicsAdapterOpenGL'],
                    source = 'test_app_graphics.cpp',
                    use = 'TESTMAIN APP DDF DLIB DMGLFW PROFILE PLATFORM VULKAN GRAPHICS graphics_vulkan graphics_transcoder_basisu'.split() + extra_libs,
                    target = 'test_app_graphics')
