#! /usr/bin/env python
import os

def build(bld):
    test_graphics = bld.new_task_gen(features = 'cxx cprogram test sol',
                                 source = 'test_graphics.cpp',
                                 uselib = 'GTEST DLIB SOL_RUNTIME SOL',
                                 uselib_local = "graphics_null",
                                 includes = ['../../src'],
                                 target = 'test_graphics')

    test_graphics.install_path = None

    test_glsl_uniform_parser = bld.new_task_gen(features = 'cxx cprogram test sol',
                                 source = 'test_glsl_uniform_parser.cpp',
                                 uselib = 'GTEST DLIB SOL_RUNTIME SOL',
                                 uselib_local = "graphics_null",
                                 includes = ['../../src'],
                                 target = 'test_glsl_uniform_parser')

    test_glsl_uniform_parser.install_path = None
