#! /usr/bin/env python

import os, sys
import waf_graphics, waf_dynamo

def set_options(opt):
    pass

def configure(cont):
    pass

def build(bld):
    obj = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                           includes = ['.', '../build/default/proto'],
                           proto_gen_py = True,
                           proto_gen_java = True,
                           protoc_includes = '../proto',
                           classpath=bld.env['DYNAMO_HOME'] + '/ext/share/java/protobuf-java-2.3.0.jar' + os.pathsep + bld.env['DYNAMO_HOME'] + '/share/java/ddf.jar',
                           target = 'render',
                           ddf_jar = 'render.jar')

    obj.find_sources_in_dirs('. ../proto/render render', exts = ['.cpp', '.proto'])
    #obj.source.append('../proto/render_ddf.proto')

    classpath = [bld.env['DYNAMO_HOME'] + '/ext/share/java/protobuf-java-2.3.0.jar',
                 bld.env['DYNAMO_HOME'] + '/share/java/ddf.jar',
                 'default/proto/render/generated']

    bld.add_group()
    bld.add_subdirs('test')

    bld.new_task_gen(features='javac seq',
                     classpath=os.pathsep.join(classpath),
                     source_root='java')
    bld.env["JAVACFLAGS"] = '-g'

    bld.new_task_gen(features='jar seq',
                     basedir='java',
                     destfile='fontc.jar')

    bld.install_files('${PREFIX}/include/render', 'render/font_renderer.h')
    bld.install_files('${PREFIX}/include/render', 'render/render.h')

    bld.install_files('${PREFIX}/share/java', 'fontc.jar')
    bld.install_files('${PREFIX}/lib/python', 'waf_render.py')

    bld.install_files('${PREFIX}/share/proto', '../proto/render/material_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../proto/render/render_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../proto/render/font_ddf.proto')

    bld.new_task_gen(source = 'render/render_script.cpp',
                     target = 'render_doc.sdoc',
                     rule = '${SCRIPT_DOC} ${SRC} ${TGT}')

    bld.new_task_gen(source = 'render/render_script.cpp',
                     target = 'render_doc.json',
                     rule = '${SCRIPT_DOC} -t json ${SRC} ${TGT}')

    bld.install_files('${PREFIX}/share/doc', 'render_doc.sdoc render_doc.json')

