function update(self)
    msg.post("target", "request_transform")
    if self.target_pos then
        local pos = go.get_position()
        local dir = vmath.normalize(self.target_pos - pos)
        msg.post("#shot", "play_sound")
        factory.create("#bullet_factory", pos, vmath.quat_from_to(vmath.vector3(1, 0, 0), dir))
    end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("transform_response") then
        assert(sender.path == go.get_id("target"), "invalid id in transform response")
        self.target_pos = message.position
    elseif message_id == hash("target_dead") then
        msg.post("main:/main#script", "done")
    end
end
