-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function update(self)
    if self.target_pos then
        local pos = go.get_position()
        local dir = vmath.normalize(self.target_pos - pos)
        msg.post("#shot", "play_sound")
        factory.create("#bullet_factory", pos, vmath.quat_from_to(vmath.vector3(1, 0, 0), dir))
    end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("trigger_response") then
        assert(sender.path == go.get_id(), "invalid id in trigger response")
        if message.enter then
            self.target_pos = go.get_world_position(message.other_id)
        end
        -- provoke exit too
        msg.post("#co_trigger", "disable")
    elseif message_id == hash("target_dead") then
        msg.post("main:/main#script", "done")
    end
end
