function update(self)
    if self.target_pos then
        local pos = go.get_position()
        local dir = vmath.normalize(self.target_pos - pos)
        msg.post("#shot", "play_sound")
        factory.create("#bullet_factory", pos, vmath.quat_from_to(vmath.vector3(1, 0, 0), dir))
    end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("trigger_response") then
        assert(sender.path == go.get_id(), "invalid id in trigger response")
        if message.enter then
            self.target_pos = go.get_world_position(message.other_id)
        end
        -- provoke exit too
        msg.post("#co_trigger", "disable")
    elseif message_id == hash("target_dead") then
        msg.post("main:/main#script", "done")
    end
end
