-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    -- properties
    self.target_group = hash("target")
    self.speed = 18
    self.impact_damage = 0.2
    self.hit_response = nil
    msg.post("attacker", "dummy_msg")
end

function update(self, dt)
    local rot = go.get_world_rotation()
    if self.hit_response then
        go.delete()
        factory.create("#factory")
        self.hit_response = nil
    else
        local pos = go.get_world_position()
        -- prediction for CD
        local prev_pos = vmath.vector3(pos)
        local velocity = vmath.vector3(self.speed, 0, 0)
        local dp = vmath.rotate(rot, velocity) * dt
        pos = pos + dp
        local next_pos = pos + dp
        go.set_position(pos)
        -- request ray cast
        physics.raycast_async(prev_pos, next_pos, {self.target_group}, 1)
    end
end

function on_message(self, message_id, message)
    if message_id == hash("ray_cast_response") and message.group == self.target_group and message.request_id == 1 then
        self.hit_response = message
    end
end
