-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    local min_r = 5
    local max_r = 10
    local a = 2 * math.pi * math.random()
    local r = min_r + math.random() * (max_r - min_r)
    go.set_position(vmath.vector3(r * math.cos(a), r * math.sin(a), 0))
    self.health = 1
end

function on_message(self, message_id, message, sender)
    if message_id == hash("hit") then
        self.health = self.health - message.damage
        if self.health < 0 then
            msg.post("attacker#script", "target_dead")
            go.delete()
        end
    end
end
