#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    particle = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                                includes = ['.', '../proto'],
                                proto_gen_py = True,
                                protoc_includes = '../proto',
                                target = 'particle',
                                uselib = 'DDF DLIB PLATFORM_SOCKET',
                                source = 'particle.cpp ../proto/particle/particle_ddf.proto')

    # if not the desktop target, there's no need to generate this
    if bld.env.PLATFORM in ['win32', 'x86_64-win32', 'x86_64-linux', 'x86_64-darwin']:
        particle_shared = bld.new_task_gen(features = 'cxx cshlib ddf',
                                           includes = ['.', '../proto'],
                                           target = 'particle_shared',
                                           protoc_includes = '../proto',
                                           uselib = 'DDF DLIB PLATFORM_SOCKET',
                                           source = 'particle.cpp ../proto/particle/particle_ddf.proto')

    bld.install_files('${PREFIX}/include/particle', 'particle.h')
    bld.install_files('${PREFIX}/share/proto', '../proto/particle/particle_ddf.proto')

    bld.add_subdirs('test')
