#! /usr/bin/env python
import os
import Options

def configure(conf):
    pass

def build(bld):
    # if not desktop
    if not bld.env.PLATFORM in ('x86_64-win32', 'x86_64-darwin', 'x86_64-linux'):
        return

    graphics_lib = 'GRAPHICS'
    graphics_adapter = 'GraphicsAdapterOpenGL'
    if Options.options.with_vulkan:
        graphics_lib = 'GRAPHICS_VULKAN'
        graphics_adapter = 'GraphicsAdapterVulkan'

    b = bld.new_task_gen(features = 'cc cxx cprogram',
                        uselib = 'PLATFORM_SOCKET HID INPUT DDF DLIB DMGLFW X CARES ' + graphics_lib,
                        exported_symbols = [graphics_adapter],
                        source = 'main.cpp',
                        target = 'gdc')

    if bld.env.PLATFORM == 'x86_64-darwin':
        b.env.append_value('LINKFLAGS', ['-framework', 'Metal', '-framework', 'Foundation', '-framework', 'IOSurface'])
