local WIDTH = 8
local HEIGHT = 8

local function make_quad(w, h)
    return {
        vertices = {0, 0, 0, h, w, h, w, 0},
        uvs = {0, 0, 0, h, w, h, w, 0},
        indices = {0, 1, 2, 0, 2, 3}
    }
end

local function make_texture_buffer(w, h)
    local tex_buffer = buffer.create(w * h, {{name = hash("rgba"), type = buffer.VALUE_TYPE_UINT8, count = 4}})
    local stream = buffer.get_stream(tex_buffer, hash("rgba"))
    for i = 1, w * h * 4 do
        stream[i] = 0xff
    end
    return tex_buffer
end

function init(self)
    async_texture_auto_size_ready = false

    local tparams = {
        width = WIDTH,
        height = HEIGHT,
        type = graphics.TEXTURE_TYPE_2D,
        format = graphics.TEXTURE_FORMAT_RGBA,
    }

    resource.create_texture_async("/gui/async_texture_auto_size.texturec", tparams, make_texture_buffer(WIDTH, HEIGHT),
        function(self, request_id, result)
            local atlas_id = resource.create_atlas("/gui/async_texture_auto_size.texturesetc", {
                texture = result.path,
                animations = {{
                    id = "frame",
                    width = WIDTH,
                    height = HEIGHT,
                    frames = {1},
                    fps = 60,
                    playback = go.PLAYBACK_ONCE_FORWARD,
                }},
                geometries = {make_quad(WIDTH, HEIGHT)}
            })
            go.set("#gui", "textures", atlas_id, {key = "dynamic_atlas"})
            async_texture_auto_size_ready = true
        end)
end
