-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

tests_done = false

local function assert_layout_object(object, id, src)
    assert(object.type == "link")
    assert(object.id == hash(id))
    assert(object.attributes.src == src)
end

function init(self)
    local node = gui.get_node("text")
    local initial_objects = gui.get_layout_objects(node)
    assert(#initial_objects == 1)
    assert_layout_object(initial_objects[1], "initial", "initial")

    gui.set_text(node, "<link id=updated src=updated>Now</link>")
    local updated_objects = gui.get_layout_objects(node)
    assert(#updated_objects == 1)
    assert_layout_object(updated_objects[1], "updated", "updated")
    assert(updated_objects[1].text_length == 3)

    tests_done = true
end
