-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

tests_done = false

local function callback(self, node)
    tests_done = true
end

function init( self )
    self.node = gui.get_node("box")

    local flipbook = gui.get_flipbook(self.node)
    assert(flipbook == hash("anim"))

    gui.play_flipbook(self.node, "anim_once", callback)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function final()
end
