-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
	local data, error = sys.load_resource("/texture/valid_png.rawc")
	local img = image.load(data, true)
	gui.new_texture("valid", img.width, img.height, img.type, img.buffer, false)
	local node = gui.new_box_node(vmath.vector3(100,100,0), vmath.vector3(img.width,img.height,0))
	gui.set_texture(node, "valid")
end
