-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local ATLAS_A = "/gui/texture_setter_override_a.t.texturesetc"
local ATLAS_B = "/gui/texture_setter_override_b.t.texturesetc"

function init(self)
    self.updated = false
end

function update(self, dt)
    if self.updated then
        return
    end

    local atlas_info = resource.get_atlas(ATLAS_B)
    resource.set_atlas(ATLAS_A, atlas_info)
    self.updated = true
end
