function init(self)

	local tbuffer = buffer.create(32 * 32, { {name=hash("rgba"), type=buffer.VALUE_TYPE_FLOAT32, count=4} } )
    local tstream = buffer.get_stream(tbuffer, hash("rgba"))
    local tparams = {
	       width  = 32,
	       height = 32,
	       type   = graphics.TEXTURE_TYPE_2D,
	       format = graphics.TEXTURE_FORMAT_RGBA,
	   }

	resource.set_texture("/gui/atlas_valid.texturec", tparams, tbuffer)
	resource.set_texture("/gui/texture_valid_png.texturec", tparams, tbuffer)

	-- create a new texture and assign the the atlas
	local tnew = resource.create_texture("/gui/texture_custom.texturec", tparams, tbuffer)
	local atlas_info = resource.get_atlas("/gui/atlas_valid.a.texturesetc")
	atlas_info.texture = tnew
	resource.set_atlas("/gui/atlas_valid.a.texturesetc", atlas_info)
end
