-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

require "gui.gui_module"

function init(self)
    self.x = 1
end

function update(self, dt)
    assert(self.x == 1)
    self.x = self.x + 1
end

local function assert_layout_object_message(message)
    assert(message.type == hash("link"))
    assert(message.id == hash("docs"))
    assert(message.src == "https://www.defold.com", message.src)
end

function on_message(self, message_id, message, sender)
    if message_id == hash("text_object_hovered") then
        assert_layout_object_message(message)
        gui.set_color(gui.get_node("text"), vmath.vector4(0.25, 1.0, 1.0, 1.0))
    elseif message_id == hash("text_object_unhovered") then
        assert_layout_object_message(message)
        gui.set_color(gui.get_node("text"), vmath.vector4(0.5, 1.0, 1.0, 1.0))
    elseif message_id == hash("text_object_clicked") then
        assert_layout_object_message(message)
        gui.set_text(gui.get_node("text"), "clicked")
    end
end
