tests_done = false

local function emitter_state_change(self, id, emitter, state)
    if state == particlefx.EMITTER_STATE_POSTSPAWN then
        tests_done = true
    end
end

function init(self)
    local co = coroutine.create(function()
        particlefx.play("#particlefx", emitter_state_change)
    end)

    local ok, error = coroutine.resume(co)
    assert(ok, tostring(error))
    assert(coroutine.status(co) == "dead")
end
