#! /usr/bin/env python
import os, re
from waf_dynamo import copy_file_task, apidoc_extract_task

def set_options(opt):
    pass

def build(bld):
    obj = bld.new_task_gen(features = 'cxx cstaticlib embed',
                           includes = '. ..',
                           source = 'engine_service.cpp',
                           target = 'engine_service',
                           embed_source = '../content/profiler.html')

    obj = bld.new_task_gen(features = 'cxx cstaticlib',
                           includes = '. ..',
                           source = 'engine_service_null.cpp',
                           target = 'engine_service_null')

    obj = bld.new_task_gen(features = 'cxx cstaticlib ddf embed',
                          includes = '../proto . ..',
                          target = 'engine',
                          proto_gen_py = True,
                          protoc_includes = ['../proto', bld.env['PREFIX'] + '/share'],
                          embed_source='../content/materials/debug.vpc ../content/materials/debug.fpc ../content/builtins/connect/connect.project ../content/builtins.arci ../content/builtins.arcd ../content/builtins.dmanifest',
                          source='engine.cpp engine_main.cpp physics_debug_render.cpp profile_render.cpp ../proto/engine_ddf.proto',
                          uselib_local = 'engine_service')

    obj = bld.new_task_gen(features = 'cxx cstaticlib ddf embed',
                          includes = '../proto . ..',
                          target = 'engine_release',
                          defines = 'DM_RELEASE=1',
                          proto_gen_py = True,
                          protoc_includes = ['../proto', bld.env['PREFIX'] + '/share'],
                          embed_source='../content/materials/debug.vpc ../content/materials/debug.fpc ../content/builtins_release.arci ../content/builtins_release.arcd ../content/builtins_release.dmanifest', # for draw_line/draw_text
                          source='engine.cpp engine_main.cpp ../proto/engine_ddf.proto',
                          uselib_local = 'engine_service_null')

    bld.install_files('${PREFIX}/include/engine', 'engine.h')
    bld.install_files('${PREFIX}/share/proto', '../proto/engine_ddf.proto')

    additional_libs = ['CRASH']
    exported_symbols = ['DefaultSoundDevice', 'NullSoundDevice', 'AudioDecoderWav', 'CrashExt', 'ProfilerExt']

    # Add stb_vorbis and/or tremolo depending on platform
    if 'js-web' in bld.env['PLATFORM'] or 'win32' in bld.env['PLATFORM']:
        exported_symbols.append('AudioDecoderStbVorbis')
    else:
        exported_symbols.append('AudioDecoderStbVorbis')
        exported_symbols.append('AudioDecoderTremolo')
        additional_libs.append('TREMOLO')

    if 'win32' in bld.env['PLATFORM']:
        additional_libs.append('FBGPLATFORM')
        exported_symbols.append('GameroomExt')
        exported_symbols.append('FacebookExt')
        exported_symbols.append('IAPExt')

    mobile_service_symbols = ['IACExt', 'IAPExt', 'PushExt', 'AdTruthExt', 'WebViewExt']
    if  re.match('arm.*?darwin', bld.env['PLATFORM']):
        additional_libs.append('FBSDKCORE')
        additional_libs.append('FBSDKLOGIN')
        additional_libs.append('FBSDKSHARE')
        additional_libs.append('SQLLITE')
        exported_symbols.extend(mobile_service_symbols)
        exported_symbols.append('FacebookExt')

    if 'android' in bld.env['PLATFORM']:
        sound_lib = 'SOUND OPENAL_SOFT OPENSLES'
        exported_symbols.extend(mobile_service_symbols)
        exported_symbols.append('FacebookExt')
    elif 'js-web' in bld.env['PLATFORM']:
        sound_lib = 'SOUND OPENAL'
        exported_symbols.append('FacebookExt')
        exported_symbols.append('IAPExt')
    else:
        sound_lib = 'SOUND OPENAL'

    additional_libs = ' '.join(additional_libs)

    dynamo_home = os.getenv('DYNAMO_HOME')

    activities=[('com.facebook.FacebookActivity', 'android:theme="@android:style/Theme.Translucent.NoTitleBar" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="dmengine"'),
                ('com.defold.iap.IapGooglePlayActivity', 'android:theme="@android:style/Theme.Translucent.NoTitleBar" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="IAP"')]
    extra_packages = 'com.facebook:com.google.android.gms'

    android_jar_paths = ['%s/ext/share/java/facebooksdk.jar' % (dynamo_home),
              '%s/ext/share/java/bolts-android-1.2.0.jar' % (dynamo_home),
              '%s/ext/share/java/google-play-services.jar' % (dynamo_home),
              '%s/ext/share/java/android-support-v4.jar' % (dynamo_home),
              '%s/ext/share/java/android-support-multidex.jar' % (dynamo_home),
              '%s/ext/share/java/in-app-purchasing-2.0.61.jar' % (dynamo_home),
              '%s/share/java/glfw_android.jar' % (dynamo_home),
              '%s/share/java/facebook_android.jar' % (dynamo_home),
              '%s/share/java/gamesys_android.jar' % (dynamo_home),
              '%s/share/java/iap_android.jar' % (dynamo_home),
              '%s/share/java/push_android.jar' % (dynamo_home),
              '%s/share/java/adtruth_android.jar' % (dynamo_home),
              '%s/share/java/sound_android.jar' % (dynamo_home),
              '%s/share/java/webview_android.jar' % (dynamo_home),
              '%s/share/java/iac_android.jar' % (dynamo_home)]

    obj = bld.new_task_gen(
        features = 'cc cxx cprogram apk web',
        uselib = 'WEBVIEWEXT ADTRUTHEXT PROFILEREXT GAMEROOMEXT FACEBOOKEXT IAPEXT PUSHEXT IACEXT RECORD VPX GAMEOBJECT DDF RESOURCE GAMESYS GRAPHICS GRAPHICS_UTIL PHYSICS RENDER PLATFORM_SOCKET SCRIPT LUA EXTENSION HID INPUT PARTICLE RIG DLIB DMGLFW GUI TRACKING CRASH LIVEUPDATE %s X %s' % (sound_lib, additional_libs),
        uselib_local = 'engine engine_service',
        exported_symbols = exported_symbols,
        includes = '../build ../proto . ..',
        #NOTE: _XBOX to get static lib and avoid dllimport/dllexport stuff
        defines = '_XBOX',
        proto_gen_py = True,
        protoc_includes = '../proto',
        target = 'dmengine',
        bundleid = 'com.defold.engine',
        source=['main.cpp'],
        activities = activities,
        extra_packages = extra_packages,
        jars = android_jar_paths)

    if 'win32' in bld.env.BUILD_PLATFORM:
        obj.source.append('engine.rc')

    if 'android' in bld.env['PLATFORM']:
        bld.install_files('${PREFIX}/share/java', 'dmengine.android/classes.dex')
        bld.install_files('${PREFIX}/share/java', 'dmengine.android/r.jar')
        bld.install_files('${PREFIX}/bin/${PLATFORM}', 'dmengine.android/dmengine.apk')

    obj = bld.new_task_gen(
        features = 'cc cxx cprogram apk web',
        uselib = 'WEBVIEWEXT ADTRUTHEXT PROFILEREXT GAMEROOMEXT FACEBOOKEXT IAPEXT PUSHEXT IACEXT RECORD VPX GAMEOBJECT DDF RESOURCE GAMESYS GRAPHICS GRAPHICS_UTIL PHYSICS RENDER PLATFORM_SOCKET SCRIPT LUA EXTENSION HID INPUT PARTICLE RIG DLIB DMGLFW GUI TRACKING CRASH LIVEUPDATE %s X %s' % (sound_lib, additional_libs),
        uselib_local = 'engine_release engine_service_null',
        exported_symbols = exported_symbols,
        includes = '../build ../proto . ..',
        #NOTE: _XBOX to get static lib and avoid dllimport/dllexport stuff
        defines = '_XBOX DM_RELEASE=1',
        proto_gen_py = True,
        protoc_includes = '../proto',
        target = 'dmengine_release',
        source=['main.cpp'],
        activities = activities,
        extra_packages = extra_packages,
        jars = android_jar_paths)

    if 'win32' in bld.env.BUILD_PLATFORM:
        obj.source.append('engine.rc')
        obj.env.append_value('LINKFLAGS', ['/SUBSYSTEM:WINDOWS', '/ENTRY:mainCRTStartup'])

    if 'android' in bld.env['PLATFORM']:
        bld.install_files('${PREFIX}/bin/${PLATFORM}', 'dmengine_release.android/dmengine_release.apk')

    # We need to link with GLFW on Android for the headless version of the engine.
    # Android expects a slighly different life cycle handling, currently handled
    # in the GLFW module.
    additional_libs = ''
    if 'android' in bld.env['PLATFORM']:
      additional_libs = 'DMGLFW'

    obj = bld.new_task_gen(
        features = 'cc cxx cprogram apk web',
        uselib = 'RECORD_NULL GAMEOBJECT PROFILEREXT DDF RESOURCE GAMESYS GRAPHICS_NULL GRAPHICS_UTIL PHYSICS RENDER PLATFORM_SOCKET SCRIPT LUA EXTENSION HID_NULL INPUT PARTICLE RIG GUI TRACKING CRASH DLIB LIVEUPDATE SOUND_NULL CRASH %s' % (additional_libs,),
        exported_symbols = ['ProfilerExt'],
        uselib_local = 'engine engine_service_null',
        includes = '../build ../proto . ..',
        proto_gen_py = True,
        protoc_includes = '../proto',
        target = 'dmengine_headless',
        source=['main.cpp'])

    if 'win32' in bld.env.BUILD_PLATFORM:
        obj.source.append('engine.rc')

    apidoc_extract_task(bld, ['../proto/engine_ddf.proto'])

    if 'win32' in bld.env.PLATFORM:
        src_dir = "%s/ext/lib/%s" % (bld.env.PREFIX, bld.env.PLATFORM)
        install_path = bld.get_install_path("${PREFIX}/bin/${PLATFORM}")
        task = copy_file_task(bld, "%s/OpenAL32.dll" % src_dir)
        task.install_path = install_path
        task = copy_file_task(bld, "%s/wrap_oal.dll" % src_dir)
        task.install_path = install_path

    bld.add_subdirs('test')

def configure(conf):
    pass
