#! /usr/bin/env python

import os
import waflib.Options
from BuildUtility import create_build_utility

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')

def build(bld):
    build_util = create_build_utility(bld.env)

    source_dirs = []

    for platform in [build_util.get_target_os(), 'common']:
        d = platform
        if os.path.exists(os.path.join('src', platform)):
            source_dirs.extend(['%s/*.cpp' % platform])

    b = bld.stlib(features     = 'c cxx',
                  includes     = ['.', '..'],
                  source       = bld.path.ant_glob(source_dirs),
                  target       = 'testmain')

    bld.install_files('${PREFIX}/include/testmain', 'common/testmain.h')

    if not waflib.Options.options.skip_build_tests:
        bld.recurse('test')
