#! /usr/bin/env python

import os
from BuildUtility import create_build_utility

def set_options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    build_util = create_build_utility(bld.env)

    source_dirs = []

    for platform in [build_util.get_target_os(), 'common']:
        d = os.path.join(platform)
        if os.path.exists(os.path.join('src',d)):
            source_dirs.extend([d])

    b = bld.new_task_gen(features   = 'cc cxx cstaticlib',
                      includes  = '. ..',
                      target    = 'testmain')
    b.find_sources_in_dirs(source_dirs)

