#! /usr/bin/env python

VERSION = '0.1'
APPNAME = 'bob'

srcdir = '.'
blddir = 'build'

import os
import Options

def init():
    pass

def set_options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    pass

def shutdown():
    if not Options.commands['build'] or getattr(Options.options, 'skip_tests', False):
        return
    os.system('python src/test/test_bob.py')
