#! /usr/bin/env python

def build(bld):
    libs = 'TESTMAIN PLATFORM_SOCKET GRAPHICS_NULL DDF SCRIPT EXTENSION RESOURCE DLIB PROFILE_NULL LUA CARES render'
    exported_symbols = ['GraphicsAdapterNull']

    bld.program(features = 'cxx cprogram test',
                source = 'test_render.cpp',
                use = libs,
                exported_symbols = exported_symbols,
                web_libs = ['library_sys.js', 'library_script.js'],
                includes = ['../../src', '../../proto'],
                target = 'test_render')

    bld.program(features = 'cxx cprogram test',
                source = 'test_display_profiles.cpp',
                use = libs,
                exported_symbols = exported_symbols,
                web_libs = ['library_sys.js', 'library_script.js'],
                includes = ['../../src', '../../proto'],
                target = 'test_display_profiles')

    bld.program(features = 'cxx cprogram test',
                source = 'test_material.cpp',
                use = libs,
                exported_symbols = exported_symbols,
                web_libs = ['library_sys.js', 'library_script.js'],
                includes = ['../../src', '../../proto'],
                target = 'test_material')

    bld.program(features = 'cxx cprogram test',
                source = 'test_render_script.cpp',
                use = libs,
                exported_symbols = exported_symbols,
                web_libs = ['library_sys.js', 'library_script.js'],
                includes = ['../../src', '../../proto'],
                target = 'test_render_script')

