#! /usr/bin/env python

def build(bld):
    test_render = bld.new_task_gen(features = 'cxx cprogram',
                                    source = 'test_render.cpp',
                                    uselib = 'GTEST GRAPHICS_NULL EXTENSION DDF SCRIPT DLIB LUA',
                                    uselib_local = 'render',
                                    includes = ['../../src', '../../proto'],
                                    target = 'test_render')

    test_render.install_path = None

    test_material = bld.new_task_gen(features = 'cxx cprogram',
                                    source = 'test_material.cpp',
                                    uselib = 'GTEST GRAPHICS_NULL EXTENSION DDF SCRIPT DLIB LUA',
                                    uselib_local = 'render',
                                    includes = ['../../src', '../../proto'],
                                    target = 'test_material')

    test_material.install_path = None

    test_render_script = bld.new_task_gen(features = 'cxx cprogram',
                                    source = 'test_render_script.cpp',
                                    uselib = 'GTEST GRAPHICS_NULL EXTENSION DDF SCRIPT DLIB LUA',
                                    uselib_local = 'render',
                                    includes = ['../../src', '../../proto'],
                                    target = 'test_render_script')

    test_render_script.install_path = None
