#! /usr/bin/env python

VERSION='0.1'
APPNAME='particle'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')
    opt.tool_options('waf_sol')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.check_tool('waf_ddf')
    conf.check_tool('waf_sol')

    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")
    conf.env['LIB_GTEST'] = 'gtest'
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_DDF'] = 'ddf'

    platform = conf.env['PLATFORM']

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="PARTICLE"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="PARTICLE"')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    waf_dynamo.run_gtests(valgrind = True)
