#! /usr/bin/env python

VERSION='0.1'
APPNAME='particle'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('waf_ddf')

    waf_ddf.configure(conf)

    conf.recurse('src')

    conf.env.append_value('INCLUDES', "default/src")
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_DDF'] = 'ddf'

    platform = conf.env['PLATFORM']

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="PARTICLE"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="PARTICLE"')

def build(bld):
    bld.recurse('src')

def shutdown(self):
    waf_dynamo.run_tests(valgrind = True)
