#! /usr/bin/env python

import os, sys
from waf_dynamo import dmsdk_add_files

def set_options(opt):
    pass

def build(bld):
    if bld.env.PLATFORM != 'as3-web':
        obj = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                               includes = ['. opengl'],
                               proto_gen_py = True,
                               protoc_includes = '../proto',
                               target = 'graphics')

        obj.find_sources_in_dirs('. opengl ../proto')
        if 'js-web' in bld.env.PLATFORM:
             obj.source.append('opengl/async/job_queue_sync.cpp');
        else:
             obj.source.append('opengl/async/job_queue_threaded.cpp');

    else:
        obj = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                               includes = ['. flash'],
                               proto_gen_py = True,
                               protoc_includes = '../proto',
                               target = 'graphics')

        obj.find_sources_in_dirs('. flash ../proto')

    obj = bld.new_task_gen(features = 'cxx cstaticlib',
                           includes = ['. null'],
                           proto_gen_py = True,
                           protoc_includes = '../proto',
                           target = 'graphics_null')

    obj.find_sources_in_dirs('. null ../proto')

    bld.add_subdirs('test')

    bld.install_files('${PREFIX}/include/graphics/', 'graphics.h')
    bld.install_files('${PREFIX}/include/graphics/', 'graphics_util.h')
    bld.install_files('${PREFIX}/include/graphics/', 'graphics_native.h')
    bld.install_files('${PREFIX}/include/graphics/opengl/win32', 'opengl/win32/glext.h')
    bld.install_files('${PREFIX}/include/graphics/opengl', 'opengl/graphics_opengl_defines.h')

    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')

    bld.install_files('${PREFIX}/bin', 'texc.py')
    bld.install_files('${PREFIX}/lib/python', 'dds.py')
    bld.install_files('${PREFIX}/lib/python', 'pvrtc.py')
    bld.install_files('${PREFIX}/lib/python', 'waf_graphics.py')

def configure(conf):
    pass
