#! /usr/bin/env python
import os, re
from waf_dynamo import apidoc_extract_task

def configure(conf):
    pass

def build(bld):
    source = ['webview_null.cpp']

    if re.match('arm.*?darwin', bld.env.PLATFORM) or re.match('.*?android', bld.env.PLATFORM):
        source = ['webview_mobile.cpp']

    webview = bld.new_task_gen(features = 'cxx cstaticlib',
                               includes = '.',
                               source = source,
                               target = 'webviewext')

    apidoc_extract_task(bld, ['webview_doc.h'])
