#! /usr/bin/env python

from waf_dynamo import apidoc_extract_task

def configure(conf):
    pass

def build(bld):
    source = ['webview_null.cpp']

    if bld.env.PLATFORM in ('arm64-ios', 'x86_64-ios', 'armv7-android'):
        source = ['webview_mobile.cpp']

    webview = bld.stlib(features = 'cxx',
                        includes = '.',
                        source = source,
                        target = 'webviewext')

    apidoc_extract_task(bld, ['webview_doc.h'])
