function init(self)
    self.cameras = {}
end

function update(self)
    -- cameras are added by the order of camera_1, camera_2 and camera_3,
    -- meaning that camera_3 will be on top of the camera focus stack, then camera_2 and lastly camera_1
    assert(self.cameras[1] == hash("/camera_3"))
    assert(self.cameras[2] == hash("/camera_2"))
    assert(self.cameras[3] == hash("/camera_1"))

    msg.post("@system:", "exit", { code = 0 })
end

function on_message(self, message_id, message, sender)
    if message_id == hash("set_view_projection") then
        table.insert(self.cameras, sender.path)
    end
end
