import Task, TaskGen
from TaskGen import extension, declare_extension

def build(bld):
    libs = 'SCRIPT GTEST PLATFORM_SOCKET THREAD RESOURCE DDF DLIB LUA SCRIPT EXTENSION SOL SOL_RUNTIME'
    test_tracking = bld.new_task_gen(features = 'cxx cprogram test embed',
                                     includes = '..',
                                     uselib = libs,
                                     uselib_local = 'tracking',
				     embed_source = 'test_tracking.lua',
                                     target = 'test_tracking',
                                     source = 'test_tracking.cpp')

    test_tracking.install_path = None

