local M = {}


local function stringify(x)
    if type(x) == "string" then
        return string.format("%q", x)
    elseif type(x) == "function" then
        return "function() end"
    elseif type(x) == "table" then
        local entries = {}
        local n = #x
        for i = 1, n do
            entries[#entries+1] = stringify(x[i])
        end
        for k, v in pairs(x) do
            if type(k) == "number" and k >= 1 and k <= n then
                -- do nothing: we have already written the array part!
            elseif type(k) == "string" and k:match("^[%a_][%w_]*$") ~= nil then
                entries[#entries+1] = tostring(k) .. " = " .. stringify(v)
            else
                entries[#entries+1] = "[" .. stringify(k) .. "]" .. " = " .. stringify(v)
            end 
        end
        return "{" .. table.concat(entries, ", ") .. "}"
    else
        return tostring(x)
    end
end

local function test(...)
    local args = {...}
    local s = "zip.pack("
    for i = 1, #args do
        s = s .. stringify(args[i])
        if i < #args then
            s = s .. ", "
        end
    end
    s = s .. ")"
    local success, error = pcall(zip.pack, ...)
    if success then
        print(("%s => ok"):format(s))
    else
        print(("%s => error: %s"):format(s, error))
    end
end

function M.get_commands()
    return {{
        label = "Test",
        locations = {"Edit"},
        run = function()
            print("A file:")
            test("gitignore.zip", {".gitignore"})
            print("A directory:")
            test("foo.zip", {"foo"})
            print("Multiple:")
            test("multiple.zip", {"foo", {"foo", "bar"}, ".gitignore", {"game.project", "settings.ini"}})
            print("Outside:")
            test("outside.zip", {{os.getenv("PWD") .. "/project.clj", "project.clj"}})
            print("Stored method:")
            test("stored.zip", {method = zip.METHOD.STORED}, {"foo"})
            for i = 0, 9 do
                print("Compression level " .. i .. ":")
                test("level_" .. i .. ".zip", {level = i}, {"foo", {"foo", "bar"}, ".gitignore", "game.project"})
            end
            print("Mixed compression settings:")
            test("mixed.zip", {
                {"foo", "9", level = 9},
                {"foo", "1", level = 1},
                {"foo", "0", level = 0},
                {"foo", "stored", method = zip.METHOD.STORED},
            })
            print("Archive path is a directory:")
            test("foo", {"game.project"})
            print("Source path does not exist:")
            test("error.zip", {"does-not-exist.txt"})
            print("Target path is absolute:")
            test("error.zip", {os.getenv("HOME")})
            print("Target path is a relative path above root:")
            test("error.zip", {{"game.project", "../../game.project"}})
            test("error.zip", {{"game.project", "foo/bar/../../../../game.project"}})
        end
    }}
end

return M
