#! /usr/bin/env python

def build(bld):
    test_testmain = bld.program(features = 'cxx test',
                                includes = '..',
                                use      = ['TESTMAIN', 'APP'],
                                target   = 'test_testmain',
                                source   = 'test_testmain.cpp')
    test_testmain.install_path = None
