-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    msg.post("#", "start_test")

    -- list of expected messages to receive and the next
    -- message to send
    self.expected = {
        -- load and unload cycle (twice)
        { id = hash("start_test"), send = "load", to = "#cp1" },
        { id = hash("proxy_loaded"), send = "unload", to = "#cp1" },
        { id = hash("proxy_unloaded"), send = "load", to = "#cp1" },
        { id = hash("proxy_loaded"), send = "unload", to = "#cp1" },
        { id = hash("proxy_unloaded"), send = "next_test", to = "#" },

        -- load, enable and unload cycle (twice)
        { id = hash("next_test"), send = "load", to = "#cp1" },
        { id = hash("proxy_loaded"), send = "enable", to = "#cp1" },
        { id = hash("im_loaded"), send = "unload", to = "#cp1" },
        { id = hash("im_unloaded") },
        { id = hash("proxy_unloaded"), send = "load", to = "#cp1" },
        { id = hash("proxy_loaded"), send = "enable", to = "#cp1" },
        { id = hash("im_loaded"), send = "unload", to = "#cp1" },
        { id = hash("im_unloaded") },
        { id = hash("proxy_unloaded"), send = "next_test", to = "#" },

        -- async_load, enable and unload cycle (twice)
        { id = hash("next_test"), send = "async_load", to = "#cp1" },
        { id = hash("proxy_loaded"), send = "enable", to = "#cp1" },
        { id = hash("im_loaded"), send = "unload", to = "#cp1" },
        { id = hash("im_unloaded") },
        { id = hash("proxy_unloaded"), send = "async_load", to = "#cp1" },
        { id = hash("proxy_loaded"), send = "enable", to = "#cp1" },
        { id = hash("im_loaded"), send = "unload", to = "#cp1" },
        { id = hash("im_unloaded") },
        { id = hash("proxy_unloaded"), send = "end_test", to = "#" },

        { id = hash("end_test"), send = "done", to = "main:/main#script" },
    }
end

function on_message(self, message_id, message, sender)
    local e = table.remove(self.expected, 1)
    assert(e, "Received " ..  message_id .. " - this is more messages than expected!")
    assert(hash(e.id) == message_id, "Received " .. message_id .. " but expected " .. e.id)
    if e.send then
        print("Received " .. message_id .. " - Sending " .. hash(e.send) .. " to " .. e.to)
        msg.post(e.to, e.send)
    else
        print("Received " .. message_id)
    end
end
