function init(self)
    msg.post("#cp1", "load")
    self.unload_count = 0
end

function on_message(self, message_id, message, sender)
    if message_id == hash("proxy_loaded") then
        msg.post("#cp1", "enable")
    elseif message_id == hash("proxy_unloaded") then
        if self.unload_count < 2 then
            msg.post("#cp1", "load")
	elseif self.unload_count < 4 then
	    msg.post("#cp1", "load_async")
        else
            msg.post("main:/main#script", "done")
        end
    elseif message_id == hash("unload_me") then
        msg.post("#cp1", "unload")
    elseif message_id == hash("im_unloaded") then
        self.unload_count = self.unload_count + 1
    end
end
