function init(self)
    self.sprites = render.predicate({"tile"})
    self.view = vmath.matrix4()
    self.projection = vmath.matrix4_orthographic(0, 640, 0, 360, -1, 1)
end

function update(self)
    render.set_viewport(0, 0, render.get_window_width(), render.get_window_height())
    render.set_view(self.view)
    render.set_projection(self.projection)
    render.set_depth_mask(false)
    render.disable_state(graphics.STATE_DEPTH_TEST)
    render.disable_state(graphics.STATE_STENCIL_TEST)
    render.disable_state(graphics.STATE_CULL_FACE)
    render.enable_state(graphics.STATE_BLEND)
    render.set_blend_func(graphics.BLEND_FACTOR_SRC_ALPHA, graphics.BLEND_FACTOR_ONE_MINUS_SRC_ALPHA)
    render.clear({[graphics.BUFFER_TYPE_COLOR0_BIT] = vmath.vector4(0.02, 0.03, 0.06, 1)})
    render.draw(self.sprites, {frustum = self.projection})
end
