#! /usr/bin/env python
import os, re

def configure(conf):
    pass

def build(bld):
    source = ['window_private.cpp']

    bld.new_task_gen(features = 'cxx cstaticlib',
                           includes = '.',
                           source = source,
                           target = 'windowext')

    bld.new_task_gen(source = 'window_private.h',
                     target = 'window.sdoc',
                     rule = '${SCRIPT_DOC} ${SRC} ${TGT}')

    bld.new_task_gen(source = 'window_private.h',
                     target = 'window.json',
                     rule = '${SCRIPT_DOC} ${SRC} -t json ${TGT}')

    bld.install_files('${PREFIX}/share/doc', 'window.sdoc')
    bld.install_files('${PREFIX}/share/doc', 'window.json')
