-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.


function init(self)
	self.num_updates = 0
	self.num_late_updates = 0
	self.frames = 0
	self.frames_count = 10
end

function update(self, dt)
	self.num_updates = self.num_updates + 1
	self.frames = self.frames + 1
	if self.frames == self.frames_count then
		-- num_late_updates should be frames_count -1 because late_update executes after regular update
		if self.num_updates == self.frames_count and self.num_late_updates == self.frames_count - 1 then
			sys.exit(0)
		else
			sys.exit(1)
		end
	end
end

function late_update(self, dt)
	self.num_late_updates = self.num_late_updates + 1
end
