function init(self)
	self.num_updates = 0
	self.num_late_updates = 0
	self.frames = 0
	self.frames_count = 10
end

function update(self, dt)
	self.num_updates = self.num_updates + 1
	self.frames = self.frames + 1
	if self.frames == self.frames_count then
		-- num_late_updates should be frames_count -1 because late_update executes after regular update
		if self.num_updates == self.frames_count and self.num_late_updates == self.frames_count - 1 then
			sys.exit(0)
		else
			sys.exit(1)
		end
	end
end

function late_update(self, dt)
	self.num_late_updates = self.num_late_updates + 1
end
