#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    script = bld.new_task_gen(features = 'cc cxx cprogram',
                              uselib = 'DLIB',
                              source = ['launcher.cpp'],
                              target = 'launcher')

    if 'win32' in bld.env.BUILD_PLATFORM:
        script.source.append('launcher.rc')
