#! /usr/bin/env python

VERSION='0.1'
APPNAME='rig'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf
import waflib.Options
import TestContext
from build_constants import TargetOS

test_context = None

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('waf_ddf')

    waf_ddf.configure(conf)

    conf.recurse('src')

    target_os = conf.env['TARGET_OS']
    conf.env.append_value('INCLUDES', "default/src")
    conf.env['STLIB_DLIB_NOASAN']          = ['dlib_noasan']
    conf.env['STLIB_DDF_NOASAN']           = ['ddf_noasan']
    conf.env['STLIB_GRAPHICS_NULL']        = ['graphics_null', 'graphics_proto']
    conf.env['STLIB_GRAPHICS_NULL_NOASAN'] = ['graphics_null_noasan', 'graphics_proto_noasan'] # For the shared library used in editor
    conf.env['STLIB_PLATFORM_NULL']        = ['platform_null']

    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="RIG"')

    if target_os != TargetOS.WINDOWS:
        conf.env.append_value('CFLAGS', ["-fdebug-compilation-dir=engine/rig"])
        conf.env.append_value('CXXFLAGS', ["-fdebug-compilation-dir=engine/rig"])

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)
