#! /usr/bin/env python
import os, re

def configure(conf):
    pass

def build(bld):
    embed_source = ''

    source = []

    if re.match('arm.*?darwin', bld.env.PLATFORM):
        source += ['dummy.mm']
    if re.match('arm.*?tvos', bld.env.PLATFORM):
        source += ['dummy.mm']
    dummy = bld.new_task_gen(features = 'cxx cstaticlib',
                            includes = '.',
                            source = source,
                            target = 'dummy')

