-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local test_counter = require("script_props.test_counter")

go.property("big_font", resource.font())
go.property("atlas2", resource.atlas())

local function assert_exit(assert_that, error_string)
    if not assert_that then
        if error_string then
            print(error_string)
        end
        msg.post("@system:", "exit", { code = 1 })
        assert(assert_that)
    end
end

local function assert_error(func)
    local r, err = pcall(func)
    assert_exit(not r, err)
end

local function assert_not_error(func)
    local r, err = pcall(func)
    assert_exit(r, err)
end

function init(self)
    msg.post("#", "late_init")
end

function late_init(self)
    test_counter.start()
    ---- Fonts

    -- Test set fonts works
    assert_not_error(function()
            go.set("#gui", "fonts", self.big_font, {key = "system_font_BIG"})
        end)

    -- Test replace fonts works
    assert_not_error(function()
            go.set("#gui", "fonts", self.big_font, {key = "default_font"})
        end)

    -- Test set fonts with index failed
    assert_error(function()
            go.set("#gui", "fonts", self.big_font, {index = 992})
        end)

    -- Test set fonts with both index and key failed
    assert_error(function()
            go.set("#gui", "fonts", self.big_font, {key = "default_font", index = 992})
        end)

    -- Test get fonts works
    local font
    assert_not_error(function()
            font = go.get("#gui", "fonts", {key = "system_font_BIG"})
        end)
    assert_exit(font == self.big_font, "Wrong font got from gui component")

    -- Test get font without key
    assert_error(function()
        go.get("#gui", "fonts", {})
    end)
    assert_error(function()
        go.get("#gui", "fonts")
    end)

    ---- Textures

        -- Test set atlas works
    assert_not_error(function()
            go.set("#gui", "textures", self.atlas2, {key = "atlas2"})
        end)

    -- Test replace atlas works
    assert_not_error(function()
            go.set("#gui", "textures", self.atlas2, {key = "atlas1"})
        end)

    -- Test set atlas with index failed
    assert_error(function()
            go.set("#gui", "textures", self.atlas2, {index = 992})
        end)

    -- Test set atlas with both index and key failed
    assert_error(function()
            go.set("#gui", "textures", self.atlas2, {key = "atlas2", index = 992})
        end)

    -- Test get atlas works
    local atlas
    assert_not_error(function()
            atlas = go.get("#gui", "textures", {key = "atlas1"})
        end)
    assert_exit(atlas == self.atlas2, "Wrong atlas got from gui component")

    -- Test get atlas without key
    assert_error(function()
        go.get("#gui", "textures", {})
    end)
    assert_error(function()
        go.get("#gui", "textures")
    end)

    -- Validate resources were changed in gui
    msg.post("#gui", "test")
end

function on_message(self, message_id, message, sender)
    if hash("late_init") == message_id then
        late_init(self)
    elseif hash("test_done") == message_id then
        test_counter.done()
    end
end