function on_input(self, action_id, action)
	if action_id == hash("gamepad_connected") then
		assert(action.gamepad_name == "null_device")
		assert(action.gamepad_guid == "00000000000000000000000000000000")
		assert(action.gamepad_guid_info.bus == 0)
		assert(action.gamepad_guid_info.crc == 0)
		assert(action.gamepad_guid_info.vendor == 0)
		assert(action.gamepad_guid_info.product == 0)
		assert(action.gamepad_guid_info.version == 0)
		assert(action.touch == nil)
		assert(action.text == nil)
	elseif action_id == hash("gamepad_connected_0") then
		assert(action.gamepad_name == "")
		assert(action.gamepad_guid == "00000000000000000000000000000000")
		assert(action.gamepad_guid_info.bus == 0)
		assert(action.gamepad_guid_info.crc == 0)
		assert(action.gamepad_guid_info.vendor == 0)
		assert(action.gamepad_guid_info.product == 0)
		assert(action.gamepad_guid_info.version == 0)
		assert(action.touch == nil)
		assert(action.text == nil)
	else
		assert(action.gamepad_name == nil)
		assert(action.gamepad_guid == nil)
		assert(action.gamepad_guid_info == nil)
	end
end
