-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    self.render = msg.url("@render:")
    self.gui = msg.url("#gui")
    msg.post(self.render, "test_message", {data = 1})
end

function update(self)
    msg.post("@system:", "exit", { code = 1 })
end

function on_message(self, message_id, message, sender)
    if sender == self.render then
        msg.post(self.gui, message_id, message)
    elseif sender == self.gui and message_id == hash("test_message") and message.data == 1 then
        msg.post("@system:", "exit", { code = 0 })
    end
end
