#! /usr/bin/env python

VERSION='0.1'
APPNAME='sound'

srcdir = '.'
blddir = 'build'

import os, sys
import waf_dynamo, waf_ddf

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')

    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")
    conf.env['LIB_GTEST'] = 'gtest'
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_LUA'] = 'lua'
    conf.env['STATICLIB_DMGLFW'] = 'dmglfw'
    conf.env['STATICLIB_SCRIPT'] = 'script'

    platform = conf.env['PLATFORM']

    if platform == "darwin":
        conf.env.append_value('LINKFLAGS', ['-framework', 'Carbon', '-framework', 'OpenAL', '-framework', 'IOKit'])
    elif platform == "armv7-darwin":
        conf.env.append_value('LINKFLAGS', ['-framework', 'OpenAL', '-framework', 'IOKit'])
    elif platform == "linux":
        conf.env['LIB_OPENAL'] = 'openal'
        conf.env.append_value('LINKFLAGS', ['-lXext', '-lX11', '-lXi', '-lGL', '-lGLU', '-lpthread'])
    elif platform == "win32":
        conf.env['LIB_OPENAL'] = 'OpenAL32'
        conf.env.append_value('LINKFLAGS', ['user32.lib'])

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="SOUND"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="SOUND"')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    run = False
    # Try to determine if sound device exists
    if sys.platform == 'linux2' and os.path.exists('/dev/snd/controlC0'):
        run = True
    elif sys.platform == 'darwin':
        run = True
    if run:
        waf_dynamo.run_gtests(valgrind = True)
