#! /usr/bin/env python

VERSION='0.1'
APPNAME='sound'

srcdir = '.'
blddir = 'build'

import os, sys, re
import waf_dynamo, waf_ddf

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.check_tool('java')

    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")
    conf.env['STATICLIB_SCRIPT'] = 'script'
    conf.env['STATICLIB_TREMOLO'] = 'tremolo'

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="SOUND"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="SOUND"')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
