#! /usr/bin/env python

VERSION='0.1'
APPNAME='tracking'

srcdir = '.'
blddir = 'build'

import sys, re, os
import waf_dynamo, waf_ddf

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')
    opt.tool_options('waf_ddf')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.check_tool('waf_ddf')
    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")

    conf.env['LIB_GTEST'] = 'gtest'
    conf.env['STATICLIB_DLIB'] = ['dlib', 'axtls']
    conf.env['STATICLIB_DDF'] = 'ddf'
    conf.env['STATICLIB_RESOURCE'] = 'resource'
    conf.env['STATICLIB_EXTENSION'] = 'extension'
    conf.env['STATICLIB_SCRIPT'] = 'script'

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="TRACKING"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="TRACKING"')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    waf_dynamo.run_gtests(valgrind = True)
