-- Copyright 2020-2022 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
-- 
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
-- 
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.


function init(self)
    self.unload = false
    --- step 2 ---
    assert(collectionfactory.get_status("/go#collectionfactory") == collectionfactory.STATUS_LOADED)
    collectionfactory.load("/go#collectionfactory", load_complete)
end

function load_complete(self, url, result)
    assert(result == true)
    collectionfactory.create(url)
    collectionfactory.create(url)
    -- DEF-3338 Collection factory create() function should accept nil value in place of table
    collectionfactory.create(url, nil, nil, nil, 1)
    self.unload = true
end

function update(self, dt)
    --- step 2 ---
    if self.unload == true then
        collectionfactory.unload("/go#collectionfactory")
        self.unload = false
    end
end

function final(self)
    go.delete("/collection0/go", true)
    go.delete("/collection0/go2", true)
    go.delete("/collection1/go", true)
    go.delete("/collection1/go2", true)
    go.delete("/collection2/go", true)
    go.delete("/collection2/go2", true)
end
