#! /usr/bin/env python

def build(bld):
    bld.new_task_gen(features = 'cxx cprogram test',
                    includes = '../../../src . ../../proto',
                    uselib = 'TESTMAIN DLIB PLATFORM_SOCKET LUA SCRIPT',
                    uselib_local = 'rig',
                    target = 'test_rig',
                    source = 'test_rig.cpp')
