import Task, TaskGen
from TaskGen import extension, declare_extension

def build(bld):
    test_rig = bld.new_task_gen(features = 'cxx cprogram test',
                                includes = '../../../src . ../../proto',
                                uselib = 'GTEST DLIB PLATFORM_SOCKET LUA SCRIPT',
                                uselib_local = 'rig',
                                target = 'test_rig',
                                source = 'test_rig.cpp')

    test_rig.install_path = None
