#! /usr/bin/env python

import os, sys

def build(bld):
    proto_include_path = bld.env['DYNAMO_HOME'] + '/ext/include'

    copy = 'cp'
    if sys.platform == 'win32':
        copy = 'copy'

    copy_rule = '%s %s/%s ${TGT}' % (copy, proto_include_path, 'google/protobuf/compiler/plugin.proto')
    # Copy on windows doesn't like /...
    copy_rule = copy_rule.replace('/', os.sep)
    bld.new_task_gen(rule= copy_rule,
                     target='plugin.proto',
                     name='copy_plugin.proto',
                     shell=True)

    bld.new_task_gen(
         rule   = 'protoc --python_out=. -I . -I %s ${SRC}' % (proto_include_path),
         source ='plugin.proto',
         after = 'copy_plugin.proto',
         shell = True)

    ddf_ext = bld.new_task_gen(
         rule   = 'protoc --python_out=${TGT[0].parent.dir(env)} --cpp_out=${TGT[0].parent.dir(env)} -I ${SRC[0].parent.src_dir(env)} -I %s ${SRC}' % (proto_include_path),
         source = 'ddf_extensions.proto',
         target = 'ddf_extensions_pb2.py',
         shell = True)

    ddf_ext = bld.new_task_gen(
         rule   = 'echo "" > ${TGT}',
         source = 'ddf_extensions.proto',
         target = '__init__.py',
         shell = True)

    bld.install_files('${PREFIX}/lib/python/ddf',
                      ddf_ext.path.find_or_declare('ddf_extensions_pb2.py').abspath(ddf_ext.env),
                      ddf_ext.env)

    bld.install_files('${PREFIX}/lib/python',
                      ddf_ext.path.find_or_declare('plugin_pb2.py').abspath(ddf_ext.env),
                      ddf_ext.env)

    bld.add_group()

    bld.new_task_gen(
            features = 'cxx cstaticlib ddf sol',
            includes = '../.. ..',
            source = 'ddf_extensions.proto ddf_math.proto ddf.cpp ddf_load.cpp ddf_save.cpp ddf_inputbuffer.cpp ddf_util.cpp ddf_message.cpp ddf_loadcontext.cpp ddf_outputstream.cpp ddf_rebase.cpp ddf_sol.cpp ddf.sol',
            proto_gen_cc = True,
            proto_compile_cc = True,
            proto_gen_py = True,
            sol_includes = '.',
            protoc_includes = '..',
            target = 'ddf')

    bld.install_files('${PREFIX}/include/ddf', 'ddf.h')
    bld.install_files('${PREFIX}/lib/sol', 'ddf.sol')
    bld.install_files('${PREFIX}/lib/sol', 'ddf_math.sol')
    bld.install_files('${PREFIX}/lib/sol', 'ddf_extensions.sol')

def configure(conf):
    pass

