#! /usr/bin/env python

from waflib.Options import options

def build(bld):
   bld(features     = 'c cxx cprogram test',
       source       = 'test_texc.cpp',
       use          = 'DLIB BASIS_ENCODER PROFILE_NULL texc',
       proto_gen_py = True,
       target       = 'test_texc')

   bld(features     = 'c cxx cprogram test',
       source       = 'test_atlasc.cpp',
       use          = 'DLIB BASIS_ENCODER PROFILE_NULL atlasc atlaspacker',
       target       = 'test_atlasc')
