#! /usr/bin/env python

VERSION='0.1'
APPNAME='iac'

srcdir = '.'
blddir = 'build'

import waf_dynamo

def options(opt):
    opt.tool_options('waf_dynamo')

def init(ctx):
    pass

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.recurse('src')

def build(bld):
    bld.recurse('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
