#!/usr/bin/env python

def init(ctx):
    pass

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    liveupdate = bld.__call__(features = 'cxx cstaticlib',
                                  includes = '.',
                                  target = 'liveupdate')

    liveupdate.find_sources_in_dirs('.')
    liveupdate.source = [x for x in liveupdate.source if not 'null' in x]

    liveupdate_null = bld.__call__(features = 'cxx cstaticlib',
                                  includes = '.',
                                  source = 'liveupdate_null.cpp',
                                  target = 'liveupdate_null')

    bld.recurse('test')

    bld.install_files('${PREFIX}/include/liveupdate', 'liveupdate.h')

def shutdown(self):
    pass
