#! /usr/bin/env python
import os
from TaskGen import feature, before

VERSION='0.1'
APPNAME='sdk'

srcdir = '.'
blddir = 'build'

import waf_dynamo

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_EXTENSION'] = 'extension'
    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="SDK"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="SDK"')


def build(bld):
    bld.add_subdirs('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
