#! /usr/bin/env python
import os
from waflib.TaskGen import feature, before

VERSION='0.1'
APPNAME='sdk'

srcdir = '.'
blddir = 'build'

import waf_dynamo
import waflib.Options
import TestContext

test_context = None

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.env['STLIB_DLIB'] = 'dlib'
    conf.env['STLIB_EXTENSION'] = 'extension'
    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="SDK"')

    conf.env.append_value('CFLAGS', ["-fdebug-compilation-dir=engine/sdk", "-fdebug-prefix-map=../src=src", "-fdebug-prefix-map=../../../tmp/dynamo_home=../../defoldsdk"])
    conf.env.append_value('CXXFLAGS', ["-fdebug-compilation-dir=engine/sdk", "-fdebug-prefix-map=../src=src", "-fdebug-prefix-map=../../../tmp/dynamo_home=../../defoldsdk"])

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)
