-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
	local ok, err = pcall(function()
		local node1 = gui.new_box_node(vmath.vector3(0), vmath.vector3(0))
		gui.set_texture(node1, "texture1")
		gui.play_flipbook(node1, hash("image"))

		local node2 = gui.new_box_node(vmath.vector3(0), vmath.vector3(0))
		gui.set_texture(node2, "texture1")
	end)
	if not ok then
		print(err)
		msg.post("@system:", "exit", { code = 1 })
	else
		msg.post("@system:", "exit", { code = 0 })
	end
end
