#! /usr/bin/env python

import waf_dynamo

VERSION = '0.1'
APPNAME = 'testmain'

srcdir = '.'
blddir = 'build'

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')
    opt.sub_options('src')

def configure(conf):
    conf.load('waf_dynamo')
    conf.recurse('src')

def build(bld):
    bld.recurse('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
