tests_done = false

local texture_params = {
    width = 4,
    height = 4,
    type = graphics.TEXTURE_TYPE_2D,
    format = graphics.TEXTURE_FORMAT_RGBA,
}

function init(self)
    local co = coroutine.create(function()
        local texture_path = "/create_texture_async_from_coroutine.texturec"
        local expected_path = hash(texture_path)
        local texture_buffer = buffer.create(texture_params.width * texture_params.height, {
            { name = hash("rgba"), type = buffer.VALUE_TYPE_UINT8, count = 4 }
        })

        resource.create_texture_async(texture_path, texture_params, texture_buffer, function(self, request_id, result)
            assert(request_id ~= nil)
            assert(result.path == expected_path)

            local texture_info = resource.get_texture_info(result.path)
            assert(texture_info.width == texture_params.width)
            assert(texture_info.height == texture_params.height)
            tests_done = true
        end)
    end)

    local ok, error = coroutine.resume(co)
    assert(ok, tostring(error))
    assert(coroutine.status(co) == "dead")

    co = nil
    collectgarbage("collect")
end
