-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local function assert_attachment(attachment, t_info)
	assert(t_info.width == attachment.width)
	assert(t_info.height == attachment.height)
end

local function test_get_info(self)
	local info = resource.get_render_target_info("/render_target/valid.render_targetc")
	assert(info.handle ~= nil)
	assert(#info.attachments == 3)
	assert(info.attachments[1].width == 128)
	assert(info.attachments[1].height == 128)
	assert(info.attachments[1].buffer_type == resource.BUFFER_TYPE_COLOR0_BIT)
	assert(info.attachments[2].width == 128)
	assert(info.attachments[2].height == 128)
	assert(info.attachments[2].buffer_type == resource.BUFFER_TYPE_COLOR1_BIT)
	assert(info.attachments[3].width == 128)
	assert(info.attachments[3].height == 128)
	assert(info.attachments[3].buffer_type == resource.BUFFER_TYPE_DEPTH_BIT)

	assert_attachment(info.attachments[1], resource.get_texture_info(info.attachments[1].handle))
	assert_attachment(info.attachments[2], resource.get_texture_info(info.attachments[2].handle))
	assert_attachment(info.attachments[3], resource.get_texture_info(info.attachments[3].handle))
end

local function test_attachment_get_info(self)
	local info = resource.get_render_target_info("/render_target/valid.render_targetc")

	assert(info.attachments[1].texture ~= nil)
	assert(info.attachments[2].texture ~= nil)
	assert(info.attachments[3].texture ~= nil)

    assert_attachment(info.attachments[1], resource.get_texture_info(info.attachments[1].texture))
    assert_attachment(info.attachments[2], resource.get_texture_info(info.attachments[2].texture))
    assert_attachment(info.attachments[3], resource.get_texture_info(info.attachments[3].texture))

    local info_from_handle = resource.get_render_target_info(info.handle)
    assert(info_from_handle.attachments[1].texture == nil)
    assert(info_from_handle.attachments[2].texture == nil)
    assert(info_from_handle.attachments[3].texture == nil)
end

function init(self)
    test_get_info(self)
    test_attachment_get_info(self)
end
