local function assert_attachment(attachment, t_info)
	assert(t_info.width == attachment.width)
	assert(t_info.height == attachment.height)
end

local function test_get_info(self)
	local info = resource.get_render_target_info("/resource/render_target_valid.render_targetc")
	assert(info.handle ~= nil)
	assert(info.sample_count == 4)
	assert(#info.attachments == 3)
	assert(info.attachments[1].width == 128)
	assert(info.attachments[1].height == 128)
	assert(info.attachments[1].buffer_type == graphics.BUFFER_TYPE_COLOR0_BIT)
	assert(info.attachments[2].width == 128)
	assert(info.attachments[2].height == 128)
	assert(info.attachments[2].buffer_type == graphics.BUFFER_TYPE_COLOR1_BIT)
	assert(info.attachments[3].width == 128)
	assert(info.attachments[3].height == 128)
	assert(info.attachments[3].buffer_type == graphics.BUFFER_TYPE_DEPTH_BIT)

	assert_attachment(info.attachments[1], resource.get_texture_info(info.attachments[1].handle))
	assert_attachment(info.attachments[2], resource.get_texture_info(info.attachments[2].handle))
	assert_attachment(info.attachments[3], resource.get_texture_info(info.attachments[3].handle))
end

local function test_get_cubemap_info(self)
	local info = resource.get_render_target_info("/resource/render_target_cubemap.render_targetc")
	assert(#info.attachments == 1)
	assert(info.attachments[1].width == 16)
	assert(info.attachments[1].height == 16)
	assert(info.attachments[1].type == graphics.TEXTURE_TYPE_CUBE_MAP)
	local texture_info = resource.get_texture_info(info.attachments[1].handle)
	assert(texture_info.type == graphics.TEXTURE_TYPE_CUBE_MAP)
	assert(texture_info.page_count == 6)
end

local function test_attachment_get_info(self)
	local info = resource.get_render_target_info("/resource/render_target_valid.render_targetc")

	assert(info.attachments[1].texture ~= nil)
	assert(info.attachments[2].texture ~= nil)
	assert(info.attachments[3].texture ~= nil)

    assert_attachment(info.attachments[1], resource.get_texture_info(info.attachments[1].texture))
    assert_attachment(info.attachments[2], resource.get_texture_info(info.attachments[2].texture))
    assert_attachment(info.attachments[3], resource.get_texture_info(info.attachments[3].texture))

    local info_from_handle = resource.get_render_target_info(info.handle)
    assert(info_from_handle.attachments[1].texture == nil)
    assert(info_from_handle.attachments[2].texture == nil)
    assert(info_from_handle.attachments[3].texture == nil)
    assert(info_from_handle.sample_count == info.sample_count)
end

function init(self)
    test_get_info(self)
    test_get_cubemap_info(self)
    test_attachment_get_info(self)
end
