#!/usr/bin/env python

VERSION = '1.0'
APPNAME = 'liveupdate'

import os
import waf_dynamo, waf_ddf
import waflib.Options
import TestContext

test_context = None

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('java')

    waf_ddf.configure(conf)
    conf.recurse('src')

    conf.env['STLIB_DDF']      = 'ddf'
    conf.env['STLIB_RESOURCE'] = 'resource'
    conf.env['STLIB_DLIB']     = ['dlib', 'mbedtls', 'zip']

    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="LIVEUPDATE"')

    conf.env.append_value('CFLAGS', ["-fdebug-compilation-dir=engine/liveupdate", "-fdebug-prefix-map=../src=src", "-fdebug-prefix-map=../../../tmp/dynamo_home=../../defoldsdk"])
    conf.env.append_value('CXXFLAGS', ["-fdebug-compilation-dir=engine/liveupdate", "-fdebug-prefix-map=../src=src", "-fdebug-prefix-map=../../../tmp/dynamo_home=../../defoldsdk"])

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)
