#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    buffer = bld.new_task_gen(features = 'cxx cstaticlib',
                              includes = ['.'],
                              target = 'buffer',
                              uselib = 'DLIB',
                              source = 'buffer.cpp')

    bld.install_files('${PREFIX}/include/buffer', 'buffer.h')

    bld.add_subdirs('test')
