-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)

	local tbuffer = buffer.create(32 * 32, { {name=hash("rgba"), type=buffer.VALUE_TYPE_FLOAT32, count=4} } )
    local tstream = buffer.get_stream(tbuffer, hash("rgba"))
    local tparams = {
	       width  = 32,
	       height = 32,
	       type   = graphics.TEXTURE_TYPE_2D,
	       format = graphics.TEXTURE_FORMAT_RGBA,
	   }

	resource.set_texture("/atlas/valid.texturec", tparams, tbuffer)
	resource.set_texture("/texture/valid_png.texturec", tparams, tbuffer)

	-- create a new texture and assign the the atlas
	local tnew = resource.create_texture("/texture/custom.texturec", tparams, tbuffer)
	local atlas_info = resource.get_atlas("/atlas/valid.t.texturesetc")
	atlas_info.texture = tnew
	resource.set_atlas("/atlas/valid.t.texturesetc", atlas_info)
end
