function init(self)
	msg.post("#collectionproxy", "load")
	self.count = 0
end

function final(self)
end

function update(self, dt)
	self.count = self.count + 1

	--if self.count == 23 then
	--	msg.post("#collectionproxy", "unload")
	--end
end

function on_message(self, message_id, message, sender)
	print(message_id)
	if message_id == hash("proxy_loaded") then
		msg.post("#collectionproxy", "init")
		msg.post("#collectionproxy", "enable")
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
