def configure(conf):
    pass

def build(bld):
    bullet_collision = bld.new_task_gen(features = 'cxx cstaticlib',
                                        includes = '. ..',
                                        target = 'BulletCollision',
                                        uselib = 'BULLET')

    bullet_collision.find_sources_in_dirs(['BroadphaseCollision',
                                           'CollisionShapes',
                                           'CollisionDispatch',
                                           'Gimpact',
                                           'NarrowPhaseCollision'])
