-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local fire_rate = 10

function init(self)
	self.timer = 0
end

function update(self, dt)
	if self.target then
		self.timer = self.timer - dt
		if self.timer <= 0 then
			self.timer = 1/fire_rate
			local dir = self.target - go.get_world_position()
			local angle = math.atan2(dir.y, dir.x)
			factory.create("#factory", go.get_world_position(), vmath.quat_rotation_z(angle))
			--msg.post("#sound", "play_sound", {gain = 0.2})
		end
	else
		self.timer = 0
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_target") then
		self.target = message.target
	end
end
