#! /usr/bin/env python

def build(bld):

    if bld.env.PLATFORM in ('win32', 'x86_64-win32', 'x86_64-linux', 'x86_64-darwin'):
        vpx = 'VPX'
        record = 'record'
    else:
        vpx = ''
        record = 'record_null'

    extra_defines = []
    if bld.env.PLATFORM in ('armv7-darwin', 'arm64-darwin', 'x86_64-ios'):
        extra_defines = ['DM_NO_SYSTEM_FUNCTION'] # Needed because we wish to build the tests for all platforms, but not all platforms have the system() function

    test_record = bld.new_task_gen(features='cxx cprogram test',
                                   includes='../../../src .',
                                   defines=extra_defines,
                                   uselib='APP DLIB %s' % vpx,
                                   uselib_local=record,
                                   proto_gen_py=True,
                                   target='test_record',
                                   source='test_record.cpp')
    test_record.install_path = None
