go.property("test_value_1", vmath.vector3())
go.property("test_value_2", 0)

local epsilon = 0.000001

local function callback(self, url, property_id)
    go.cancel_animations(url)
end

function init(self)
    go.cancel_animations("#", nil)
    go.animate("#", "test_value_1.x", go.PLAYBACK_ONCE_FORWARD, 2, go.EASING_LINEAR, 2)
    go.animate("#", "test_value_1.y", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_LINEAR, 1, 0, callback)
    go.animate("#", "test_value_2", go.PLAYBACK_ONCE_FORWARD, 8, go.EASING_LINEAR, 2)
    self.timer = 0
    self.frame = 0
    self.counter = 0
end

function update(self, dt)
    assert(math.abs(self.timer - self.test_value_1.x) < epsilon)
    assert(math.abs(self.timer - self.test_value_1.y) < epsilon)
    assert(math.abs(self.test_value_2 - self.counter) < epsilon)
    if self.frame < 4 then
        self.timer = self.timer + dt
        self.counter = self.counter + 1
    end
    self.frame = self.frame + 1
end