-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

go.property("test_value", 0)

local epsilon = 0.000001

local function callback(self, url, property_id)
    go.animate(url, "test_value", go.PLAYBACK_ONCE_FORWARD, 0.5, go.EASING_LINEAR, 0.5, 1, function ()
        self.test_value = 0
    end)
end

function init(self)
    go.animate(nil, "test_value", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_LINEAR, 1, 0, callback)
    self.timer = 0
    self.frame = 0
end

function update(self, dt)
    if self.frame < 4 then
        assert(math.abs(self.timer - self.test_value) < epsilon)
    elseif self.frame < 8 then
        assert(1 == self.test_value)
    elseif self.frame < 10 then
        local t = self.timer - 2
        local e = 1 - t
        assert(math.abs(e - self.test_value) < epsilon)
    else
        assert(self.test_value == 0)
    end
    self.timer = self.timer + dt
    self.frame = self.frame + 1
end