-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local count = 257

function init(self)
    self.objects = {}

    for i = 1, count do
        table.insert(self.objects, hash("box" .. i))
    end    
    self.p = true
end

local function animate_color(self)
    local c = vmath.vector4(1, 0, 0, 1)
    for i = 1, count do
        local delay = i / count
        local o = self.objects[i]
        local url = msg.url()
        url.path = o
        url.fragment = hash("script")
        go.animate(url, "tint.x", go.PLAYBACK_ONCE_FORWARD, c.x, go.EASING_LINEAR, 1.6, delay)
    end
end

local function done(self)
    animate_color(self)
end

function update(self, dt)
    if self.p then
        for i = 1, count do
            local pos = vmath.vector3(i * 10 + 300 , -i * 10 + 700 , 0)    
            local cb = nil
            if #self.objects == i then
                cb = done
            end
            go.animate(self.objects[i], "position.x", go.PLAYBACK_ONCE_FORWARD, pos.x, go.EASING_INOUTELASTIC, 1.6, 0, cb)
        end
    end
    self.p = nil
end