#! /usr/bin/env python

from waflib.Options import options

def configure(conf):
    conf.env['STLIB_HARFBUZZ'] = ['harfbuzz', 'sheenbidi']
    conf.env['STLIB_SKRIBIDI'] = ['skribidi', 'unibreak']

def build(bld):
    if options.skip_build_tests:
       return

    bld.add_group()
    sources = bld.path.ant_glob(['*.cpp'], excl=['test_font_gen.cpp', 'test_font_gen_null.cpp', 'test_font_vector.cpp'])

    bld(features = 'cxx cprogram test',
        source   = sources,
        use      = 'TESTMAIN DLIB PROFILE_NULL font',
        includes = '. .. ../font',
        target = 'test_font')

    bld(features = 'cxx cprogram test',
        source   = sources,
        use      = 'TESTMAIN DLIB PROFILE_NULL HARFBUZZ SKRIBIDI font_skribidi',
        defines  = ['FONT_USE_HARFBUZZ', 'FONT_USE_SKRIBIDI'],
        includes = '. .. ../font',
        target = 'test_font_skribidi')

    for name, library in [('test_font_gen', 'font_gen'), ('test_font_gen_null', 'font_gen_null'), ('test_font_vector', 'font')]:
        bld(features = 'cxx cprogram test',
            source = name + '.cpp',
            use = 'TESTMAIN DLIB PROFILE_NULL ' + library + (' font' if library != 'font' else ''),
            includes = '. .. ../font',
            target = name)

    bld(features = 'cxx cprogram test',
        source = 'test_font_vector.cpp',
        use = 'TESTMAIN DLIB PROFILE_NULL HARFBUZZ SKRIBIDI font_skribidi',
        includes = '. .. ../font',
        target = 'test_font_vector_skribidi')
