#! /usr/bin/env python
import os
from waf_dynamo import dmsdk_add_files
from BuildUtility import create_build_utility

def options(opt):
    pass

def build(bld):
    # build_util = create_build_utility(bld.env)

    bld.stlib(features = 'cxx',
                includes = ['.'],
                target   = 'fontgen',
                defines  = [],
                source   = bld.path.ant_glob(['*.cpp']))

    #bld.add_group()
    #bld.recurse('test')

def configure(conf):
    pass

