#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    script = bld.stlib(features = 'cxx ddf',
                       includes = '../proto .',
                       target = 'input',
                       source = bld.path.ant_glob('*.cpp') + bld.path.parent.ant_glob('proto/input/*'),
                       proto_gen_py = True,
                       protoc_includes = '../proto')

    bld.install_files('${PREFIX}/include/input', 'input.h')
    bld.install_files('${PREFIX}/share/proto', '../proto/input/input_ddf.proto')

    bld.recurse('test')
