function init(self)
    self.collection_sp_ids = { "test_attacker_target.collectionproxyc" }
    go.post_to(go.get_id(self), self.collection_sp_ids[1], "load")
    go.post_to(go.get_id(self), self.collection_sp_ids[1], "init")
    go.post_to(go.get_id(self), self.collection_sp_ids[1], "activate")
    self.timer = 4
end

function update(self, dt)
    self.timer = self.timer - dt
    if self.timer < 0 then
        go.post("exit", { code = 1 })
    end
end
