import Task, TaskGen
from TaskGen import extension, declare_extension
import os, sys
import waf_gamesys

def build(bld):
    obj = bld.new_task_gen(
        features = 'cc cxx cprogram',
        uselib = 'GTEST GAMEOBJECT DDF RESOURCE GAMESYS GRAPHICS_NULL GRAPHICS_UTIL DLIB PHYSICS RENDER PLATFORM_SOCKET LUA SCRIPT HID_NULL INPUT PARTICLE GUI SOUND_NULL',
        uselib_local = 'engine',
        includes = '../build ../proto .',
        #NOTE: _XBOX to get static lib and avoid dllimport/dllexport stuff
        defines = '_XBOX',
        proto_gen_py = True,
        protoc_includes = '../proto',
        target = 'test_engine')
    obj.find_sources_in_dirs('.', exts = ['.cpp', '.project', '.font', '.vp', '.fp', '.gamepads', '.input_binding', '.collection', '.script', '.go', '.collisionobject', '.convexshape', '.material', '.collectionproxy'])
    obj.install_path = None
