#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    script = bld.new_task_gen(features = 'cxx cstaticlib',
                          includes = '.',
                          target = 'script',
                          install_path='${PREFIX}/lib')
    script.find_sources_in_dirs(['.'])

    bld.install_files('${PREFIX}/include/script', 'script.h')

    bld.add_subdirs('test')
