def configure(conf):
    pass

def build(bld):
    box2d = bld.new_task_gen(features = 'cxx cstaticlib',
                                   includes = '..',
                                   target = 'Box2D',
                                   install_path='${PREFIX}/lib' )
    box2d.find_sources_in_dirs('. Collision Collision/Shapes Common Dynamics Dynamics/Contacts Dynamics/Joints')
