tests_done = false

local function create_geometries(count)
    local tbl = {}
    for i=1,count do
        table.insert(tbl, {
                vertices = {},
                uvs      = {},
                indices  = {}})
    end
    return tbl
end

-- Check the default animation
local function test_simple()
    local frame_count = go.get("#sprite", "frame_count")
    assert(frame_count == 4)
end

-- Check a custom atlas with x animation frames
local function test_atlas()
    local tparams = {
       width          = 16,
       height         = 16,
       type           = graphics.TEXTURE_TYPE_2D,
       format         = graphics.TEXTURE_FORMAT_RGBA,
    }
    local texture    = resource.create_texture("/my_texture.texturec", tparams)
    local num_frames = 12
    local aparams = {
        texture = texture,
        animations = {{
                id          = "frames",
                width       = 128,
                height      = 128,
                frame_start = 1,
                frame_end   = num_frames + 1,
            }
        },
        geometries = create_geometries(num_frames)
    }
    local atlas = resource.create_atlas("/my_atlas.texturesetc", aparams)
    go.set("#sprite", "image", atlas)

    local frame_count = go.get("#sprite", "frame_count")
    assert(frame_count == num_frames)

    resource.release(texture)
    resource.release(atlas)
end

function init(self)
    test_simple()
    test_atlas()
    tests_done = true
end
