local function assert_error(func)
    local r, err = pcall(func)
    if not r then
        print(err)
    end
    assert(not r)
end

function init(self)
	local valid_atlas = hash("/sprite/atlas_valid.a.texturesetc")
	local valid_atlas_64 = hash("/sprite/atlas_valid_64x64.a.texturesetc")

	-- all of these should be the same initially.
	local without_options = go.get("#sprite", "image")
	local with_options_tex0 = go.get("#sprite", "image", { key = "tex0" })
	local with_options_tex1 = go.get("#sprite", "image", { key = "tex1" })

	assert(without_options == valid_atlas)
	assert(without_options == with_options_tex0)
	assert(without_options == with_options_tex1)

	go.set("#sprite", "image", valid_atlas_64, { key = "tex1" })
	assert(valid_atlas_64 == go.get("#sprite", "image", { key = "tex1" }))

	go.set("#sprite", "image", valid_atlas_64)
	assert(valid_atlas_64 == go.get("#sprite", "image"))

	go.set("#sprite", "image", valid_atlas_64, { key = "tex0" })
	assert(valid_atlas_64 == go.get("#sprite", "image", { key = "tex0" }))

	-- error tests
	assert_error(function() go.set("#sprite", "image", "missing_atlas") end)
	assert_error(function() go.set("#sprite", "image", valid_atlas_64, { key = "missing_sampler" }) end)
end
