tests_done = false
num_finished = 0
num_messages = 0

local function callback(self, message_id, message, sender)
    num_finished = num_finished + 1

    self.waiting_to_render_invalid_texture = 1
    sprite.play_flipbook("#sprite", "does_not_exist") -- see to it that we handle an invalid animation
end

function init(self)
    sprite.play_flipbook("#sprite", "anim_once")

    num_finished = 0
    num_messages = 0

    self.waiting_to_render_invalid_texture = 0
end

function update(self, dt)
    if self.waiting_to_render_invalid_texture == 1 then
        self.waiting_to_render_invalid_texture = self.waiting_to_render_invalid_texture + 1
    end

    tests_done = num_finished == 2 and self.waiting_to_render_invalid_texture > 1
end

function on_message(self, message_id, message)
    if message_id == hash("animation_done") then
        num_finished = num_finished + 1
        num_messages = num_messages + 1

        -- continue with the next animation
        sprite.play_flipbook("#sprite", "anim_once", callback)
    end
end

function final()
    assert(num_finished == 2)
    assert(num_messages == 1)
end
