-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

tests_done = false
num_finished = 0
num_messages = 0

local function callback(self, message_id, message, sender)
    num_finished = num_finished + 1

    self.waiting_to_render_invalid_texture = 1
    sprite.play_flipbook("#sprite", "does_not_exist") -- see to it that we handle an invalid animation
end

function init(self)
    sprite.play_flipbook("#sprite", "anim_once")

    num_finished = 0
    num_messages = 0

    self.waiting_to_render_invalid_texture = 0
end

function update(self, dt)
    if self.waiting_to_render_invalid_texture == 1 then
        self.waiting_to_render_invalid_texture = self.waiting_to_render_invalid_texture + 1
    end

    tests_done = num_finished == 2 and self.waiting_to_render_invalid_texture > 1
end

function on_message(self, message_id, message)
    if message_id == hash("animation_done") then
        num_finished = num_finished + 1
        num_messages = num_messages + 1

        -- continue with the next animation
        sprite.play_flipbook("#sprite", "anim_once", callback)
    end
end

function final()
    assert(num_finished == 2)
    assert(num_messages == 1)
end
