-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    go.animate("go1#sprite", "scale.x", go.PLAYBACK_ONCE_FORWARD, 0.0, go.EASING_LINEAR, 2/60.0, 0, function() go.delete("go1") end)
    go.animate("go2#sprite", "scale.x", go.PLAYBACK_ONCE_FORWARD, 0.0, go.EASING_LINEAR, 2/60.0, 1/60.0, function() go.delete("go2") end)
    go.animate("go3#sprite", "scale.x", go.PLAYBACK_ONCE_FORWARD, 0.0, go.EASING_LINEAR, 4/60.0, 1/60.0)

    self.last_scale_x = 1.0
end

function update(self, dt)
    local s = go.get("go3#sprite", "scale")
    if (s.x < 1.0 and s.x > 0.0) then
        assert(s.x < self.last_scale_x)
        self.last_scale_x = s.x
    end
    local size = go.get("go3#sprite", "size")
    assert(size.x == 16.0 and size.y == 16.0)
end
