#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    resource = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                                includes = '.',
                                proto_gen_py = True,
                                proto_gen_java = True,
                                protoc_includes = '../../proto',
                                # NOTE: default/... is hardcoded. How to solve?
                                classpath=bld.env['DYNAMO_HOME'] + '/ext/share/java/protobuf-java-2.3.0.jar' + os.pathsep + bld.env['DYNAMO_HOME'] + '/share/java/ddf.jar',
                                target = 'gamesys',
                                ddf_jar = 'gamesys.jar',
                                install_path='${PREFIX}/lib')

    resource.find_sources_in_dirs(['.', '../../proto'])

    bld.install_files('${PREFIX}/include/gamesys', 'gameobject_registration.h')
    bld.install_files('${PREFIX}/include/gamesys', 'resource_creation.h')
    bld.install_files('${PREFIX}/share/proto', '../../proto/physics_ddf.proto')
