#! /usr/bin/env python

VERSION='0.1'
APPNAME='hello'

srcdir = '.'
blddir = 'build'

import os, glob
import waf_ddf, waf_graphics, waf_dynamo, waf_gamesys, waf_physics, waf_render

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('java')
    conf.check_tool('waf_dynamo')

    waf_graphics.configure(conf)
    waf_ddf.configure(conf)
    waf_physics.configure(conf)
    waf_render.configure(conf)
    waf_gamesys.configure(conf)

def build(bld):
    obj = bld.new_task_gen()

    content_source_dirs = ['.']
    for top_file in glob.glob('*'):
        if os.path.isdir(top_file) and top_file != 'build' and top_file != '.git':
            content_source_dirs.append(top_file)
            for root, dirs, files in os.walk(top_file):
                for d in dirs:
                    content_source_dirs.append(os.path.join(root, d))

    obj.find_sources_in_dirs(' '.join(content_source_dirs))
    obj.source.append('game.project')
