#! /usr/bin/env python

def build(bld):
#    bld.add_subdirs('test')

    bld.new_task_gen(
            features = 'cxx cstaticlib',
            source = 'ddf.cpp ddf_load.cpp ddf_inputbuffer.cpp ddf_util.cpp ddf_message.cpp ddf_loadcontext.cpp ',
            target = 'ddf')

    bld.install_files('${PREFIX}/include/ddf', 'ddf.h')

def configure(conf):
    pass

