-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    self.frame_count = 0

    local s = vmath.vector3(64, 64, 0)
    for i=0,19 do
        for j=0,10 do
            local p = vmath.vector3(i*64, j*64, 0)
            local n = gui.new_box_node(p, s)
            local c = math.random()
            gui.set_pivot(n, gui.PIVOT_SW)
            gui.set_color(n, vmath.vector4(c, c, c, 1))
        end
    end
end

function update(self)
    if self.frame_count == 5 then
        msg.post("@system:", "exit", {code = 0})
    end

    self.frame_count = self.frame_count + 1
end

