#! /usr/bin/env python

import Task, TaskGen
from TaskGen import extension, declare_extension
import os, sys, glob, re
import waf_gamesys

def build(bld):

    defines = ['_XBOX'] #NOTE: _XBOX to get static lib and avoid dllimport/dllexport stuff
    if re.match('arm.*?darwin', bld.env.PLATFORM):
        defines = ['DM_NO_SYSTEM_FUNCTION'] # Needed because we wish to build the tests for all platforms, but not all platforms have the system() function

    obj = bld.new_task_gen(
        features = 'cc cxx cprogram test',
        uselib = 'RECORD VPX GTEST PROFILEREXT GAMEOBJECT DDF RESOURCE GAMESYS GRAPHICS_NULL GRAPHICS_UTIL PHYSICS RENDER PLATFORM_SOCKET SCRIPT LUA EXTENSION HID_NULL INPUT PARTICLE RIG GUI TRACKING SOUND_NULL DLIB DMGLFW LIVEUPDATE',
        exported_symbols = ['ProfilerExt'],
        uselib_local = 'engine engine_service',
        includes = '../../proto .',
        defines = defines,
        source = 'test_engine.cpp',
        target = 'test_engine')

    # Psapi.lib is needed by ProfilerExt
    if 'win32' in bld.env.BUILD_PLATFORM:
        obj.env.append_value('LINKFLAGS', ['Psapi.lib'])

    builtins_src = "content/builtins"
    builtins_dst = "src/test/builtins"

    # Build engine test content using bob
    # We always run distclean. Hook into waf clean/distclean in some way?
    bld.new_task_gen(rule = 'java -Djava.ext.dirs= -jar ${SRC[0].abspath(env)} -r ${SRC[1].src_dir(env)} distclean build',
                     source = '../../content/bob-engine.jar wscript',
                     always = True)

    obj.install_path = None
