-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function on_input(self, action_id, action)
    -- mouse less input
    if action_id == hash("test_action") then
        assert(action.x == nil)
        assert(action.y == nil)
        assert(action.dx == nil)
        assert(action.dy == nil)
    elseif action_id == nil then -- mouse movement
        assert(action.value == nil)
        assert(action.pressed == nil)
        assert(action.released == nil)
        assert(action.repeated == nil)
        assert(action.x == 1.0)
        assert(action.y == 2.0)
        assert(action.dx == 3.0)
        assert(action.dy == 4.0)
    else
        assert(false, "unkown action")
    end
end
