-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

require "lua.test_helpers"

local function assert_custom_color(v)
    assert_vec4(v, go.get("#model", "custom_color"))
end

local function test_go_get()
    assert_custom_color(vmath.vector4(1,0,0,1))
    go.set("#model", "custom_color", vmath.vector4(0,1,0,1))
    assert_custom_color(vmath.vector4(0,1,0,1))
end

function init(self)
    test_go_get()
end
