-- Copyright 2020-2024 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

require "lua.test_helpers"

local function test_all_aabb(self)
    local res = model.get_aabb("#model")
    local cube_aabb = res[hash("Cube")]
    assert_not_nil(cube_aabb)
    assert_vec3(cube_aabb.min, vmath.vector3(-50.000019073486, -50, -50.000019073486))
    assert_vec3(cube_aabb.max, vmath.vector3(50.000019073486, 50, 50.000030517578))
end

local function test_wrong_component_url(self)
    assert_error(function()
        local res = model.get_aabb("#invalid_model")
    end)
end

function init(self)
    test_all_aabb(self)
    test_wrong_component_url(self)
end
