#ifndef H_NETWORK_CONSTANTS
#define H_NETWORK_CONSTANTS

#define CONST_UNIVERSAL_BIND_ADDRESS_IPV4 "0.0.0.0"
#define CONST_UNIVERSAL_BIND_ADDRESS_IPV6 "::"
#define CONST_LOOPBACK_ADDRESS_IPV4       "127.0.0.1"
#define CONST_LOOPBACK_ADDRESS_IPV6       "::1"

#endif