#ifndef DM_NETWORK_CONSTANTS
#define DM_NETWORK_CONSTANTS

#define DM_UNIVERSAL_BIND_ADDRESS_IPV4 "0.0.0.0"
#define DM_UNIVERSAL_BIND_ADDRESS_IPV6 "::"
#define DM_LOOPBACK_ADDRESS_IPV4       "127.0.0.1"
#define DM_LOOPBACK_ADDRESS_IPV6       "::1"

#endif