function init(self)
    local p = get_position(self)
    assert(p.x == 0)
    assert(p.y == 0)
    assert(p.z == 0)

    self.counter = 0
    assert(self.counter == 0)

    self.counter = self.counter +  1
    assert(self.counter == 1)
    tmp = "1";
end

function update(self)
    assert (self.counter == 1)

    local p = get_position(self)

    p.y = 123.0
    set_position(self, p)

    p = get_position(self)
    assert(p.y == 123.0)

    post("spawn", {prototype = "test", pos = vec_math.vector3(1, 2, 3)} )
end

function on_event(self, event_hash, event)
    assert(event_hash == hash("spawn_result"))
    assert(event.status == 1010)
end

functions = { init = init, update = update, on_event = on_event }
