local EPSILON = 0.001
local function assert_near_vector4(a,b)
    assert(math.abs(a.x-b.x) < EPSILON)
    assert(math.abs(a.y-b.y) < EPSILON)
    assert(math.abs(a.z-b.z) < EPSILON)
    assert(math.abs(a.w-b.w) < EPSILON)
end

function assert_all(exp_v1,exp_v2,exp_v3,exp_v4)
	local v1 = go.get("#sprite", "custom_value_1")
	assert_near_vector4(exp_v1, v1)

	local v2 = go.get("#sprite", "custom_value_2")
	assert_near_vector4(exp_v2, v2)

	local v3 = go.get("#sprite", "custom_value_3")
	assert_near_vector4(exp_v3, v3)

	local v4 = go.get("#sprite", "custom_value_4")
	assert_near_vector4(exp_v4, v4)
end

function init(self)
	assert_all(vmath.vector4(1,2,3,4), vmath.vector4(11,12,13,14), vmath.vector4(21,22,23,24), vmath.vector4(31,32,33,34))

	go.set("#sprite", "custom_value_2", vmath.vector4(91, 92, 93, 94))
	assert_all(vmath.vector4(1,2,3,4), vmath.vector4(91, 92, 93, 94), vmath.vector4(21,22,23,24), vmath.vector4(31,32,33,34))

	go.set("#sprite", "custom_value_4", vmath.vector4(1337, 1338, 1339, 1340))
	assert_all(vmath.vector4(1,2,3,4), vmath.vector4(91, 92, 93, 94), vmath.vector4(21,22,23,24), vmath.vector4(1337, 1338, 1339, 1340))

	go.set("#sprite", "custom_value_1", vmath.vector4(-1, -2, -3, -4))
	assert_all(vmath.vector4(-1, -2, -3, -4), vmath.vector4(91, 92, 93, 94), vmath.vector4(21,22,23,24), vmath.vector4(1337, 1338, 1339, 1340))

	go.set("#sprite", "custom_value_3", vmath.vector4(-100, -101, -102, -103))
	assert_all(vmath.vector4(-1, -2, -3, -4), vmath.vector4(91, 92, 93, 94), vmath.vector4(-100, -101, -102, -103), vmath.vector4(1337, 1338, 1339, 1340))
end
