
(customize-set-variable 'clojure-indent-style 'align-arguments)

(define-clojure-indent
  (assoc 1)
  (make-nodes 2)
  (fnk 1)
  (precluding-errors 1)
  (with-auto-evaluation-context 1)
  (with-auto-or-fake-evaluation-context 1)
  (with-system 1)
  (with-config! 1)
  (with-temp-dir 1)
  (with-temp-dir! 1)
  (maybe-silently 1)
  (with-git 1)
  (gl-push-matrix 1)
  (with-gl-bindings 1)
  (defhandler 1)
  (register-ddf-resource-type 1)
  (event-handler 1)
  (invalidation-listener 1)
  (on-action! 1)
  (on-closing! 1)
  (with-controls 1)
  (with-progress 1)
  (-if 1)
  (when 1)
  (when-not 1)
  (with-server 2)
  (with-build-results 1)
  (with-error-translation 1)
  (with-loaded-project 1)
  (with-logged-calls 1)
  (with-prop 1)
  (with-temp-dir! 1)
  (with-channel 1)
  (profile 1)
  (are '(:defn)))
