#! /usr/bin/env python

VERSION='0.1'
APPNAME='texc'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo
import waflib.Options
import TestContext

test_context = None

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('java')

    conf.recurse('src')

    conf.env.append_value('INCLUDES', "default/src")
    conf.env['STLIB_DLIB'] = 'dlib'
    conf.env['STLIB_DLIB_NOASAN'] = ['dlib_noasan']
    conf.env['STLIB_BASIS_ENCODER'] = 'basis_encoder'
    conf.env['STLIB_BASIS_TRANSCODER'] = 'basis_transcoder'

    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="TEXC"')

def build(bld):
    global test_context

    is_desktop = bld.env['PLATFORM'] in ('x86_64-macos', 'x86_64-linux', 'x86_64-win32')
    if not is_desktop:
        return

    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)
