#! /usr/bin/env python

VERSION='0.1'
APPNAME='texc'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo

def init(ctx):
    pass

def options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.recurse('src')

    conf.env.append_value('INCLUDES', "default/src")
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_DLIB_NOASAN'] = 'dlib_noasan'
    conf.env['STATICLIB_BASIS_ENCODER'] = 'basis_encoder'
    conf.env['STATICLIB_BASIS_TRANSCODER'] = 'basis_transcoder'

    platform = conf.env['PLATFORM']

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="TEXC"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="TEXC"')

def build(bld):
    bld.recurse('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
