import Task, TaskGen
from TaskGen import extension, declare_extension
from waf_dynamo import new_copy_task

new_copy_task('luascript', '.lua', '.luac')

def build(bld):
    libs = 'SCRIPT EXTENSION THREAD RESOURCE DDF DLIB LUA SCRIPT CARES'
    if 'android' in bld.env['PLATFORM']:
        libs += ' UNWIND'
    test_crash = bld.new_task_gen(features = 'cxx cprogram test',
                                     includes = '..',
                                     uselib = libs,
                                     uselib_local = 'crashext',
                                     web_libs = ['library_sys.js'],
                                     target = 'test_crash',
                                     source = 'test_crash.cpp')

    test_crash.install_path = None
    test_crash.env.append_value('LINKFLAGS', ['Psapi.lib'])

    test_script_crash = bld.new_task_gen(features = 'cxx cprogram test',
                                     includes = '..',
                                     uselib = libs,
                                     uselib_local = 'crashext',
                                     web_libs = ['library_sys.js','library_script.js'],
                                     target = 'test_script_crash',
                                     exported_symbols = 'CrashExt',
                                     source = 'test_script_crash.cpp test_crash.lua')

    test_script_crash.install_path = None
    test_script_crash.env.append_value('LINKFLAGS', ['Psapi.lib'])
