import Task, TaskGen
from TaskGen import extension, declare_extension
from waf_dynamo import new_copy_task

new_copy_task('luascript', '.lua', '.luac')

def build(bld):
    libs = 'TESTMAIN SCRIPT EXTENSION THREAD RESOURCE DDF DLIB LUA SCRIPT CARES'
    if 'android' in bld.env['PLATFORM']:
        libs += ' UNWIND'
    test_crash = bld.new_task_gen(features = 'cxx cprogram test',
                                     includes = '..',
                                     uselib = libs,
                                     uselib_local = 'crashext',
                                     web_libs = ['library_sys.js'],
                                     target = 'test_crash',
                                     source = 'test_crash.cpp')

    test_crash.install_path = None
    if 'win32' in bld.env['PLATFORM']:
        test_crash.env.append_value('LINKFLAGS', ['Psapi.lib'])

    # essentially only test that it links
    test_crash_null = bld.new_task_gen(features = 'cxx cprogram',
                                     includes = '..',
                                     uselib = libs,
                                     uselib_local = 'crashext_null',
                                     web_libs = ['library_sys.js'],
                                     target = 'test_crash_null',
                                     source = 'test_crash.cpp')

    test_crash_null.install_path = None

    test_script_crash = bld.new_task_gen(features = 'cxx cprogram test',
                                     includes = '..',
                                     uselib = libs,
                                     uselib_local = 'crashext',
                                     web_libs = ['library_sys.js','library_script.js'],
                                     target = 'test_script_crash',
                                     exported_symbols = 'CrashExt',
                                     source = 'test_script_crash.cpp test_crash.lua')

    test_script_crash.install_path = None
    if 'win32' in bld.env['PLATFORM']:
        test_script_crash.env.append_value('LINKFLAGS', ['Psapi.lib'])

    test_script_crash_null = bld.new_task_gen(features = 'cxx cprogram test',
                                     includes = '..',
                                     uselib = libs,
                                     uselib_local = 'crashext_null',
                                     web_libs = ['library_sys.js','library_script.js'],
                                     target = 'test_script_crash_null',
                                     exported_symbols = 'CrashExt',
                                     source = 'test_script_crash_null.cpp test_crash_null.lua')
    test_script_crash_null.install_path = None
