-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local speed = -30

function update(self, dt)
	local p = go.get_position()
	-- apply the speed
	p.x = p.x + speed * dt
	-- reset clouds to far right when they reach the far left to create infinite scrolling
	if p.x <= -1280 then
		p.x = 1280
	end
	go.set_position(p)
end
