import sys

def set_options(opt):
    pass

def configure(conf):
    conf.sub_config('box2d')
    conf.sub_config('physics')

def build(bld):
    bld.add_subdirs('box2d')
    bld.add_subdirs('physics')
