from waf_dynamo import dmsdk_add_files

def options(opt):
    pass

def configure(conf):
    conf.recurse('box2d')
    conf.recurse('physics')

def build(bld):
    bld.recurse('box2d')
    bld.recurse('physics')

    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')
