function init(self)
    self.sprite_pred = render.predicate({"sprite"})
    self.gui_pred = render.predicate({"gui"})
    self.text_pred = render.predicate({"text"})
end

function update(self)
    render.clear({[graphics.BUFFER_TYPE_COLOR0_BIT] = vmath.vector4(0, 0, 0, 0)})

    render.set_viewport(0, 0, render.get_window_width(), render.get_window_height())
    render.set_view(vmath.matrix4())
    render.set_projection(vmath.matrix4_orthographic(0, render.get_window_width(), 0, render.get_window_height(), -1, 1))

    render.set_depth_mask(false)
    render.disable_state(graphics.STATE_DEPTH_TEST)
    render.enable_state(graphics.STATE_BLEND)
    render.set_blend_func(graphics.BLEND_FACTOR_SRC_ALPHA, graphics.BLEND_FACTOR_ONE_MINUS_SRC_ALPHA)
    render.disable_state(graphics.STATE_CULL_FACE)

    render.draw(self.sprite_pred)

    render.set_projection(vmath.matrix4_orthographic(0, render.get_window_width(), render.get_window_height(), 0, -1, 1))

    render.draw(self.gui_pred)
    render.draw(self.text_pred)
end

function on_message(self, message_id, message)
end