function init(self)
    self.ids = {"opaque.spawnpointc"}--, "transparent.spawnpointc"}
    go.post("acquire_input_focus", { game_object_id = go.get_id(self) })
end

function on_input(self, action_id, action)
    if action_id == hash("ok") then
        local index = math.random(1, #self.ids)
        go.post_to(go.get_id(self), self.ids[index], "spawn_object", { position = go.get_position(self), rotation = vmath.quat(0,0,0,1) })
    end
    return false
end
