go.property("prop1", msg.url("url"))
go.property("prop2", msg.url(""))
go.property("prop3", msg.url())
go.property("prop4", msg.url('url'))
go.property("prop5", msg.url(''))
go.property("prop6", msg.url('socket', '/path/to/object', 'fragment'))
go.property("prop7", msg.url(hash('socket-hash'), hash('/path/to/object-hash'), hash('fragment-hash')))
go.property("prop8", msg.url("", "", ""))
go.property("prop9", msg.url("", ""))
go.property("prop10", msg.url(nil))
go.property("prop11", msg.url("", "", nil))
