#! /usr/bin/env python
import os

def build(bld):
    test = bld.new_task_gen(features='cxx cprogram test',
                            uselib='TESTUTIL TESTMAIN DLIB',
                            uselib_local='launcherutil',
                            includes = ['.'],
                            target='test_launcher',
                            source='test_launcher.cpp')

    test.install_path = None
    
