#! /usr/bin/env python
import os

def build(bld):
    test = bld.program(features='cxx test',
                       use='DLIB launcherutil',
                       includes = ['.'],
                       target='test_launcher',
                       source='test_launcher.cpp')

    test.install_path = None
    
