import Task, TaskGen
from TaskGen import extension, declare_extension

def build(bld):
    test_fb = bld.new_task_gen(features = 'cxx cprogram test',
                                includes = '../../../src .',
                                uselib = 'GTEST DLIB PLATFORM_SOCKET LUA SCRIPT',
                                uselib_local = 'facebookext',
                                target = 'test_fb',
                                source = 'test_fb.cpp')

    test_fb.install_path = None
