#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    record = bld.new_task_gen(features = 'cxx cstaticlib',
                              includes = '.',
                              target = 'record')


    record.find_sources_in_dirs('.')
    bld.install_files('${PREFIX}/include/record', 'record.h')
