#! /usr/bin/env python

VERSION='0.1'
APPNAME='input'

srcdir = '.'
blddir = 'build'

import sys, os
import waf_dynamo, waf_ddf
import waflib.Options
import TestContext
from build_constants import TargetOS

test_context = None

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    target_os = conf.env['TARGET_OS']

    waf_ddf.configure(conf)

    conf.recurse('src')

    conf.env.append_value('INCLUDES', "src")
    conf.env['STLIB_DLIB'] = ['dlib', 'mbedtls']
    conf.env['STLIB_DDF'] = 'ddf'
    conf.env['STLIB_HID_NULL'] = 'hid_null'

    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="INPUT"')

    if target_os != TargetOS.WINDOWS:
        conf.env.append_value('CFLAGS', ["-fdebug-compilation-dir=engine/input"])
        conf.env.append_value('CXXFLAGS', ["-fdebug-compilation-dir=engine/input"])

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)
