#! /usr/bin/env python

VERSION='0.1'
APPNAME='input'

srcdir = '.'
blddir = 'build'

import sys, os
import waf_dynamo, waf_ddf

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')

    waf_ddf.configure(conf)

    conf.recurse('src')

    conf.env.append_value('INCLUDES', "default/src")
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_DDF'] = 'ddf'
    conf.env['STATICLIB_HID_NULL'] = 'hid_null'

    platform = conf.env['PLATFORM']

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="INPUT"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="INPUT"')

def build(bld):
    bld.recurse('src')

def shutdown(self):
    waf_dynamo.run_tests(valgrind = True)
