#! /usr/bin/env python

VERSION='0.1'
APPNAME='hid'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')

    waf_ddf.configure(conf)

    conf.recurse('src')

    conf.env.append_value('INCLUDES', "default/src")

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="HID"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="HID"')

def build(bld):
    bld.recurse('src')

def shutdown(self):
    waf_dynamo.run_tests(valgrind = True)

