-- Scenario: An object is on a trigger and sends an event every frame.
-- When it sends 3 events, we set up a physics listener.
-- When 3 events are collected in the listener, the listener is removed.
-- On every switch, we make sure that events are sent only to either the message or the listener.

tests_done = false -- flag end of test to C level

function init(self)
	self.listener_counter = 0
	self.message_counter = 0
	self.expected_count = 3
	self.total_counter = 0
end

function update(self)
	if self.check_next_frame then
		self.check_next_frame = self.check_next_frame - 1
		if self.check_next_frame == 0 then
			assert(self.expected_count == self.listener_counter)
			assert(5 == self.message_counter)
			tests_done = true
		end
	end
	if self.total_counter > 100 then
		assert(false)
	end
end

function on_message(self, message_id, message, sender)
	self.message_counter = self.message_counter + 1
	if self.message_counter == self.expected_count then
		physics.set_event_listener(function(self, events)
			for _, event in ipairs(events) do
				self.total_counter = self.total_counter + 1
				if event.type == hash("collision_event") then
					self.listener_counter = self.listener_counter + 1
					if self.listener_counter == self.expected_count then
						physics.set_event_listener(nil)
						self.check_next_frame = self.expected_count
					end
				end
			end
		end)
	end
end
