-- scenario: body1-go is dynamic, body2-go is trigger collision, both have event_trigger: false, body1-go is thrown to body2-go, trigger results are asserted

function init(self)
  -- throw object
  go.set("/body1-go#co", "linear_velocity", vmath.vector3(100,0,0))
end

tests_done = false -- flag end of test to C level
local counter = 0

local trigger_entered = false
local trigger_exited = false
function on_message(self, message_id, message, sender)
  if message_id == hash("trigger_response") then
    if message.enter == true then
      trigger_entered = true
    elseif message.enter == false then
      trigger_exited = true
    end
  end
end

function update(self, dt)
  counter = counter + 1

  if counter >= 120 then
    assert(not trigger_entered)
    assert(not trigger_exited)
    tests_done = true
  end
end

