-- helper functions to verify test data.
-- throws a Lua error if the assert(s) fails.
local function assert_near(a, b)
    local eps = 0.001
    local diff = math.abs(a - b)
    if not (diff < eps) then
        local err_msg = "assert_near failed, a: " .. tostring(a) .. ", b: " .. tostring(b) .. " diff == " .. tostring(diff) .. " >= " .. tostring(eps)
        error(debug.traceback(err_msg))
    end
end

function init(self)
	self.sphere_1 = physics.get_shape("/get_set_error_shape_go#collisionobject", "shape_sphere_1")
	assert(self.sphere_1.diameter ~= nil)
	assert_near(self.sphere_1.diameter, 16)
end

function final(self)
	self.sphere_1.diameter = 0
	physics.set_shape("/get_set_error_shape_go#collisionobject", "shape_sphere_1", self.sphere_1)
end