-- This is the test script for collision object properties. Starting with 'bullet' property. More to come...

function test_bullet_property()
  -- test getters/setters of bullet property
	assert(go.get("go#properties-co", "bullet") == false)
  go.set("go#properties-co", "bullet", true)
	assert(go.get("go#properties-co", "bullet"))
end

function test_collision_group()
    assert( physics.get_group("go#properties-co") == hash("user"))
    physics.set_group("go#properties-co","default")
    assert( physics.get_group("go#properties-co") == hash("default"))
end

function test_collision_mask()
    assert( physics.get_maskbit("go#properties-co", "default") )
    physics.set_maskbit("go#properties-co","default", false)
    assert( not physics.get_maskbit("go#properties-co","default") )
    
    physics.set_maskbit("go#properties-co","enemy", true)
    assert( physics.get_maskbit("go#properties-co","enemy") )
end

function init(self)
  physics.set_gravity(vmath.vector3(0, -10, 0))

  test_bullet_property()
  test_collision_group()
  test_collision_mask()
end

tests_done = false -- flag end of test to C level

function update(self, dt)
    tests_done = true
end
