-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.



function init(self)
  physics.set_gravity(vmath.vector3(0, -10, 0)) -- note, higher gravity (like -100) won't allow the object to settle
end

tests_done = false -- flag end of test to C level

local counter = 0
local body1_asleep_pos

function update(self, dt)
  counter = counter + 1

  if counter == 100 then -- iterate 100 times to allow bodies to settle and sleep
		physics.create_joint(physics.JOINT_TYPE_FIXED, "body1-go#body-co", "my_test_joint", vmath.vector3(0, 0, 0), "body2-go#body-co", vmath.vector3(0, 0, 0), { max_length = 20 })
    body1_asleep_pos = go.get_position("body1-go")
	end

	if counter == 110 then -- iterate a little more to make sure that object although attached hasn't moved
    local body1_pos = go.get_position("body1-go")
    assert(body1_asleep_pos.x == body1_pos.x)
    assert(body1_asleep_pos.y == body1_pos.y)
    physics.wakeup("body1-go#body-co")
  end

  if counter >= 120 then -- make sure the object has now moved after being awaken
    local body1_pos = go.get_position("body1-go")
    assert(body1_asleep_pos.x ~= body1_pos.x)
    tests_done = true
  end
end
