-- scenario: body1 is moving , body2 is still. body1 velocity should cause elastic  collision

function init(self)
  physics.set_gravity(vmath.vector3(0, -10, 0))
  go.set("/body1-go#body-co", "linear_velocity", vmath.vector3(21, 0, 0) )
  go.set("/body2-go#body-co", "linear_velocity", vmath.vector3(0, 0, 0) )
end

tests_done = false -- flag end of test to C level
local zero_velocity = vmath.vector3(0,0,0)
local counter = 0



function update(self, dt)
  counter = counter + 1    
  local velocity1 = math.floor(vmath.length(go.get("body1-go#body-co", "linear_velocity")))
  local velocity2 = math.floor(vmath.length(go.get("body2-go#body-co", "linear_velocity")))
  --print("Frame", counter,":", velocity1, "-", velocity2)
  
  -- object hit at frames 16. At 10, object 2 should stand still
  if counter == 10 then
	assert(velocity2 == 0)
  end
  -- at frame 20, object 2 should move faster than object 1
  if counter == 20 then
	assert(velocity2 > velocity1)
  end
  
  -- at frame 30 we stop object1 and have object 2 run against it with a smaller velocity
  if counter == 30 then
	go.set("/body1-go#body-co", "linear_velocity", vmath.vector3(0, 0, 0) )
    go.set("/body2-go#body-co", "linear_velocity", vmath.vector3(-19, 0, 0) )
  end
  
  -- at frame 50 both object should move with the same velocity
  if counter == 50 then
	assert(velocity1 == velocity2)
  end

  if counter >= 120 then -- make sure that body1 has smaller velocity, and body2 is moving
    tests_done = true
  end
end
