import sys, os
import Task, TaskGen
from TaskGen import extension

def build(bld):
    sys.path.insert(0, "default/proto")

    flist = 'cc cxx cprogram'

    if 'web' in bld.env['PLATFORM']:
        flist = flist + ' web'

    font_viewer = bld.new_task_gen(features = flist,
                                    source = 'fontview.cpp deja_vu_sans.font vera_mo_bd.font font.vp font.fp font.material',
                                    uselib = 'RENDER GRAPHICS RESOURCE HID DDF DMGLFW PLATFORM_SOCKET SCRIPT LUA EXTENSION DLIB X',
                                    web_libs = ['library_sys.js', 'library_glfw.js'],
                                    uselib_local = 'gamesys',
                                    includes = ['../../../src', '../../../build'],
                                    target = 'fontview')
    font_viewer.install_path = None
