import sys, os
import waflib.Task, waflib.TaskGen
from waflib.Options import options

def build(bld):
    if options.skip_build_tests:
        return

    sys.path.insert(0, "default/proto")

    flist = 'c cxx cprogram'

    if 'web' in bld.env['PLATFORM']:
        flist = flist + ' web'

    font_viewer = bld.program(features = flist,
                              source   = 'fontview.cpp deja_vu_sans.font vera_mo_bd.font font.vp font.fp font.material',
                              use      = 'RENDER CRASH GRAPHICS RESOURCE HID DDF DMGLFW PLATFORM_SOCKET SCRIPT LUA EXTENSION DLIB X CARES gamesys',
                              web_libs = ['library_sys.js', 'library_glfw.js'],
                              includes = ['../../../../src',  '../../../build'],
                              target   = 'fontview')

    font_viewer.install_path = None
