#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    resource = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                                includes = '. ../proto',
                                protoc_includes = '../proto',
                                proto_gen_py = True,
                                target = 'resource')
    resource.find_sources_in_dirs('.')

    if 'js-web' in bld.env.PLATFORM:
         resource.source.append('async/load_queue_sync.cpp');
    else:
         resource.source.append('async/load_queue_threaded.cpp');

    resource.find_sources_in_dirs('async')
    resource.find_sources_in_dirs('../proto')

    bld.add_subdirs('test')
    bld.install_files('${PREFIX}/include/resource', 'resource.h')
    bld.install_files('${PREFIX}/lib/python', 'waf_resource.py')
    bld.install_files('${PREFIX}/bin', 'arcc.py')

