#! /usr/bin/env python

VERSION='0.1'
APPNAME='lua'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf, waflib
import TestContext
from build_constants import TargetOS

test_context = None

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.load('waf_dynamo')
    opt.recurse('src')

def configure(conf):
    conf.load('waf_dynamo')
    conf.recurse('src')

    target_os = conf.env['TARGET_OS']
    if target_os != TargetOS.WINDOWS:
        conf.env.append_value('CFLAGS', ["-fdebug-compilation-dir=engine/lua"])
        conf.env.append_value('CXXFLAGS', ["-fdebug-compilation-dir=engine/lua"])

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)

