#! /usr/bin/env python

VERSION='0.1'
APPNAME='lua'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')
    opt.recurse('src')

def configure(conf):
    conf.load('waf_dynamo')
    conf.recurse('src')

def build(bld):
    bld.recurse('src')
