#! /usr/bin/env python

VERSION='0.1'
APPNAME='lua'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')
    opt.add_option('--skip-apidocs', action='store_true', default=False, dest='skip_apidocs', help='skip extraction and generation of API docs.')
    opt.sub_options('src')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.sub_config('src')

def build(bld):
    bld.add_subdirs('src')
