import os

def set_options(opt):
    pass

def configure(conf):
    conf.sub_config('gamesys')

def build(bld):
    bld.add_subdirs('gamesys')
    bld.install_files('${PREFIX}/lib/python', 'waf_gamesys.py')
    bld.install_files('${PREFIX}/lib/python/colladaImEx', 'colladaImEx/*.py')

    if 'android' in bld.env['PLATFORM']:
        classpath = ['%s/ext/share/java/android.jar' % bld.env.DYNAMO_HOME]
        classpath = os.pathsep.join(classpath)

        bld.new_task_gen(features='javac seq',
                         classpath=classpath,
                         source_root='java')

        bld.env["JAVACFLAGS"] = '-g -source 1.7 -target 1.7'

        bld.new_task_gen(features='jar seq',
                         basedir='java',
                         destfile='gamesys_android.jar')

        bld.install_files('${PREFIX}/share/java', 'gamesys_android.jar')
