#! /usr/bin/env python

VERSION='0.1'
APPNAME='physics'

srcdir = '.'
blddir = 'build'

import os, sys
import waf_dynamo, waf_ddf
import waflib.Options
import TestContext
from BuildUtility import create_build_utility

test_context = None

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.recurse('src')
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')

    waf_ddf.configure(conf)

    conf.recurse('src')

    build_util = create_build_utility(conf.env)
    ext_libpath = build_util.get_dynamo_ext('lib', build_util.get_target_platform())
    ext_libpath_norm = os.path.normcase(os.path.normpath(ext_libpath))
    conf.env['LIBPATH'] = [ext_libpath] + [p for p in conf.env['LIBPATH'] if os.path.normcase(os.path.normpath(p)) != ext_libpath_norm]

    conf.env.append_value('INCLUDES', "default/src")
    conf.env['STLIB_DLIB']         = 'dlib'
    conf.env['STLIB_BULLET']       = ['BulletDynamics', 'BulletCollision', 'LinearMath']
    conf.env['STLIB_BOX2D']        = 'box2d'
    conf.env['STLIB_BOX2D_DEFOLD'] = 'box2d_defold'

    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="PHYSICS"')

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context)
