def configure(conf):
    pass

def build(bld):
    linear_math = bld.new_task_gen(features = 'cxx cstaticlib',
                           includes = '. ..',
                           target = 'LinearMath',
                           uselib = 'BULLET' )
    linear_math.find_sources_in_dirs('.')

#    bld.install_files('${PREFIX}/include/gamesys', 'resource.h')
#    bld.install_files('${PREFIX}/include/gamesys', 'gameobject.h')
#    bld.install_files('${PREFIX}/share/proto', 'gameobject_ddf.proto')
