#!/usr/bin/env python
import os
from BuildUtility import create_build_utility

def build(bld):
    build_util = create_build_utility(bld.env)

    bld.new_task_gen(features = 'cxx cprogram test',
                    includes = ['../%s' % build_util.get_target_os(), '..', '.'],
                    uselib = 'APP DLIB DMGLFW PLATFORM PLATFORM_SOCKET LUA SCRIPT',
                    uselib_local = 'hid_null',
                    target = 'test_hid',
                    source = 'test_hid.cpp')


    web_libs = ['library_glfw.js', 'library_sys.js']  
    bld.new_task_gen(features = 'cxx cprogram test skip_test',
                    includes = ['../%s' % build_util.get_target_os(), '..', '.'],
                    uselib = 'APP DLIB OPENGL DMGLFW CARES PLATFORM PLATFORM_SOCKET LUA SCRIPT',
                    uselib_local = 'hid',
                    web_libs = web_libs,
                    target = 'test_app_hid',
                    source = 'test_app_hid.cpp')
