-- Copyright 2020-2022 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
	self.update_counter = 0
end

function update(self, dt)
	if self.update_counter == 0 then
		local mouse_lock = window.get_mouse_lock()
		assert(mouse_lock == false)

		window.set_mouse_lock(true)
		mouse_lock = window.get_mouse_lock()
		assert(mouse_lock == true)
	elseif self.update_counter == 1 then
		-- not supported
		window.set_mouse_lock("false")
	end

	self.update_counter = self.update_counter + 1
end
