function init(self)
	self.update_counter = 0
end

function update(self, dt)
	if self.update_counter == 0 then
		local mouse_lock = window.get_mouse_lock()
		assert(mouse_lock == false)

		window.set_mouse_lock(true)
		mouse_lock = window.get_mouse_lock()
		assert(mouse_lock == true)
	elseif self.update_counter == 1 then
		-- not supported
		window.set_mouse_lock("false")
	end

	self.update_counter = self.update_counter + 1
end
