#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    extension = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                                 includes = '.',
                                 target = 'extension')
    extension.find_sources_in_dirs('.')

    bld.add_subdirs('test')
    bld.install_files('${PREFIX}/include/extension', 'extension.h')
