#! /usr/bin/env python
import os, re

def configure(conf):
    pass

def build(bld):
    bld.add_subdirs('test')
    bld.install_files('${PREFIX}/include/extension', 'extension.h')
    bld.install_files('${PREFIX}/sdk/include/dmsdk/extension', 'dmsdk/extension/extension.h')

    source = ['extension.cpp']
    if re.match('arm.*?darwin', bld.env.PLATFORM):
        source += ['extension_ios.cpp']

    extension = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                                 includes = '.',
                                 source = source,
                                 target = 'extension')

