#! /usr/bin/env python
import os, re
from waf_dynamo import dmsdk_add_files
from BuildUtility import create_build_utility

def configure(conf):
    pass

def build(bld):
    bld.recurse('test')
    bld.install_files('${PREFIX}/include/extension', 'extension.h')
    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')

    source = ['extension.cpp']
    if bld.env.PLATFORM in ('arm64-darwin', 'x86_64-ios'):
        source += ['extension_ios.cpp']
    if re.match('arm.*?android', bld.env.PLATFORM):
        source += ['extension_android.cpp']

    build_util = create_build_utility(bld.env)
    extension = bld.stlib(features     = 'cxx ddf',
                          includes     = '.',
                          source       = source,
                          install_path = build_util.get_library_path(),
                          target       = 'extension')

