#! /usr/bin/env python

VERSION='0.1'
APPNAME='docs'

srcdir = '.'
blddir = 'build'

import sys, os, re
import waf_dynamo

def init():
    pass

def configure(conf):
    conf.env['SCRIPT_DOC'] = os.path.abspath('script_doc.py')
    pass

def build(bld):
#        bld.new_task_gen(source = source,
#                         target = '%s_doc.sdoc' % source,
#                         rule = 'python ${SCRIPT_DOC} ${SRC} ${TGT}')
#        bld.new_task_gen(source = source,
#                         target = '%s_doc.json' % source,
#                         rule = 'python ${SCRIPT_DOC} -t json ${SRC} ${TGT}')

def install(bld):
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')
