#! /usr/bin/env python

import sys, os, re
import waf_dynamo

def configure(conf):
    conf.env['SCRIPT_DOC'] = os.path.abspath('src/script_doc.py')
    pass

def build(bld):
    files = bld.path.ant_glob('*.apidoc_')
    for source in files.split():
        namespace, _ = os.path.splitext(source)
        bld.new_task_gen(source = source,
                     target = '%s_doc.sdoc' % namespace,
                     rule = 'python ${SCRIPT_DOC} ${SRC} ${TGT}')
        bld.new_task_gen(source = source,
                     target = '%s_doc.json' % namespace,
                     rule = 'python ${SCRIPT_DOC} -t json ${SRC} ${TGT}')
        bld.new_task_gen(source = source,
                     target = '%s_doc.script_api' % namespace,
                     rule = 'python ${SCRIPT_DOC} -t script_api ${SRC} ${TGT}')

        bld.install_files('${PREFIX}/share/doc', '%s_doc.sdoc' % namespace)
        bld.install_files('${PREFIX}/share/doc', '%s_doc.json' % namespace)
        bld.install_files('${PREFIX}/share/doc', '%s_doc.script_api' % namespace)

def set_options(opt):
    opt.tool_options('waf_dynamo')
