function init(self)
    -- properties
    self.group = 1
    self.mask = 2
    self.speed = 18
    self.impact_damage = 0.2
    self.hit_response = nil
end

function update(self, dt)
    local rot = go.get_world_rotation()
    local expired = false
    if self.hit_response then
        expired = true
        local receiver = msg.url()
        receiver.path = self.hit_response.game_object_id
        msg.post(receiver, "hit", { damage = self.impact_damage })
    else
        local pos = go.get_world_position()
        -- prediction for CD
        local prev_pos = vmath.vector3(pos)
        local velocity = vmath.vector3(self.speed, 0, 0)
        local dp = vmath.rotate(rot, velocity) * dt
        pos = pos + dp
        local next_pos = pos + dp
        go.set_position(pos)
        -- request ray cast
        msg.post("@physics:", "ray_cast_request", {from = prev_pos, to = next_pos, ignored_game_object_id = go.get_id(), mask = self.mask})
    end
    if expired then
        go.delete()
    end
end

function on_message(self, message_id, message)
    if message_id == hash("ray_cast_response") then
        self.hit_response = message
    end
end