#! /usr/bin/env python
import os
from waflib.Options import options

import gen_java

def configure(conf):
    conf.load('java')
    conf.load('waf_dynamo')

    dynamo_home = conf.env.DYNAMO_HOME
    includes = [os.getcwd(),
                os.path.join(dynamo_home, 'sdk', 'include')]

    def make_path(path):
        cwd = os.getcwd()
        script_dir = conf.path.abspath()
        path = os.path.normpath(os.path.join(script_dir, path))
        if not os.path.exists(path):
            os.makedirs(path)
        return os.path.relpath(path, cwd)

    gen_java.generate(header_path   = make_path('./atlasc.h'),
                     namespace      = 'dmAtlasc',
                     package_name   = 'com.dynamo.bob.pipeline',
                     includes       = includes,
                     java_outdir    = make_path('./java'),
                     jni_outdir     = make_path('./jni'))


def build(bld):
    # We only need this library in the editor and bob
    if not bld.env.IS_TARGET_DESKTOP:
        print("Skipping build of modelc for non host platform")
        return

    atlaspacker_source = bld.path.ant_glob("atlaspacker/*.c")

    bld.stlib(features     = 'c skip_asan',
                source       = atlaspacker_source,
                includes     = ['./atlaspacker/include'],
                target       = 'atlaspacker')

    # java_includes = [os.path.join(os.environ['JAVA_HOME'], 'include')]
    # if 'linux' in bld.env['PLATFORM']:
    #     java_includes.append(os.path.join(os.environ['JAVA_HOME'], 'include', 'linux'))
    # if 'win32' in bld.env['PLATFORM']:
    #     java_includes.append(os.path.join(os.environ['JAVA_HOME'], 'include', 'win32'))
    # if 'macos' in bld.env['PLATFORM']:
    #     java_includes.append(os.path.join(os.environ['JAVA_HOME'], 'include', 'darwin'))

    atlasc_sources = bld.path.ant_glob("atlasc.cpp") + bld.path.ant_glob("jni/**/*.cpp")

    # The static library for the tests
    bld.stlib(features  = 'cxx',
               source   = atlasc_sources,
               includes = ['.', './atlaspacker/include'],
               use      = 'JDK JNI',
               target   = 'atlasc')

    # The dynamic library for the shared library
    bld.stlib(features  = 'cxx skip_asan',
               source   = atlasc_sources,
               includes = ['.', './atlaspacker/include'],
               use      = 'JDK JNI',
               target   = 'atlasc_noasan')

    atlasc_shared_sources = bld.path.ant_glob("atlasc*.cpp")

    bld.shlib(features     = 'cxx cshlib skip_asan',
                source       = atlasc_shared_sources,
                includes     = ['.', './jni', './atlaspacker/include'],
                target       = 'atlasc_shared',
                use          = 'DLIB_NOASAN PROFILE_NULL_NOASAN JNI_NOASAN JDK atlaspacker atlasc_noasan')

    # ******************************************************************************************
    # JAVA: atlascompiler.jar

    # classpath = [os.path.join(bld.env.DYNAMO_HOME, '../../com.dynamo.cr/com.dynamo.cr.bob/lib/jna-5.10.0.jar'),
    #              os.path.join(bld.env.DYNAMO_HOME, '../..//com.dynamo.cr/com.dynamo.cr.bob/lib/jna-platform-5.10.0.jar')]

    # bld(features='javac seq',
    #     classpath=classpath,
    #     srcdir='java/atlasc',
    #     outdir='java/atlasc')

    # bld.env["JAVACFLAGS"] = '-g -source 1.8 -target 1.8'.split()

    # bld(features='jar seq',
    #     basedir='java/atlasc',
    #     destfile='atlascompiler.jar')


    bld(features='javac seq',
        #classpath=[],
        srcdir='java',
        outdir='java')

    bld.env["JAVACFLAGS"] = '-g'.split()

    bld(features='jar seq',
        basedir='java',
        destfile='atlascompiler.jar')

    # ******************************************************************************************

    bld.install_files('${PREFIX}/include/atlasc', 'atlasc.h')
    bld.install_files('${PREFIX}/share/java', 'atlascompiler.jar')

    # ******************************************************************************************

    if not options.skip_build_tests:
        bld.recurse('test')
