#! /usr/bin/env python
import os, waflib.Task
from waflib.TaskGen import feature, before
from waf_dynamo import dmsdk_add_files

def options(opt):
    pass

def build(bld):
    bld.recurse('ddf')
    bld.recurse('test')

    bld.install_files('${PREFIX}/lib/python', 'waf_ddf.py')
    bld.install_files('${PREFIX}/bin', 'ddfc.py', chmod=493)
    bld.install_files('${PREFIX}/bin', 'ddfc_java', chmod=493)
    bld.install_files('${PREFIX}/bin', 'ddfc_cxx', chmod=493)
    bld.install_files('${PREFIX}/bin', 'ddfc_cxx.bat')
    bld.install_files('${PREFIX}/share/proto/ddf', 'ddf/ddf_extensions.proto')
    bld.install_files('${PREFIX}/share/proto/ddf', 'ddf/ddf_math.proto')
    bld.install_files('${PREFIX}/share/proto/ddf', 'ddf/ddf_struct.proto')

    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')

def configure(conf):
    pass

