#! /usr/bin/env python

VERSION='0.1'
APPNAME='gameobject'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf

def init():
    pass

def set_options(opt):
    opt.sub_options('src')
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.check_tool('java')
    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")
    conf.env['LIB_GTEST'] = 'gtest'
    conf.env['STATICLIB_DLIB'] = ['dlib', 'axtls']
    conf.env['STATICLIB_DDF'] = 'ddf'
    conf.env['STATICLIB_RIG'] = 'rig'
    conf.env['STATICLIB_RESOURCE'] = 'resource'
    conf.env['STATICLIB_SCRIPT'] = 'script'
    conf.env['STATICLIB_EXTENSION'] = 'extension'

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="GAMEOBJECT"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="GAMEOBJECT"')

def build(bld):
    sys.path.insert(0, os.path.abspath('build/default/proto'))
    sys.path.insert(0, os.path.abspath('build/default/proto/gameobject'))
    bld.add_subdirs('src')

import Build, Options
import os, subprocess
def shutdown():
    if not Options.commands['build']:
        return
    waf_dynamo.run_gtests(valgrind = True)
