#!/usr/bin/env python

VERSION='0.1'
APPNAME='gameobject'

srcdir = '.'
blddir = 'build'

import sys, os
import waf_dynamo, waf_ddf
import waflib.Options
import TestContext

test_context = None

def generate_source_proto(task):
    output, package_init = task.outputs
    output.parent.mkdir()
    command = task.env.PROTOC + ['--python_out=' + output.parent.parent.abspath()]
    for include in task.generator.protoc_includes:
        command += ['-I', os.path.normpath(os.path.join(task.generator.path.abspath(), include))]
    command.append(task.inputs[0].abspath())
    result = task.exec_command(command)
    if result == 0:
        package_init.write('')
    return result

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.recurse('src')
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('java')
    waf_ddf.configure(conf)

    conf.recurse('src')

    conf.env.append_value('INCLUDES', 'src')
    conf.env.append_value('INCLUDES', 'src/proto')
    conf.env['STLIB_DLIB']      = ['dlib', 'image', 'zip', 'dmbedtls']
    conf.env['STLIB_DDF']       = 'ddf'
    conf.env['STLIB_RIG']       = 'rig'
    conf.env['STLIB_RESOURCE']  = 'resource'
    conf.env['STLIB_SCRIPT']    = 'script'
    conf.env['STLIB_EXTENSION'] = 'extension'

    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="GAMEOBJECT"')

def build(bld):
    global test_context

    sys.path.insert(0, os.path.abspath('build/proto'))
    sys.path.insert(0, os.path.abspath('build/proto/gameobject'))

    # This authoring schema imports component descriptions and must only
    # generate Python, without passing through the native DDF compiler.
    source_proto = bld.path.find_resource('proto/gameobject_source/gameobject_source_ddf.proto')
    source_python = source_proto.change_ext('_pb2.py')
    source_init = source_python.parent.find_or_declare('__init__.py')
    bld(name='gameobject_source_proto_py',
        rule=generate_source_proto,
        source=source_proto,
        target=[source_python, source_init],
        scan=waf_ddf.scan,
        protoc_includes=['proto', '../gamesys/proto', '../particle/proto',
                         '../ddf/src', '../graphics/proto', bld.env['DYNAMO_HOME'] + '/ext/include'])
    bld.install_files('${PREFIX}/lib/python/gameobject_source', [source_python, source_init])
    bld.install_files('${PREFIX}/share/proto/gameobject_source', source_proto)

    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, folders = {"build/src/gameobject/test": "build/src/gameobject/test"})
