tests_done = false -- flag end of test to C level

time_elapsed = 0

local function sound_evt_callback(self, message_id, message, sender)
	assert(message_id == hash("sound_stopped"))
	assert(time_elapsed < 0.555)

	tests_done = true
end

function init(self)
    sound.play("#sound", { delay = 1 }, sound_evt_callback)
end

function update(self, dt)
	if time_elapsed > 0.5 then
		sound.stop("#sound")
	end
	time_elapsed = time_elapsed + dt
end
