-- Copyright 2020-2023 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
-- 
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
-- 
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local function sound_evt_callback(self, message_id, message, sender)
    if message_id == hash("sound_stopped") then
        self.sound_done = 1
        print("sound done!", self.count)
    end
end

function init(self)
    self.sound_done = 0
    self.count = 0
    sound.play("#sound", nil, sound_evt_callback)
end

function final(self)
    assert(self.sound_done == 1)
end

function update(self, dt)
    print("update")
    self.count = self.count + 1
    if self.count == 1 then
        sound.stop("#sound")
    end
end
