-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    self.updated = false
end

function update(self, dt)
    -- update sound only once
    if not self.updated then
        local host_path = sys.get_host_path("src/gamesys/test/sound_ext/replacement.wav")
        local f = io.open(host_path, "rb")
        local c  = f:read("*all")
        f:close()

        local path = go.get("/go#dynamic-sound", "sound")
        resource.set_sound(path, c);

        self.updated = true;
    end
end
