function init(self)
    self.updated = false
end

function update(self, dt)
    -- update sound only once
    if not self.updated then
        local f = io.open("src/gamesys/test/sound_ext/replacement.wav")
        local c  = f:read("*all")
        f:close()
        --print("data size: ", #c)

        local path = go.get("/go#dynamic-sound", "sound")
        --assert(path == hash("/sound/valid.wav"))
        resource.set_sound(path, c);

        self.updated = true;
    end
end
