#!/usr/bin/env python
# Copyright 2020-2026 The Defold Foundation
# Copyright 2014-2020 King
# Copyright 2009-2014 Ragnar Svensson, Christian Murray
# Licensed under the Defold License version 1.0 (the "License"); you may not use
# this file except in compliance with the License.
#
# You may obtain a copy of the License, together with FAQs at
# https://www.defold.com/license
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

VERSION = '0.1'
APPNAME = 'debugger'
srcdir = '.'
blddir = 'build'

import waf_dynamo
import waflib.Options

test_program = None

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="DEBUGGER"')

def build(bld):
    global test_program
    if 'web' in bld.env.PLATFORM:
        return
    bld.stlib(features='cxx', target='debugger',
              source='src/dap.cpp src/debugger.cpp src/debugger_values.cpp src/debugger_extension.cpp',
              includes='src ../script/src ..', uselib='LUA')
    bld.install_files('${PREFIX}/include/debugger', 'src/debugger.h')
    if not bld.options.skip_build_tests and bld.env.PLATFORM == bld.env.BUILD_PLATFORM:
        test_program = bld.program(features='cxx', target='dap_debuggee', source='src/test/test_debugger.cpp',
                                   includes='src', use='debugger DLIB LUA SOCKET THREAD PROFILE_NULL')

def shutdown(ctx):
    if test_program is None or getattr(waflib.Options.options, 'skip_tests', False):
        return
    import subprocess, sys
    if getattr(test_program, 'link_task', None):
        binary = test_program.link_task.outputs[0].abspath()
        subprocess.check_call([sys.executable, 'src/test/test_dap.py', '--debuggee', binary])
