#! /usr/bin/env python

VERSION='0.1'
APPNAME='modelc'

srcdir = '.'
blddir = 'build'

import sys, os
import waf_dynamo, waf_ddf

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.check_tool('waf_ddf')

    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_DDF'] = 'ddf'

    if 'JAVA_HOME' in os.environ:

        host = 'windows'
        if 'linux' in sys.platform:
            host = 'linux'
        elif 'darwin' in sys.platform:
            host = 'darwin'

        conf.env['CPPPATH_JDK'] = [os.path.join(os.environ['JAVA_HOME'], 'include'), os.path.join(os.environ['JAVA_HOME'], 'include', host)]
        conf.env['LIBPATH_JDK'] = os.path.join(os.environ['JAVA_HOME'], 'lib')
        #conf.env['LIB_JDK'] = ['native']
        conf.env['DEFINES_JDK'] = ['DM_HAS_JDK']

    platform = conf.env['PLATFORM']

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="MODELC"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="MODELC"')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
