#! /usr/bin/env python
import os, sys, shutil
from waflib.TaskGen import feature, before, after
from waf_dynamo import platform_supports_feature

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')

def build(bld):

    n = bld.path.make_node('build/main.cpp')
    n.write('#include <stdio.h>\nint main() {printf("hello\\n"); return 0;}\n')

    bld.add_group()
    bld.program(source='build/main.cpp', target='app')
