#! /usr/bin/env python

VERSION='0.1'
APPNAME='wscript'

srcdir = '.'
blddir = 'build'

import sys, os
import waf_dynamo, waf_ddf
import Options

def init():
    pass

def set_options(opt):
    opt.tool_options('compiler_cc')
    opt.tool_options('compiler_cxx')
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('compiler_cc')
    conf.check_tool('compiler_cxx')
    conf.check_tool('java')
    conf.check_tool('waf_dynamo')

    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")
    conf.env['LIB_GTEST'] = 'gtest'
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_DDF'] = 'ddf'

    platform = conf.env['PLATFORM']

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="VSCRIPT"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="VSCRIPT"')

def build(bld):
    bld.add_subdirs('src')

def shutdown():
    if not Options.commands['build'] or getattr(Options.options, 'skip_tests', False):
        return

    python_path = os.environ.get('PYTHONPATH', '')
    os.environ['PYTHONPATH'] = 'src' + os.pathsep + 'build/default/proto' + os.pathsep + python_path
    ret = os.system('python %s' % 'src/test/test_vscript.py')
    if ret != 0:
        sys.exit(1)

    waf_dynamo.run_gtests(valgrind = True)
