#! /usr/bin/env python

VERSION='0.1'
APPNAME='arkanoid'

srcdir = '.'
blddir = 'build'

import waf_ddf, waf_graphics, waf_dynamo, waf_gamesys, waf_physics, waf_render

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('java')
    conf.check_tool('waf_dynamo')

    waf_graphics.configure(conf)
    waf_ddf.configure(conf)
    waf_physics.configure(conf)
    waf_render.configure(conf)
    waf_gamesys.configure(conf)

def build(bld):
    obj = bld.new_task_gen()
    content_source_dirs = [
    	'.',
        'fonts',
        'graphics',
        'input',
        'logic',
        'logic/session/',
        'sounds',
    ]
    obj.find_sources_in_dirs(' '.join(content_source_dirs))
    obj.source.append('game.project')
