#! /usr/bin/env python

VERSION='0.1'
APPNAME='resource'

srcdir = '.'
blddir = 'build'

import os, subprocess
import sys
sys.path = ["src"] + sys.path
import urllib2, time, atexit
from Logs import error
import Options
import waf_dynamo, waf_ddf, waf_resource

os.environ['PATH'] = os.path.abspath('src') + os.pathsep + os.environ['PATH']

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.check_tool('waf_resource')
    conf.check_tool('java')

    waf_ddf.configure(conf)

    conf.sub_config('src')

    conf.env.append_value('CPPPATH', "default/src")
    conf.env['LIB_GTEST'] = 'gtest'
    conf.env['STATICLIB_DLIB'] = ['dlib', 'axtls']
    conf.env['STATICLIB_DDF'] = 'ddf'

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="RESOURCE"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="RESOURCE"')

def build(bld):
    bld.add_subdirs('src')

def kill_proc(proc):
    proc.kill()

def shutdown():
    if not Options.commands['build'] or getattr(Options.options, 'skip_tests', False):
        return

    proc = subprocess.Popen(["python", "-m", "SimpleHTTPServer", "6123"],
                            shell = False,
                            cwd = "build/default/src/test")
    atexit.register(kill_proc, proc)

    start = time.time()
    while True:
        if time.time() - start > 5:
            error('HTTP server failed to start within 5 seconds')
            sys.exit(1)
        try:
            urllib2.urlopen('http://localhost:6123')
            break
        except urllib2.URLError:
            print('Waiting for HTTP testserver to start...')
            sys.stdout.flush()
            time.sleep(0.5)

    waf_dynamo.run_gtests(valgrind = True)
