#! /usr/bin/env python

VERSION='0.1'
APPNAME='webview'

srcdir = '.'
blddir = 'build'

import sys, re, os
import waf_dynamo, waf_ddf

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.recurse('src')

    conf.env.append_value('INCLUDES', "default/src")

    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['STATICLIB_EXTENSION'] = 'extension'

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="WEBVIEW"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="WEBVIEW"')

def build(bld):
    bld.recurse('src')

def shutdown():
    waf_dynamo.run_tests(valgrind = True)
