#! /usr/bin/env python

VERSION = '0.1'
APPNAME = 'graphics'

srcdir = '.'
blddir = 'build'

import os, sys

import waf_ddf, waf_dynamo

def init(ctx):
    pass

def options(opt):
    opt.recurse('src')
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    waf_ddf.configure(conf)

    conf.recurse('src')

    platform = conf.env['PLATFORM']

    if platform == "linux" or platform == "x86_64-linux":
        conf.env.append_value('CXXFLAGS', ['-DGL_GLEXT_PROTOTYPES', '-D_GLFW_HAS_GLXGETPROCADDRESS'])
    elif 'web' in platform:
        conf.env.append_value('CXXFLAGS', ['-DGL_GLEXT_PROTOTYPES'])

    if os.getenv('PYTHONPATH'):
        if sys.platform == "win32":
            ddf_search_lst = os.getenv('PYTHONPATH').split(';')
        else:
            ddf_search_lst = os.getenv('PYTHONPATH').split(':')

    dynamo_home = os.getenv('DYNAMO_HOME')
    if not dynamo_home:
        conf.fatal("DYNAMO_HOME not set")
    dynamo_ext = os.path.join(dynamo_home, "ext")

    if platform == "darwin" or platform == 'x86_64-darwin':
        conf.env.append_value('LINKFLAGS', ['-framework', 'Carbon', '-framework', 'OpenGL', '-framework', 'AGL', '-framework', 'IOKit', '-framework', 'CoreVideo'])
    elif platform == "x86_64-ios":
        pass
    elif platform == "linux" or platform == "x86_64-linux":
        conf.env.append_value('LINKFLAGS', ['-lXext', '-lX11', '-lXi', '-lGL', '-lGLU', '-lpthread'])
    elif "win32" in platform:
        conf.env.append_value('LINKFLAGS', ['opengl32.lib'])

    conf.env.append_value('INCLUDES', "../src")
    conf.env.append_value('INCLUDES', os.path.join(dynamo_ext, "include"))
    conf.env.append_value('LIBPATH', os.path.join(dynamo_ext, "lib", platform))
    conf.env.append_value('INCLUDES', os.path.join(dynamo_home, "include" ))
    conf.env.append_value('INCLUDES', os.path.join(dynamo_home, "include", platform))

    conf.env.append_value('CCDEFINES', 'SDL_JOYSTICK_IOKIT')
    conf.env.append_value('CXXDEFINES', 'SDL_JOYSTICK_IOKIT')

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="GRAPHICS"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="GRAPHICS"')

def build(bld):
    bld.recurse('src')
    bld.install_files('${PREFIX}/include/win32', bld.path.ant_glob('include/win32/*.h'))
    bld.install_files('${PREFIX}/bin', bld.path.ant_glob('bin/*'), chmod=493)

def shutdown(self):
    waf_dynamo.run_tests(valgrind = True)
