import Task, TaskGen
from TaskGen import extension, declare_extension

def build(bld):
    test_buffer = bld.new_task_gen(features = 'cxx cprogram test',
                                   includes = '../../../src .',
                                   uselib = 'GTEST DLIB',
                                   uselib_local = 'buffer',
                                   target = 'test_buffer',
                                   source = 'test_buffer.cpp')

    test_buffer.install_path = None
