#! /usr/bin/env python

VERSION = '0.1'
APPNAME = 'app'

srcdir = '.'
blddir = 'build'

import Options
import os, sys
import waf_dynamo

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')
    opt.sub_options('src')

def configure(conf):
    conf.check_tool('waf_dynamo')
    conf.check_tool('java')
    conf.recurse('src')

def build(bld):
    bld.recurse('src')

def shutdown():
    if not Options.commands['build'] or getattr(Options.options, 'skip_tests', False):
        return

    waf_dynamo.run_tests(valgrind = True)
