def set_options(opt):
    pass

def configure(conf):
    conf.sub_config('gamesys')

def build(bld):
    bld.add_subdirs('gamesys')
    bld.install_files('${PREFIX}/lib/python', 'waf_gamesys.py')
    bld.install_files('${PREFIX}/lib/python/colladaImEx', 'colladaImEx/*.py')
