#! /usr/bin/env python

from waf_dynamo import apidoc_extract_task

def configure(conf):
    pass

def build(bld):

    source = ''
    if bld.env['PLATFORM'] in ['arm64-nx64']:
        source += ' switch_account.cpp switch_hid.cpp '

    bld.new_task_gen(features = 'cxx cstaticlib',
                    includes = ['.'],
                    uselib = 'DLIB HID',
                    source = 'script_switch.cpp ' + source,
                    target = 'switchext')

    apidoc_extract_task(bld, ['script_switch.cpp'])

