local expected_lorem_ipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
local host_fs = test_host_fs or ""

local function assert_error(func)
    local r, err = pcall(func)
    if not r then
        print(err)
    end
    assert(not r)
end

local function test_load_buffer_invalid(self)
    assert_error(function() sys.load_buffer("invalid_path.ext") end)
end

local function test_load_buffer_path(self, path)
    local b = sys.load_buffer(path)
    assert(b)

    local s = buffer.get_bytes(b, "data")
    assert(s == expected_lorem_ipsum)
end

function init(self)
    test_load_buffer_invalid(self)
    test_load_buffer_path(self, "/sys/sys_buffer_test_content.rawc") -- from resource system
    test_load_buffer_path(self, host_fs .. "src/gamesys/test/sys/sys_buffer_test_content.raw") -- from disk
end
