-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

tests_done = false

function init(self)
    local co = coroutine.create(function()
        local expected_data = "coroutine callback"
        sys.load_buffer_async("/sys/sys_buffer_test_content.rawc", function(self, request_id, result)
            assert(request_id ~= nil)
            assert(result.status == sys.REQUEST_STATUS_FINISHED)
            assert(result.buffer ~= nil)
            assert(expected_data == "coroutine callback")
            tests_done = true
        end)
    end)

    local ok, error = coroutine.resume(co)
    assert(ok, tostring(error))
    assert(coroutine.status(co) == "dead")

    co = nil
    collectgarbage("collect")
end
