-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local expected_lorem_ipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

local function assert_error(func)
    local r, err = pcall(func)
    if not r then
        print(err)
    end
    assert(not r)
end

local function test_load_buffer_invalid(self)
    assert_error(function() sys.load_buffer("invalid_path.ext") end)
end

local function test_load_buffer_path(self, path)
    local b = sys.load_buffer(path)
    assert(b)

    local s = buffer.get_bytes(b, "data")
    assert(s == expected_lorem_ipsum)
end

function init(self)
    test_load_buffer_invalid(self)
    test_load_buffer_path(self, "/sys/sys_buffer_test_content.rawc") -- from resource system
    test_load_buffer_path(self, "src/gamesys/test/sys/sys_buffer_test_content.raw") -- from disk
end

