tests_done = false

function init(self)
    local co = coroutine.create(function()
        local expected_data = "coroutine callback"
        sys.load_buffer_async("/sys/sys_buffer_test_content.rawc", function(self, request_id, result)
            assert(request_id ~= nil)
            assert(result.status == sys.REQUEST_STATUS_FINISHED)
            assert(result.buffer ~= nil)
            assert(expected_data == "coroutine callback")
            tests_done = true
        end)
    end)

    local ok, error = coroutine.resume(co)
    assert(ok, tostring(error))
    assert(coroutine.status(co) == "dead")

    co = nil
    collectgarbage("collect")
end
