name: Linux

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wayland-protocols libwayland-dev libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxi-dev libxcursor-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -j$(nproc)
    - name: Unit Tests
      run: |
        cd build/bin/
        ./skribidi_test