#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    script = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                              includes = '../proto .',
                              target = 'vscript',
                              proto_gen_py = True,
                              proto_gen_java = True,
                              ddf_jar = 'vscript.jar',
                              protoc_includes = '../proto',
                              classpath=bld.env['DYNAMO_HOME'] + '/ext/share/java/protobuf-java-2.3.0.jar' + os.pathsep + bld.env['DYNAMO_HOME'] + '/share/java/ddf.jar',
                              install_path='${PREFIX}/lib')
    script.find_sources_in_dirs(['.', '../proto'])

