-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("go_consume_yes", "acquire_input_focus")
	msg.post("go_consume_yes#collectionproxy", "load")
end

function on_input(self, action_id, action)
	-- store away this object globally so that we can cross-reference in test module
	last_input_object = go.get_id()

	-- this should never happen,
	-- since the proxy script one level above always consumes when action.pressed != 0
	if action.pressed then
		assert(false)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "enable")
	end
end