#! /usr/bin/env python

def build(bld):
    bld.shlib(source='dlib/array.cpp', 
              includes = '.',
              target='myshlib')
        #bld.program(source='main.c', target='app', use='myshlib mystlib')
        #bld.stlib(source='a.c', target='mystlib', use='myobjects')
        #bld.shlib(source='b.c', target='myshlib')
        #bld.objects(source='c.c', target='myobjects')
    
