#! /usr/bin/env python
import os
from waf_dynamo import apidoc_extract_task

def configure(conf):
    pass

def build(bld):

    gameobject = bld.new_task_gen(features = 'cxx cstaticlib ddf rig',
                                  includes = '. ../../proto',
                                  proto_gen_py = True,
                                  protoc_includes = ['../../proto', bld.env['PREFIX'] + '/share'],
                                  protopy_includes = bld.env['PREFIX'] + '/lib/python',
                                  # NOTE: default/... is hardcoded. How to solve?
                                  target = 'gameobject')

    gameobject.find_sources_in_dirs(['.', '../../proto/gameobject'])
    bld.add_group()

    bld.add_subdirs('test')

    apidoc_extract_task(bld, ['../../proto/gameobject/gameobject_ddf.proto', 'gameobject_script.cpp'])

    bld.install_files('${PREFIX}/include/gameobject', 'gameobject.h')
    bld.install_files('${PREFIX}/include/gameobject', 'gameobject_script_util.h')
    bld.install_files('${PREFIX}/share/proto/gameobject', '../../proto/gameobject/properties_ddf.proto')
    bld.install_files('${PREFIX}/share/proto/gameobject', '../../proto/gameobject/gameobject_ddf.proto')
    bld.install_files('${PREFIX}/share/proto/gameobject', '../../proto/gameobject/lua_ddf.proto')
