#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):

    gameobject = bld.new_task_gen(features = 'cxx cstaticlib ddf sol',
                                  includes = '.',
                                  proto_gen_py = True,
                                  protoc_includes = ['../../proto', bld.env['PREFIX'] + '/share'],
                                  protopy_includes = bld.env['PREFIX'] + '/lib/python',
                                  # NOTE: default/... is hardcoded. How to solve?
                                  target = 'gameobject')

    gameobject.find_sources_in_dirs(['.', '../../proto'])
    bld.add_group()

    bld.add_subdirs('test')

    bld.new_task_gen(source = 'gameobject_script.cpp ../../proto/gameobject_ddf.proto',
                     target = 'go_doc.sdoc',
                     rule = '${SCRIPT_DOC} ${SRC} ${TGT}')

    bld.new_task_gen(source = 'gameobject_script.cpp ../../proto/gameobject_ddf.proto',
                     target = 'go_doc.json',
                     rule = '${SCRIPT_DOC} -t json ${SRC} ${TGT}')

    bld.install_files('${PREFIX}/share/doc', 'go_doc.sdoc')
    bld.install_files('${PREFIX}/share/doc', 'go_doc.json')

    bld.install_files('${PREFIX}/include/gameobject', 'gameobject.h')
    bld.install_files('${PREFIX}/include/gameobject', 'gameobject_script_util.h')
    bld.install_files('${PREFIX}/share/proto', '../../proto/properties_ddf.proto')
    bld.install_files('${PREFIX}/share/proto', '../../proto/gameobject_ddf.proto')
    bld.install_files('${PREFIX}/lib/sol', 'gameobject.sol')
