#! /usr/bin/env python

VERSION='0.1'
APPNAME='record'

srcdir = '.'
blddir = 'build'

import sys
import waf_dynamo, waf_ddf

def init(ctx):
    pass

def options(opt):
    opt.sub_options('src')
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('java')
    waf_ddf.configure(conf)

    conf.recurse('src')

    conf.env.append_value('INCLUDES', "default/src")
    conf.env['STATICLIB_DLIB'] = 'dlib'
    conf.env['LIB_VPX'] = 'vpx'

    conf.env.append_unique('CCDEFINES', 'DLIB_LOG_DOMAIN="RECORD"')
    conf.env.append_unique('CXXDEFINES', 'DLIB_LOG_DOMAIN="RECORD"')

def build(bld):
    bld.recurse('src')

import Build, Options
import os, subprocess
def shutdown():
    if not Options.commands['build']:
        return
    waf_dynamo.run_tests(valgrind = True)
