-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.



function init(self)
    self.timer = 0
    self.third_id = go.get_id("third")
end

function update(self, dt)
    self.timer = self.timer + dt
    if self.timer >= 0.02 and self.third_id ~= nil then
        print "Fourth kills third"
        go.delete(self.third_id)
        self.third_id = nil
    end
end

function final(self)
    print "Fourth object has been finalised"
end