syntax = "proto2";
package dmCollectionProxyDDF;

import "ddf/ddf_extensions.proto";
import "ddf/ddf_math.proto";

option java_package = "com.dynamo.gamesys.proto";
option java_outer_classname = "CollectionProxy";

message CollectionProxyDesc
{
    required string collection = 1 [(resource)=true];
    optional bool exclude = 2 [default=false];
}

enum TimeStepMode
{
    TIME_STEP_MODE_CONTINUOUS   = 0;
    TIME_STEP_MODE_DISCRETE     = 1;
}

/* Documented in comp_collecion_proxy.cpp */
message SetTimeStep
{
    required float          factor  = 1;
    required TimeStepMode   mode    = 2;
}

message ProxyLoading
{
    required float progress  = 1;
}

message ProxyReady
{
}