// Copyright 2020-2026 The Defold Foundation
// Copyright 2014-2020 King
// Copyright 2009-2014 Ragnar Svensson, Christian Murray
// Licensed under the Defold License version 1.0 (the "License"); you may not use
// this file except in compliance with the License.
//
// You may obtain a copy of the License, together with FAQs at
// https://www.defold.com/license
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

syntax = "proto2";
package dmCollectionProxyDDF;

import "ddf/ddf_extensions.proto";

option java_package = "com.dynamo.gamesys.proto";
option java_outer_classname = "CollectionProxy";

/*# Collection proxy API documentation
 *
 * Messages for controlling and interacting with collection proxies
 * which are used to dynamically load collections into the runtime.
 *
 * @document
 * @name Collection proxy
 * @namespace collectionproxy
 * @language Lua
 */

message CollectionProxyDesc
{
    required string collection = 1 [(resource)=true];
    optional bool exclude = 2 [default=false];
}

enum TimeStepMode
{
    TIME_STEP_MODE_CONTINUOUS   = 0;
    TIME_STEP_MODE_DISCRETE     = 1;
}

/* Documented in comp_collecion_proxy.cpp */
message SetTimeStep
{
    required float          factor  = 1;
    required TimeStepMode   mode    = 2;
}

/*# reports that a collection proxy is loading
 *
 * @message
 * @name proxy_loading
 * @param progress [type:number] the loading progress (0.0 to 1.0)
 * @examples
 *
 * ```lua
 * function init(self)
 *   collectionproxy.load("#proxy", {}, function(self, message_id, message, sender)
 *      if message_id == hash("proxy_loading") then
 *         print("Proxy loading progress:", message.progress)
 *      end
 *   end)
 * end
 * ```
 */
message ProxyLoading
{
    required float progress  = 1;
}

/*# reports that a collection proxy has been loaded and is running
 *
 * @message
 * @name proxy_ready
 * @examples
 *
 * ```lua
 * function init(self)
 *   collectionproxy.load("#proxy", {}, function(self, message_id, message, sender)
 *      if message_id == hash("proxy_ready") then
 *         print("Proxy has been loaded and is running")
 *      end
 *   end)
 * end
 * ```
 */
message ProxyReady
{
}

/*# reports that an error occurred while loading or initializing a collection
 * proxy
 *
 * @message
 * @name proxy_error
 * @param code [type:number] error code
 * @examples
 *
 * ```lua
 * function init(self)
 *   collectionproxy.load("#proxy", {}, function(self, message_id, message, sender)
 *      if message_id == hash("proxy_error") then
 *         print("Proxy loading error:", message.code)
 *      end
 *   end)
 * end
 * ```
 */
message ProxyError
{
    required int32 code = 1;
}
