#! /usr/bin/env python
import os

def configure(conf):
    pass

def build(bld):
    script = bld.new_task_gen(features = 'cc cxx cprogram',
                              uselib = 'DDF PLATFORM_SOCKET HID DLIB INPUT DMGLFW ',
                              source = 'main.cpp',
                              target = 'gdc')
