def build(bld):
    test_record = bld.new_task_gen(features='cxx cprogram',
                                   includes='../../../src .',
                                   uselib='GTEST DLIB VPX',
                                   uselib_local='record',
                                   proto_gen_py=True,
                                   target='test_record',
                                   source='test_record.cpp')
    test_record.install_path = None

