import sys, os
import Task, TaskGen
from TaskGen import extension

def build(bld):
    sys.path.insert(0, "default/proto")
    font_viewer = bld.new_task_gen(features = 'cc cxx cprogram',
                                    source = 'fontview.cpp DejaVuSans.font VeraMoBd.font font.vp font.fp font.material',
                                    uselib = 'RENDER GRAPHICS RESOURCE DLIB HID DDF DMGLFW PLATFORM_SOCKET',
                                    uselib_local = 'gamesys',
                                    includes = ['../../../src', '../../../build'],
                                    target = 'fontview')
    font_viewer.install_path = None

    fonts = bld.new_task_gen(
        features = '',
        size = 24,
        imagefont='VeraMoBd.imagefontc',
        source='VeraMoBd.ttf')

    fonts = bld.new_task_gen(
        features = '',
        size = 24,
        imagefont='DejaVuSans.imagefontc',
        source='DejaVuSans.ttf')
