#! /usr/bin/env python
import os, re
from waf_dynamo import apidoc_extract_task


def configure(conf):
    pass

def build(bld):
    source = 'push_null.cpp'

    platforms = ['arm.*?darwin', 'arm.*?android', 'x86_64-ios']
    for p in platforms:
        if re.match(p, bld.env.PLATFORM):
            source = 'push_stub.cpp'
            break

    bld.new_task_gen(features = 'cxx cstaticlib',
                    includes = '.',
                    source = source,
                    target = 'pushext')

    apidoc_extract_task(bld, ['push_doc.h'])

