#! /usr/bin/env python

import waflib.Task, waflib.Utils
from waflib.TaskGen import taskgen_method, feature, after, before
from cross_build import find_configured_platform_variant_files

VERSION='0.1'
APPNAME='extender'

srcdir = '.'
blddir = 'build'

def append_yaml(task):
    path = task.outputs[0].abspath()
    with open(path, 'wb') as out_f:
        for i in task.inputs:
            with open(i.abspath(), 'rb') as in_f:
                data = in_f.read()
                out_f.write(data)

    digest = waflib.Utils.h_file(path)
    for i in task.inputs:
        task.generator.bld.node_sigs[task.inputs[0]] = digest
    return 0

task = waflib.Task.task_factory('merge_yaml',
                                func  = append_yaml,
                                color = 'PINK',
                                before  = 'c cxx')
@taskgen_method
@feature('merge_yaml')
def feature_merge_yaml(self):
    inputs = []
    for source in self.yaml_source:
        if hasattr(source, 'abspath'):
            inputs.append(source)
        else:
            inputs.append(self.path.make_node(source))

    out = self.path.find_or_declare(self.yaml_target)
    task = self.create_task('merge_yaml')
    task.set_inputs(inputs)
    task.set_outputs(out)

def init(ctx):
    pass

def options(opt):
    opt.load('waf_dynamo')

def configure(conf):
    conf.load('waf_dynamo')

def build(bld):

    # build_input.yml is the template for generated build.yml. Platform variants
    # are named after the generated output, e.g. build_ios.yml.
    source_target = 'build.yml'
    source = find_configured_platform_variant_files(bld, 'build_input.yml', source_target)

    bld(features = 'merge_yaml',
        yaml_source = source,
        yaml_target = source_target,
        name='Build Yaml')

    variants = ('debug', 'release', 'headless')
    for variant in variants:
        source_target = 'variants/%s.appmanifest' % variant
        # *_input.appmanifest files are templates for generated manifests.
        # Platform variants use the generated output basename, e.g.
        # variants/debug_ios.appmanifest.
        source = find_configured_platform_variant_files(
            bld, 'variants/%s_input.appmanifest' % variant, source_target)

        bld(features = 'merge_yaml',
            yaml_source = source,
            yaml_target = source_target,
            name='Build Yaml %s' % variant)

    bld.add_group()
    bld.install_files('${PREFIX}/extender/', 'build.yml')
    bld.install_files('${PREFIX}/extender/variants/', 'variants/debug.appmanifest')
    bld.install_files('${PREFIX}/extender/variants/', 'variants/release.appmanifest')
    bld.install_files('${PREFIX}/extender/variants/', 'variants/headless.appmanifest')

def shutdown(ctx):
    pass
