#! /usr/bin/env python

VERSION='0.1'
APPNAME='extender'

srcdir = '.'
blddir = 'build'

import sys, re, os
import waf_dynamo

def init():
    pass

def set_options(opt):
    opt.tool_options('waf_dynamo')

def configure(conf):
    conf.check_tool('waf_dynamo')

def build(bld):
    bld.add_group()
    bld.install_files('${PREFIX}/extender', 'build.yml')
    bld.install_files('${PREFIX}/extender/variants', 'variants/*.appmanifest')

def shutdown():
    pass
