#ifndef DMGRAPHICS_VULKAN_DEFINES_H
#define DMGRAPHICS_VULKAN_DEFINES_H

#ifdef __MACH__
	/* note: VK_USE_PLATFORM_IOS_MVK and VK_USE_PLATFORM_MACOS_MVK are
	         apparently deprecated and VK_USE_PLATFORM_METAL_EXT should
	         be used instead. But at least on my dev machine, the ext is not
	         available.. Otherwise we'd do:

	         #define VK_USE_PLATFORM_METAL_EXT
	*/
    #if (defined(__arm__) || defined(__arm64__))
        #define VK_USE_PLATFORM_IOS_MVK
    #else
        #define VK_USE_PLATFORM_MACOS_MVK
    #endif
#elif ANDROID
	#define VK_USE_PLATFORM_ANDROID_KHR
#elif WIN32
	#define VK_USE_PLATFORM_WIN32_KHR
#elif __linux__
    #define VK_USE_PLATFORM_XCB_KHR
#endif

#define DMGRAPHICS_BUFFER_TYPE_COLOR_BIT                    (0x1)
#define DMGRAPHICS_BUFFER_TYPE_DEPTH_BIT                    (0x2)
#define DMGRAPHICS_BUFFER_TYPE_STENCIL_BIT                  (0x4)

// These defines don't have a Vulkan equivalent, so we
// just represent them as increasing number..
#define DMGRAPHICS_STATE_DEPTH_TEST                         (1)
#define DMGRAPHICS_STATE_SCISSOR_TEST                       (2)
#define DMGRAPHICS_STATE_STENCIL_TEST                       (3)
#define DMGRAPHICS_STATE_ALPHA_TEST                         (4)
#define DMGRAPHICS_STATE_BLEND                              (5)
#define DMGRAPHICS_STATE_CULL_FACE                          (6)
#define DMGRAPHICS_STATE_POLYGON_OFFSET_FILL                (7)
#define DMGRAPHICS_STATE_POLYGON_OFFSET_LINE                (8)
#define DMGRAPHICS_STATE_POLYGON_OFFSET_POINT               (9)
#define DMGRAPHICS_TEXTURE_TYPE_2D                          (10)
#define DMGRAPHICS_TEXTURE_TYPE_CUBE_MAP                    (11)

// Note: We can't use VK_FILTER_LINEAR/NEAREST here since
//       mipmap and texture filtering is separated into
//       VkSamplerMipmapMode and VkFilter
#define DMGRAPHICS_TEXTURE_FILTER_LINEAR                    (12)
#define DMGRAPHICS_TEXTURE_FILTER_NEAREST                   (13)
#define DMGRAPHICS_TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST    (14)
#define DMGRAPHICS_TEXTURE_FILTER_NEAREST_MIPMAP_LINEAR     (15)
#define DMGRAPHICS_TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST     (16)
#define DMGRAPHICS_TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR      (17)

#define DMGRAPHICS_RENDER_BUFFER_COLOR                      (18)
#define DMGRAPHICS_RENDER_BUFFER_DEPTH                      (19)
#define DMGRAPHICS_RENDER_BUFFER_STENCIL                    (20)
#define DMGRAPHICS_RENDER_BUFFER_COLOR_ATTACHMENT           (21)
#define DMGRAPHICS_RENDER_BUFFER_DEPTH_ATTACHMENT           (22)
#define DMGRAPHICS_RENDER_BUFFER_STENCIL_ATTACHMENT         (23)

// These defines do have a Vulkan equivalent,
// so we just use it directly.
#define DMGRAPHICS_PRIMITIVE_POINTS                         (0) // (VK_PRIMITIVE_TOPOLOGY_POINT_LIST)
#define DMGRAPHICS_PRIMITIVE_LINES                          (1) // (VK_PRIMITIVE_TOPOLOGY_LINE_LIST)
#define DMGRAPHICS_PRIMITIVE_LINE_LOOP                      (2) // (VK_INVALID)
#define DMGRAPHICS_PRIMITIVE_LINE_STRIP                     (3) // (VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP)
#define DMGRAPHICS_PRIMITIVE_TRIANGLES                      (4) // (VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST)
#define DMGRAPHICS_PRIMITIVE_TRIANGLE_STRIP                 (5) // (VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP)
#define DMGRAPHICS_PRIMITIVE_TRIANGLE_FAN                   (6) // (VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN)

// Types
#define DMGRAPHICS_TYPE_BYTE                                (VK_FORMAT_R8_SINT)
#define DMGRAPHICS_TYPE_UNSIGNED_BYTE                       (VK_FORMAT_R8_UINT)
#define DMGRAPHICS_TYPE_SHORT                               (VK_FORMAT_R16_SINT)
#define DMGRAPHICS_TYPE_UNSIGNED_SHORT                      (VK_FORMAT_R16_UINT)
#define DMGRAPHICS_TYPE_UNSIGNED_SHORT_4444                 (VK_FORMAT_R4G4B4A4_UNORM_PACK16)
#define DMGRAPHICS_TYPE_UNSIGNED_SHORT_565                  (VK_FORMAT_R5G6B5_UNORM_PACK16)
#define DMGRAPHICS_TYPE_INT                                 (VK_FORMAT_R32_SINT)
#define DMGRAPHICS_TYPE_UNSIGNED_INT                        (VK_FORMAT_R32_UINT)
#define DMGRAPHICS_TYPE_HALF_FLOAT                          (VK_FORMAT_R16_SFLOAT)
#define DMGRAPHICS_TYPE_FLOAT                               (VK_FORMAT_R32_SFLOAT)
#define DMGRAPHICS_TYPE_FLOAT_VEC4                          (VK_FORMAT_R32G32B32A32_SFLOAT)
#define DMGRAPHICS_TYPE_FLOAT_MAT4                          (VK_FORMAT_R32G32B32A32_SFLOAT)

// There's no sampler type in vulkan..
#define DMGRAPHICS_TYPE_SAMPLER_2D                          (VK_FORMAT_MAX_ENUM-1)
#define DMGRAPHICS_TYPE_SAMPLER_CUBE                        (VK_FORMAT_MAX_ENUM-2)

#define DMGRAPHICS_TEXTURE_FORMAT_LUMINANCE                 (VK_FORMAT_R8_UNORM)
#define DMGRAPHICS_TEXTURE_FORMAT_LUMINANCE_ALPHA           (VK_FORMAT_R8G8_UNORM)
#define DMGRAPHICS_TEXTURE_FORMAT_RGB                       (VK_FORMAT_R8G8B8_UINT)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA                      (VK_FORMAT_R8G8B8A8_UINT)

#define DMGRAPHICS_TEXTURE_WRAP_REPEAT                      (VK_SAMPLER_ADDRESS_MODE_REPEAT)
#define DMGRAPHICS_TEXTURE_WRAP_CLAMP_TO_BORDER             (VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER)
#define DMGRAPHICS_TEXTURE_WRAP_CLAMP_TO_EDGE               (VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE)
#define DMGRAPHICS_TEXTURE_WRAP_MIRRORED_REPEAT             (VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT)

#define DMGRAPHICS_BLEND_FACTOR_ZERO                        (0) // (VK_BLEND_FACTOR_ZERO)
#define DMGRAPHICS_BLEND_FACTOR_ONE                         (1) // (VK_BLEND_FACTOR_ONE)
#define DMGRAPHICS_BLEND_FACTOR_SRC_COLOR                   (2) // (VK_BLEND_FACTOR_SRC_COLOR)
#define DMGRAPHICS_BLEND_FACTOR_ONE_MINUS_SRC_COLOR         (3) // (VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR)
#define DMGRAPHICS_BLEND_FACTOR_DST_COLOR                   (4) // (VK_BLEND_FACTOR_DST_COLOR)
#define DMGRAPHICS_BLEND_FACTOR_ONE_MINUS_DST_COLOR         (5) // (VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR)
#define DMGRAPHICS_BLEND_FACTOR_SRC_ALPHA                   (6) // (VK_BLEND_FACTOR_SRC_ALPHA)
#define DMGRAPHICS_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA         (7) // (VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA)
#define DMGRAPHICS_BLEND_FACTOR_DST_ALPHA                   (8) // (VK_BLEND_FACTOR_DST_ALPHA)
#define DMGRAPHICS_BLEND_FACTOR_ONE_MINUS_DST_ALPHA         (9) // (VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA)
#define DMGRAPHICS_BLEND_FACTOR_SRC_ALPHA_SATURATE          (10) // (VK_BLEND_FACTOR_SRC_ALPHA_SATURATE)
#define DMGRAPHICS_BLEND_FACTOR_CONSTANT_COLOR              (11) // (VK_BLEND_FACTOR_CONSTANT_COLOR)
#define DMGRAPHICS_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR    (12) // (VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR)
#define DMGRAPHICS_BLEND_FACTOR_CONSTANT_ALPHA              (13) // (VK_BLEND_FACTOR_CONSTANT_ALPHA)
#define DMGRAPHICS_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA    (14) // (VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA)

#define DMGRAPHICS_COMPARE_FUNC_NEVER                       (0) // (VK_COMPARE_OP_NEVER)
#define DMGRAPHICS_COMPARE_FUNC_LESS                        (1) // (VK_COMPARE_OP_LESS)
#define DMGRAPHICS_COMPARE_FUNC_LEQUAL                      (2) // (VK_COMPARE_OP_LESS_OR_EQUAL)
#define DMGRAPHICS_COMPARE_FUNC_GREATER                     (3) // (VK_COMPARE_OP_GREATER)
#define DMGRAPHICS_COMPARE_FUNC_GEQUAL                      (4) // (VK_COMPARE_OP_GREATER_OR_EQUAL)
#define DMGRAPHICS_COMPARE_FUNC_EQUAL                       (5) // (VK_COMPARE_OP_EQUAL)
#define DMGRAPHICS_COMPARE_FUNC_NOTEQUAL                    (6) // (VK_COMPARE_OP_NOT_EQUAL)
#define DMGRAPHICS_COMPARE_FUNC_ALWAYS                      (7) // (VK_COMPARE_OP_ALWAYS)

// Stencil operation
#define DMGRAPHICS_STENCIL_OP_KEEP                          (0) // (VK_STENCIL_OP_KEEP)
#define DMGRAPHICS_STENCIL_OP_ZERO                          (1) // (VK_STENCIL_OP_ZERO)
#define DMGRAPHICS_STENCIL_OP_REPLACE                       (2) // (VK_STENCIL_OP_REPLACE)
#define DMGRAPHICS_STENCIL_OP_INCR                          (3) // (VK_STENCIL_OP_INCREMENT_AND_CLAMP)
#define DMGRAPHICS_STENCIL_OP_INCR_WRAP                     (4) // (VK_STENCIL_OP_INCREMENT_AND_WRAP)
#define DMGRAPHICS_STENCIL_OP_DECR                          (5) // (VK_STENCIL_OP_DECREMENT_AND_CLAMP)
#define DMGRAPHICS_STENCIL_OP_DECR_WRAP                     (6) // (VK_STENCIL_OP_DECREMENT_AND_WRAP)
#define DMGRAPHICS_STENCIL_OP_INVERT                        (7) // (VK_STENCIL_OP_INVERT)

#define DMGRAPHICS_BUFFER_USAGE_STREAM_DRAW                 (0)
#define DMGRAPHICS_BUFFER_USAGE_STREAM_READ                 (1)
#define DMGRAPHICS_BUFFER_USAGE_STREAM_COPY                 (2)
#define DMGRAPHICS_BUFFER_USAGE_DYNAMIC_DRAW                (3)
#define DMGRAPHICS_BUFFER_USAGE_DYNAMIC_READ                (4)
#define DMGRAPHICS_BUFFER_USAGE_DYNAMIC_COPY                (5)
#define DMGRAPHICS_BUFFER_USAGE_STATIC_DRAW                 (6)
#define DMGRAPHICS_BUFFER_USAGE_STATIC_READ                 (7)
#define DMGRAPHICS_BUFFER_USAGE_STATIC_COPY                 (8)
#define DMGRAPHICS_BUFFER_ACCESS_READ_ONLY                  (9)
#define DMGRAPHICS_BUFFER_ACCESS_WRITE_ONLY                 (10)
#define DMGRAPHICS_BUFFER_ACCESS_READ_WRITE                 (11)

#define DMGRAPHICS_FACE_TYPE_FRONT                          (0) // (VK_CULL_MODE_FRONT_BIT)
#define DMGRAPHICS_FACE_TYPE_BACK                           (1) // (VK_CULL_MODE_BACK_BIT)
#define DMGRAPHICS_FACE_TYPE_FRONT_AND_BACK                 (2) // (VK_CULL_MODE_FRONT_AND_BACK)

#define DMGRAPHICS_RENDER_BUFFER_FORMAT_DEPTH_STENCIL       (VK_FORMAT_D24_UNORM_S8_UINT)
#define DMGRAPHICS_RENDER_BUFFER_FORMAT_DEPTH24             (VK_FORMAT_D24_UNORM_S8_UINT)
#define DMGRAPHICS_RENDER_BUFFER_FORMAT_DEPTH16             (VK_FORMAT_D16_UNORM)
#define DMGRAPHICS_RENDER_BUFFER_FORMAT_STENCIL             (VK_FORMAT_S8_UINT)

// These are taken from https://github.com/KhronosGroup/Vulkan-Samples/blob/master/external/include/vulkan/vk_format.h
#define DMGRAPHICS_TEXTURE_FORMAT_RGB_DXT1                  (VK_FORMAT_BC1_RGB_UNORM_BLOCK)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA_DXT1                 (VK_FORMAT_BC1_RGBA_UNORM_BLOCK)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA_DXT3                 (VK_FORMAT_BC3_UNORM_BLOCK)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA_DXT5                 (VK_FORMAT_BC2_UNORM_BLOCK)
#define DMGRAPHICS_TEXTURE_FORMAT_RGB_PVRTC_2BPPV1          (VK_FORMAT_UNDEFINED)
#define DMGRAPHICS_TEXTURE_FORMAT_RGB_PVRTC_4BPPV1          (VK_FORMAT_UNDEFINED)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA_PVRTC_2BPPV1         (VK_FORMAT_UNDEFINED)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA_PVRTC_4BPPV1         (VK_FORMAT_UNDEFINED)
#define DMGRAPHICS_TEXTURE_FORMAT_RGB_ETC1                  (VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK)
#define DMGRAPHICS_TEXTURE_FORMAT_RED                       (VK_FORMAT_R8_UNORM)
#define DMGRAPHICS_TEXTURE_FORMAT_RG                        (VK_FORMAT_R8G8_UNORM)
#define DMGRAPHICS_TEXTURE_FORMAT_RGB32F                    (VK_FORMAT_R32G32B32_SFLOAT)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA32F                   (VK_FORMAT_R32G32B32A32_SFLOAT)
#define DMGRAPHICS_TEXTURE_FORMAT_RGB16F                    (VK_FORMAT_R16G16B16_SFLOAT)
#define DMGRAPHICS_TEXTURE_FORMAT_RGBA16F                   (VK_FORMAT_R16G16B16A16_SFLOAT)
#define DMGRAPHICS_TEXTURE_FORMAT_R16F                      (VK_FORMAT_R16_SFLOAT)
#define DMGRAPHICS_TEXTURE_FORMAT_R32F                      (VK_FORMAT_R32_SFLOAT)
#define DMGRAPHICS_TEXTURE_FORMAT_RG16F                     (VK_FORMAT_R16G16_SFLOAT)
#define DMGRAPHICS_TEXTURE_FORMAT_RG32F                     (VK_FORMAT_R32G32_SFLOAT)

#define DMGRAPHICS_WINDOW_STATE_OPENED                      (0x00020001)
#define DMGRAPHICS_WINDOW_STATE_ACTIVE                      (0x00020002)
#define DMGRAPHICS_WINDOW_STATE_ICONIFIED                   (0x00020003)
#define DMGRAPHICS_WINDOW_STATE_ACCELERATED                 (0x00020004)
#define DMGRAPHICS_WINDOW_STATE_RED_BITS                    (0x00020005)
#define DMGRAPHICS_WINDOW_STATE_GREEN_BITS                  (0x00020006)
#define DMGRAPHICS_WINDOW_STATE_BLUE_BITS                   (0x00020007)
#define DMGRAPHICS_WINDOW_STATE_ALPHA_BITS                  (0x00020008)
#define DMGRAPHICS_WINDOW_STATE_DEPTH_BITS                  (0x00020009)
#define DMGRAPHICS_WINDOW_STATE_STENCIL_BITS                (0x0002000A)
#define DMGRAPHICS_WINDOW_STATE_REFRESH_RATE                (0x0002000B)
#define DMGRAPHICS_WINDOW_STATE_ACCUM_RED_BITS              (0x0002000C)
#define DMGRAPHICS_WINDOW_STATE_ACCUM_GREEN_BITS            (0x0002000D)
#define DMGRAPHICS_WINDOW_STATE_ACCUM_BLUE_BITS             (0x0002000E)
#define DMGRAPHICS_WINDOW_STATE_ACCUM_ALPHA_BITS            (0x0002000F)
#define DMGRAPHICS_WINDOW_STATE_AUX_BUFFERS                 (0x00020010)
#define DMGRAPHICS_WINDOW_STATE_STEREO                      (0x00020011)
#define DMGRAPHICS_WINDOW_STATE_WINDOW_NO_RESIZE            (0x00020012)
#define DMGRAPHICS_WINDOW_STATE_FSAA_SAMPLES                (0x00020013)

#define DMGRAPHICS_STATE_WRITE_R                            (0x1)
#define DMGRAPHICS_STATE_WRITE_G                            (0x2)
#define DMGRAPHICS_STATE_WRITE_B                            (0x4)
#define DMGRAPHICS_STATE_WRITE_A                            (0x8)

#endif /* DMGRAPHICS_VULKAN_DEFINES_H */
