#! /usr/bin/env python

def build(bld):
    test_extension_lib = bld.stlib(features = 'cxx ddf test',
                                   includes = '../../src .',
                                   source = 'test_extension_lib.cpp',
                                   target = 'test_extension_lib')

    test_extension = bld.program(features = 'cxx embed test',
                                 includes = '../../src .',
                                 use = 'TESTMAIN DLIB LUA extension test_extension_lib',
                                 exported_symbols = ["TestExt"],
                                 target = 'test_extension',
                                 source = 'test_extension.cpp')
