import re
import Task, TaskGen
from TaskGen import extension, declare_extension

def build(bld):
    test_extension_lib = bld.new_task_gen(features = 'cxx cstaticlib ddf test',
                                 includes = '.',
                                 source = 'test_extension_lib.cpp',
                                 target = 'test_extension_lib')

    test_extension = bld.new_task_gen(features = 'cxx cprogram embed test',
                                      includes = '../../../src .',
                                      uselib = 'GTEST DLIB LUA SOL_RUNTIME SOL',
                                      uselib_local = 'extension test_extension_lib',
                                      exported_symbols = ["TestExt"],
                                      target = 'test_extension',
                                      source = 'test_extension.cpp')

    test_extension.install_path = None

