#! /usr/bin/env python

def build(bld):
    test_extension_lib = bld.__call__(features = 'cxx cstaticlib ddf test',
                                 includes = '.',
                                 source = 'test_extension_lib.cpp',
                                 target = 'test_extension_lib')

    test_extension = bld.__call__(features = 'cxx cprogram embed test',
                                      includes = '../../../src .',
                                      uselib = 'TESTMAIN DLIB LUA',
                                      uselib_local = 'extension test_extension_lib',
                                      exported_symbols = ["TestExt"],
                                      target = 'test_extension',
                                      source = 'test_extension.cpp')
