function init(self)
    -- DEF-3216 Setting nil for properties and a non-nil scale will break
    self.id_c = factory.create("#factory_c", nil, nil, nil, 1)

    self.id_a = factory.create("#factory_a", nil, nil, {test_value = 1})
    msg.post(self.id_a, "hello")
end

function update(self, dt)
    assert(self.a_hello, "no response from A yet")
    assert(not self.updated, "one more run through update than expected")
    self.updated = true
    self.id_b = factory.create("#factory_b", nil, nil, {factory = msg.url("#")})
    msg.post(self.id_b, "hello")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("pre_hello") then
        assert(sender.path == hash("/pre_spawner"), "unknown pre-spawner")
        self.spawner = sender
    elseif message_id == hash("hello") then
        self.a_hello = sender.path == self.id_a
    elseif message_id == hash("done") then
        msg.post(self.spawner, "done")
    end
end
