#! /usr/bin/env python
import sys, re

platform = bld.env.PLATFORM
local_libs = 'dmglfw'
if 'win32' in platform:
    local_libs = 'dmglfw dmglfw_getopt'
    bld.stlib(features = 'c',
                     includes = '.',
                     target = 'dmglfw_getopt',
                     source = 'getopt.c',
                     install_path = None)


samples = 'boing gears heightmap listmodes mipmaps mtbench mthello particles pong3d splitview triangle wave'
if platform in ('arm64-ios', 'x86_64-ios', 'armv7-android'):
    # Other examples are not compatible with OpenGLES
    samples = 'simple_gles2'
elif 'web' in platform:
    samples = ''

for e in samples.split():
    bld.program(features = 'c apk',
                     includes = '. ../include',
                     target = e,
                     source = '%s.c' % e,
                     uselib_local = local_libs,
		     uselib = 'X',
                     install_path = None)
