#! /usr/bin/env python
import os, re
from waf_dynamo import apidoc_extract_task


def configure(conf):
    pass

def build(bld):
    # default function for editor test
    source = 'tapticengine.cpp'.split()

    # define for iOS 
    platforms = ['armv7-darwin', 'arm64-darwin', 'x86_64-ios']
    for p in platforms:
        if re.match(p, bld.env.PLATFORM):
            source = ['tapticengine_ios.cpp', 'tapticengine.mm']
            break

    bld.new_task_gen(features = 'cxx cstaticlib',
                    includes = '.',
                    source = source,
                    target = 'tapticengine')

    apidoc_extract_task(bld, ['tapticengine_doc.h'])
