#! /usr/bin/env python

VERSION='0.1'
APPNAME='docs'

srcdir = '.'
blddir = 'build'

import sys, os, re
import Task, TaskGen
from TaskGen import extension

def scan_asciidoc(task):
    deps = []
    with open(task.inputs[0].abspath()) as f:
        for line in f:
            line.strip()
            if line.startswith('image:'):
                m = re.search(r'^image::?(\S+?)(\[\S+?\])$', line)
                if (m != None):
                    deps.append(task.inputs[0].parent.find_resource(m.groups(1)[0]))
    return (deps, [])

def init():
    pass

def configure(conf):
    conf.find_program('asciidoc', var='ASCIIDOC')
    conf.env['EMBED_VIDEO'] = os.path.abspath('scripts/embed_video.py')

asciidoc = Task.simple_task_type('asciidoc', '${ASCIIDOC} -a data-uri -o ${TGT} ${SRC}',
                                 shell=True)

asciidoc.scan = scan_asciidoc

embed_video = Task.simple_task_type('embed_video', 'python ${EMBED_VIDEO} ${SRC} ${TGT}',
                                    shell=True,
                                    after = 'asciidoc')

@extension('.txt')
def proto_file(self, node):
        doc = self.create_task('asciidoc')
        doc.set_inputs(node)
        out = node.change_ext('.html_tmp')
        doc.set_outputs(out)

        embed = self.create_task('embed_video')
        embed.set_inputs(out)
        embed_out = node.change_ext('.html')
        embed.set_outputs(embed_out)

        self.bld.install_files('${PREFIX}/share/doc',
                               embed_out.abspath(self.env), self.env)

def build(bld):
    dirs = ['src/business_plan', 'src/manual', 'src/presentation',
            'src/demos/docs']
    tsk = bld.new_task_gen(install_path='${DYNAMO_HOME}/share/doc')
    tsk.find_sources_in_dirs(dirs)
