#! /usr/bin/env python
import os
from waf_dynamo import dmsdk_add_files

def options(opt):
    pass

def build(bld):

    dmsdk_add_files(bld, '${PREFIX}/sdk/include/dmsdk', 'dmsdk')

    bld.stlib(features = 'cxx',
                includes = ['.'],
                target   = 'font',
                defines  = [],
                source   = bld.path.ant_glob(['*.cpp']))

    bld.add_group()
    bld.recurse('test')

def configure(conf):
    pass

