#! /usr/bin/env python
import os, sys

def configure(conf):
    pass

def build(bld):

    alut = bld.new_task_gen(features = 'cc cstaticlib',
                            includes = '. alut',
                            target = 'alut',
                            install_path='${PREFIX}/lib')

    alut.find_sources_in_dirs('alut')

    if sys.platform == 'win32':
        #NOTE: _XBOX to get static lib and avoid dllimport/dllexport stuff
        alut.defines = '_XBOX HAVE_STDINT_H HAVE__STAT ALUT_BUILD_LIBRARY HAVE_SLEEP HAVE_WINDOWS_H'
    else:
        alut.defines = 'HAVE_STDINT_H HAVE_STAT HAVE_UNISTD_H HAVE_USLEEP'

    if bld.env['COMPILER_CC'] == 'gcc':
        vorbis_flags = '-fsigned-char'.split()
    else:
        vorbis_flags = []
        # TODO: What options to add for msvc?
        pass

    vorbis_tremor = bld.new_task_gen(features = 'cc cstaticlib',
                           includes = '. vorbis_tremor',
                           source = [ 'vorbis_tremor/%s' % x for x in 'bitwise.c codebook.c dsp.c floor0.c floor1.c floor_lookup.c framing.c info.c mapping0.c mdct.c misc.c res012.c vorbisfile.c'.split()],
                           target = 'vorbis_tremor',
                           install_path='${PREFIX}/lib')

    vorbis_tremor.env.append_unique('CCFLAGS', vorbis_flags)

    sound = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                             includes = '. alut vorbis_tremor',
                             target = 'sound',
                             install_path='${PREFIX}/lib',
                             source = 'sound.cpp')

    sound_null = bld.new_task_gen(features = 'cxx cstaticlib ddf',
                             includes = '.',
                             target = 'sound_null',
                             install_path='${PREFIX}/lib',
                             source = 'sound_null.cpp')

    if sys.platform == 'win32':
        #NOTE: _XBOX to get static lib and avoid dllimport/dllexport stuff
        sound.defines = '_XBOX'
        sound_null.defines = '_XBOX'

    bld.add_subdirs('test')
    bld.install_files('${PREFIX}/include/sound', 'sound.h')
