#! /usr/bin/env python

def build(bld):
    bld.add_subdirs('test')
    bld.install_files('${PREFIX}/include/dlib', 'dlib/hashtable.h')

#       bld.new_task_gen(
#            features = 'cxx cstaticlib',
#            source = 'ddf.cpp ddf_inputstream.cpp private/ddf_private.cpp',
#            target = 'ddf')

def configure(conf):
    pass

