-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function update(self, dt)
    test_comp_type_from_lua("#script", "scriptc", 0)
    test_comp_type_from_lua("#a", "a", 0)

    print("Testing expected error -->")

    if (pcall(test_comp_type_from_lua("#notexist", "a", 1))) then
        print("MAWE The call succeeded unexpectedly")
        -- function didn't throw an error, but we did want it to!
        assert(false and "The call succeeded unexpectedly")
    else
        print("------------------")
    end

end
