#! /usr/bin/env python
import os, re

from waf_dynamo import apidoc_extract_task

def init():
    pass

def configure(conf):
    pass

def build(bld):
    source = 'facebook_null.cpp'

    platforms = ['arm.*?darwin', 'arm.*?android', '.*?web']
    for p in platforms:
        if re.match(p, bld.env.PLATFORM):
            source = 'facebook_stub.cpp'
            break

    bld.new_task_gen(features = 'cxx cstaticlib',
                    includes = '.',
                    source = source,
                    target = 'facebookext')

    apidoc_extract_task(bld, ['facebook_doc.h'])
