#!/usr/bin/env python

def init(ctx):
    pass

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    uselib = ['TESTMAIN', 'RESOURCE', 'DLIB', 'DDF', 'THREAD', 'LUA']

    for impl in ('', 'null'):
        local_lib = 'liveupdate'
        suffix = ''
        features = []
        if impl == 'null':
            local_lib += '_' + impl
            suffix += '_' + impl
            features = ['skip_test']

        bld.__call__(features = 'cxx cprogram test'.split() + features,
                         includes = '../../../src',
                         uselib = uselib,
                         uselib_local = local_lib,
                         web_libs = ['library_sys.js'],
                         target = 'test_liveupdate' + suffix,
                         source = 'test_liveupdate.cpp')

        bld.__call__(features = 'cxx cprogram test'.split() + features,
                         includes = '../../../src',
                         uselib = uselib,
                         uselib_local = local_lib,
                         web_libs = ['library_sys.js'],
                         target = 'test_liveupdate_async' + suffix,
                         source = '../liveupdate_async.cpp test_liveupdate_async.cpp')

def shutdown(self):
    pass
