#!/usr/bin/env python

def init():
    pass

def set_options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    uselib = ['TESTMAIN', 'RESOURCE', 'DLIB', 'DDF', 'THREAD', 'LUA', 'CARES']

    bld.new_task_gen(features = 'cxx cprogram test',
                     includes = '../../../src',
                     uselib = uselib,
                     uselib_local = 'liveupdate',
                     web_libs = ['library_sys.js'],
                     target = 'test_liveupdate',
                     source = 'test_liveupdate.cpp')

    bld.new_task_gen(features = 'cxx cprogram test',
                     includes = '../../../src',
                     uselib = uselib,
                     web_libs = ['library_sys.js'],
                     target = 'test_liveupdate_async',
                     source = '../liveupdate_async.cpp test_liveupdate_async.cpp')

def shutdown():
    pass
