local ret_code = 0

local function assert_cond(assert_that)
    if not assert_that then
        ret_code = 1
        assert(assert_that)
    end
end

function init(self)
    local n1 = gui.get_node("node_1")
    local n2 = gui.get_node("node_2")

    assert_cond(gui.get_material(n1) == hash(""))
    assert_cond(gui.get_material(n2) == hash("material_b"))

    gui.set_material(n1, "material_a")
    assert_cond(gui.get_material(n1) == hash("material_a"))

    gui.reset_material(n1)
    assert_cond(gui.get_material(n1) == hash(""))
end

function update(self)
    msg.post("#script", "done", {ret_code})
end

