-- Copyright 2020-2023 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

go.property("my_material", resource.material())

local ret_code = 0

local function assert_cond(assert_that)
    if not assert_that then
        ret_code = 1
        assert(assert_that)
    end
end

function do_test(self)
    assert_cond(go.get("#gui", "materials", { key = "material_a" }) == hash("/gui/material_script_functions_a.materialc"))
    assert_cond(go.get("#gui", "materials", { key = "material_b" }) == hash("/gui/material_script_functions_b.materialc"))

    -- replace material_a with our custom material (material_c)
    go.set("#gui", "materials", self.my_material, { key = "material_a" })
    assert_cond(go.get("#gui", "materials", { key = "material_a" }) == hash("/gui/material_script_functions_c.materialc"))

    -- create a named material slot in the list with our custom material (material_c)
    go.set("#gui", "materials", self.my_material, { key = "my_custom_material" })
    assert_cond(go.get("#gui", "materials", { key = "my_custom_material" }) == hash("/gui/material_script_functions_c.materialc"))
end

function do_exit(self)
    msg.post("@system:", "exit", { code = ret_code })
end

function on_message(self, message_id, message)
    if message_id == hash("done") then
        ret_code = message[1]

        pcall(function() do_test(self) end)
        do_exit(self)
    end
end


