-- Copyright 2020-2023 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local ret_code = 0

local function assert_cond(assert_that)
    if not assert_that then
        ret_code = 1
        assert(assert_that)
    end
end

function init(self)
    local n1 = gui.get_node("node_1")
    local n2 = gui.get_node("node_2")

    assert_cond(gui.get_material(n1) == hash(""))
    assert_cond(gui.get_material(n2) == hash("material_b"))

    gui.set_material(n1, "material_a")
    assert_cond(gui.get_material(n1) == hash("material_a"))

    gui.reset_material(n1)
    assert_cond(gui.get_material(n1) == hash(""))
end

function update(self)
    msg.post("#script", "done", {ret_code})
end

