go.property("my_material_a", resource.material("/gui/material_script_functions_a.material"))
go.property("my_material_b", resource.material("/gui/material_script_functions_b.material"))
go.property("my_material", resource.material())

local ret_code = 0

local function assert_cond(assert_that)
    if not assert_that then
        ret_code = 1
        assert(assert_that)
    end
end

function do_test(self)
    assert_cond(go.get("#gui", "materials", { key = "material_a" }) == self.my_material_a)
    assert_cond(go.get("#gui", "materials", { key = "material_b" }) == self.my_material_b)

    -- replace material_a with our custom material (material_c)
    go.set("#gui", "materials", self.my_material, { key = "material_a" })
    assert_cond(go.get("#gui", "materials", { key = "material_a" }) == self.my_material)

    -- create a named material slot in the list with our custom material (material_c)
    go.set("#gui", "materials", self.my_material, { key = "my_custom_material" })
    assert_cond(go.get("#gui", "materials", { key = "my_custom_material" }) == self.my_material)
end

function do_exit(self)
    msg.post("@system:", "exit", { code = ret_code })
end

function on_message(self, message_id, message)
    if message_id == hash("done") then
        ret_code = message[1]

        pcall(function() do_test(self) end)
        do_exit(self)
    end
end


