#! /usr/bin/env python

def build(bld):
    bld.program(features = 'cxx test skip_test',
                source = 'test_profilerext_null.cpp',
                use = 'TESTMAIN DLIB profilerext_null',
                includes = ['../../../src'],
                target = 'test_profilerext_null')
