#! /usr/bin/env python

VERSION='0.1'
APPNAME='docs'

srcdir = '.'
blddir = 'build'

import sys, os, re
import Task, TaskGen
from TaskGen import extension
import waf_dynamo

def init():
    pass

def configure(conf):
    pass

def build(bld):
    pass

def install(bld):
    pass

def set_options(opt):
    pass