local epsilon = 0.000001
local steps = 10

function init(self)
	self.dt_sum = 0
	self.steps_count = 0
	self.time_elapsed_sum = 0
	timer.delay(1/steps, true, function(_, _, time_elapsed)
		self.steps_count = self.steps_count + 1
		if self.steps_count <= steps then
			self.time_elapsed_sum = self.time_elapsed_sum + time_elapsed
		end
	end)
end

function update(self, dt)
	self.dt_sum = self.dt_sum + dt
	if self.steps_count >= steps then
		if math.abs(self.dt_sum - self.time_elapsed_sum) < epsilon * steps then
			msg.post("@system:", "exit", { code = 0 })
		else
			print("Too big difference between socket.get_time() and time_elapsed in timers:", math.abs(self.dt_sum - self.time_elapsed_sum))
			msg.post("@system:", "exit", { code = 1 })
		end
	end
end