-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

function init(self)
    msg.post("#", "start_test")
    self.elapsed = 0
end


function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
    self.elapsed = self.elapsed + dt
    if self.elapsed > 0.5 then
        print("Engine shutting down")
        msg.post("@system:", "exit", {code = 0})
    end
end

function on_message(self, message_id, message, sender)
    -- print("on_message")
    if message_id == hash("start_test") then
        msg.post("#proxy", "async_load")
    elseif message_id == hash("proxy_loaded") then
        -- enable the collection and let the loader know
        msg.post(sender, "enable")
    end
end
