#! /usr/bin/env python
import sys, re, os
import Options

defines = []
if Options.options.with_vulkan:
    defines.append('DM_USE_VULKAN')

dmglfw = bld.new_task_gen(  features = 'cc cstaticlib',
                            defines = defines,
                            target = 'dmglfw')

platform = bld.env.PLATFORM

if platform == 'darwin' or platform == 'x86_64-darwin':
    dmglfw.find_sources_in_dirs('. cocoa')
    dmglfw.includes = '. cocoa'

    if Options.options.with_vulkan:
        dmglfw.source.remove(os.path.join('cocoa','cocoa_window.m'))
    else:
        dmglfw.source.remove(os.path.join('cocoa','cocoa_window_vulkan.m'))

elif platform in ('armv7-darwin', 'arm64-darwin', 'x86_64-ios'):
    dmglfw.find_sources_in_dirs('. ios ios/app')
    dmglfw.includes = '. ios'

    if not platform == 'x86_64-ios' and Options.options.with_vulkan:
        dmglfw.source.remove(os.path.join('ios','app','EAGLView.m'))
    else:
        dmglfw.source.remove(os.path.join('ios','app','VulkanView.m'))

elif re.match('arm.*?android', platform):
    dmglfw.find_sources_in_dirs('. android')
    dmglfw.includes = '. android'
elif platform == 'linux' or platform == 'x86_64-linux':
    dmglfw.find_sources_in_dirs('. x11')
    dmglfw.includes = '. x11'
elif 'win32' in platform:
    dmglfw.find_sources_in_dirs('. win32')
    dmglfw.includes = '. win32'
elif 'web' in platform:
    dmglfw.find_sources_in_dirs('js-web')
    dmglfw.includes = 'js-web .'
