#! /usr/bin/env python
import sys, re

dmglfw = bld.new_task_gen(features = 'cc cstaticlib',
                          target = 'dmglfw')

platform = bld.env.PLATFORM

if platform == 'darwin' or platform == 'x86_64-darwin':
    dmglfw.find_sources_in_dirs('. cocoa')
    dmglfw.includes = '. cocoa'
elif re.match('arm.*?darwin', platform) or platform == 'x86_64-ios':
    dmglfw.find_sources_in_dirs('. ios')
    dmglfw.includes = '. ios'
elif re.match('arm.*?android', platform):
    dmglfw.find_sources_in_dirs('. android')
    dmglfw.includes = '. android'
elif platform == 'linux' or platform == 'x86_64-linux':
    dmglfw.find_sources_in_dirs('. x11')
    dmglfw.includes = '. x11'
elif 'win32' in platform:
    dmglfw.find_sources_in_dirs('. win32')
    dmglfw.includes = '. win32'
elif platform == 'js-web':
    dmglfw.find_sources_in_dirs('js-web')
    dmglfw.includes = 'js-web .'
elif platform == 'as3-web':
    dmglfw.find_sources_in_dirs('flash')
    dmglfw.includes = 'flash .'

