#! /usr/bin/env python
import sys, re, os
import Options

dmglfw = bld.new_task_gen(features = 'cc cstaticlib',
                          target   = 'dmglfw')

platform = bld.env.PLATFORM
darwin_vulkan_mobile  = False

if platform == 'darwin' or platform == 'x86_64-darwin':
    dmglfw.find_sources_in_dirs('. cocoa')
    dmglfw.includes = '. cocoa'
elif platform in ('armv7-darwin', 'arm64-darwin', 'x86_64-ios'):
    dmglfw.find_sources_in_dirs('. ios ios/app')
    dmglfw.includes = '. ios'
    dmglfw.source.remove(os.path.join('ios','app','VulkanView.m'))
    darwin_vulkan_mobile = True
elif re.match('arm.*?android', platform):
    dmglfw.find_sources_in_dirs('. android')
    dmglfw.includes = '. android'
elif platform == 'linux' or platform == 'x86_64-linux':
    dmglfw.find_sources_in_dirs('. x11')
    dmglfw.includes = '. x11'
elif 'win32' in platform:
    dmglfw.find_sources_in_dirs('. win32')
    dmglfw.includes = '. win32'
elif 'web' in platform:
    dmglfw.find_sources_in_dirs('js-web')
    dmglfw.includes = 'js-web .'
if darwin_vulkan_mobile:
    dmglfw = bld.new_task_gen(features = 'cc cstaticlib',
                              defines  = ['DM_USE_VULKAN'],
                              target   = 'dmglfw_vulkan')
    dmglfw.find_sources_in_dirs('. ios ios/app')
    dmglfw.includes = '. ios'
    dmglfw.source.remove(os.path.join('ios','app','EAGLView.m'))
