#! /usr/bin/env python
import re

def build(bld):

    sources = []
    includes = []

    platform = bld.env.PLATFORM

    if platform in ('x86_64-macos',):
        sources  = bld.path.ant_glob(['*.c', 'cocoa/*.m'])
        includes = '. cocoa'
    elif platform in ('arm64-ios', 'x86_64-ios'):
        sources  = bld.path.ant_glob(['*.c', 'ios/*.m', 'ios/app/*.m'])
        includes = '. ios'
    elif re.match('arm.*?android', platform):
        sources  = bld.path.ant_glob(['*.c', 'android/*.c'])
        includes = '. android'
    elif platform == 'linux' or platform == 'x86_64-linux':
        sources  = bld.path.ant_glob(['*.c', 'x11/*.c'])
        includes = '. x11'
    elif 'win32' in platform:
        sources  = bld.path.ant_glob(['*.c', 'win32/*.c'])
        includes = '. win32'
    elif 'web' in platform:
        sources  = bld.path.ant_glob('js-web/*.c')
        includes = '. js-web'

    dmglfw = bld.stlib(features     = 'c',
                       source       = sources,
                       includes     = includes, 
                       target       = 'dmglfw')
