compute_program: "/misc/material_compute_modules/compute.cp"

samplers {
  name: "u_sampler2d"
  wrap_u: WRAP_MODE_CLAMP_TO_EDGE
  wrap_v: WRAP_MODE_CLAMP_TO_EDGE
  filter_min: FILTER_MODE_MIN_LINEAR_MIPMAP_NEAREST
  filter_mag: FILTER_MODE_MAG_LINEAR
  max_anisotropy: 1.0
}

samplers {
  name: "u_samplerCube"
  wrap_u: WRAP_MODE_CLAMP_TO_EDGE
  wrap_v: WRAP_MODE_CLAMP_TO_EDGE
  filter_min: FILTER_MODE_MIN_LINEAR_MIPMAP_NEAREST
  filter_mag: FILTER_MODE_MAG_LINEAR
  max_anisotropy: 1.0
}

samplers {
  name: "u_sampler2dArray"
  wrap_u: WRAP_MODE_CLAMP_TO_EDGE
  wrap_v: WRAP_MODE_CLAMP_TO_EDGE
  filter_min: FILTER_MODE_MIN_LINEAR_MIPMAP_NEAREST
  filter_mag: FILTER_MODE_MAG_LINEAR
  max_anisotropy: 1.0
}

samplers {
  name: "texture_out"
  wrap_u: WRAP_MODE_CLAMP_TO_EDGE
  wrap_v: WRAP_MODE_CLAMP_TO_EDGE
  filter_min: FILTER_MODE_MIN_LINEAR_MIPMAP_NEAREST
  filter_mag: FILTER_MODE_MAG_LINEAR
  max_anisotropy: 1.0
}

constants {
  name: "proj"
  type: CONSTANT_TYPE_PROJECTION
}

constants {
  name: "view"
  type: CONSTANT_TYPE_VIEW
}

constants {
  name: "world"
  type: CONSTANT_TYPE_WORLD
}

constants {
  name: "u_user"
  type: CONSTANT_TYPE_USER
  value {
    x: 1.0
    y: 2.0
    z: 3.0
    w: 4.0
  }
}

constants {
  name: "u_user_arr"
  type: CONSTANT_TYPE_USER
  value {
    x: 11.0
    y: 12.0
    z: 13.0
    w: 14.0
  }
  value {
    x: 21.0
    y: 22.0
    z: 23.0
    w: 24.0
  }
}

constants {
  name: "u_user_not_found"
  type: CONSTANT_TYPE_USER
}

constants {
  name: "u_user_mat4"
  type: CONSTANT_TYPE_USER_MATRIX4
  value {
    x: 11.0
    y: 12.0
    z: 13.0
    w: 14.0
  }
  value {
    x: 21.0
    y: 22.0
    z: 23.0
    w: 24.0
  }
  value {
    x: 31.0
    y: 32.0
    z: 33.0
    w: 34.0
  }
  value {
    x: 41.0
    y: 42.0
    z: 43.0
    w: 44.0
  }
}

constants {
  name: "u_user_mat4_arr"
  type: CONSTANT_TYPE_USER_MATRIX4
  value {
    x: 11.0
    y: 12.0
    z: 13.0
    w: 14.0
  }
  value {
    x: 21.0
    y: 22.0
    z: 23.0
    w: 24.0
  }
  value {
    x: 31.0
    y: 32.0
    z: 33.0
    w: 34.0
  }
  value {
    x: 41.0
    y: 42.0
    z: 43.0
    w: 44.0
  }

  value {
    x: 101.0
    y: 102.0
    z: 103.0
    w: 104.0
  }
  value {
    x: 201.0
    y: 202.0
    z: 203.0
    w: 204.0
  }
  value {
    x: 301.0
    y: 302.0
    z: 303.0
    w: 304.0
  }
  value {
    x: 401.0
    y: 402.0
    z: 403.0
    w: 404.0
  }
}

