-- Copyright 2020-2024 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

require "misc.material_compute_modules.tests"

function init(self)
    self.material = "/misc/material_compute_modules/material_module.materialc"

    -- Get tests
    test_module_get_samplers(material, self.material, {
        default_sampler("u_sampler2d"),
        default_sampler("u_samplerCube"),
        default_sampler("u_sampler2dArray"),
    })

    test_module_get_vertex_attributes(material, self.material, {
        make_vertex_attribute("position", vmath.vector4(), graphics.DATA_TYPE_FLOAT, graphics.COORDINATE_SPACE_WORLD, false, graphics.SEMANTIC_TYPE_POSITION),
        make_vertex_attribute("page_index", 0, graphics.DATA_TYPE_FLOAT, graphics.COORDINATE_SPACE_WORLD, false, graphics.SEMANTIC_TYPE_PAGE_INDEX),
        make_vertex_attribute("custom_one", vmath.vector3(), graphics.DATA_TYPE_FLOAT, graphics.COORDINATE_SPACE_WORLD, false, graphics.SEMANTIC_TYPE_NONE),
        make_vertex_attribute("custom_two", vmath.vector3(), graphics.DATA_TYPE_FLOAT, graphics.COORDINATE_SPACE_WORLD, false, graphics.SEMANTIC_TYPE_NONE),
        make_vertex_attribute("custom_three", vmath.vector4(), graphics.DATA_TYPE_FLOAT, graphics.COORDINATE_SPACE_WORLD, false, graphics.SEMANTIC_TYPE_NONE),
    })

    test_module_get_constants(material, self.material, {
        make_constant("world", nil, material.CONSTANT_TYPE_WORLD),
        make_constant("view", nil, material.CONSTANT_TYPE_VIEW),
        make_constant("proj", nil, material.CONSTANT_TYPE_PROJECTION),
        make_constant("u_user", vmath.vector4(1,2,3,4), material.CONSTANT_TYPE_USER),
        make_constant("u_user_mat4", make_mat4(11,12,13,14,21,22,23,24,31,32,33,34,41,42,43,44), material.CONSTANT_TYPE_USER_MATRIX4),
        make_constant("u_user_arr", { vmath.vector4(11,12,13,14), vmath.vector4(21,22,23,24) }, material.CONSTANT_TYPE_USER),
        make_constant("u_user_mat4_arr", { make_mat4(11,12,13,14,21,22,23,24,31,32,33,34,41,42,43,44), make_mat4(101,102,103,104,201,202,203,204,301,302,303,304,401,402,403,404) }, material.CONSTANT_TYPE_USER_MATRIX4),
    })

    test_module_get_textures(material, self.material)

    -- Set tests
    test_module_set_sampler(material, self.material, "u_sampler2d", "u_sampler2d")
    test_module_set_sampler(material, self.material, "u_samplerCube", "u_samplerCube")
    test_module_set_sampler(material, self.material, "u_sampler2dArray", "u_sampler2dArray")

    test_module_set_vertex_attribute(material, self.material, "position", vmath.vector3(1,2,3), graphics.SEMANTIC_TYPE_NONE)
    test_module_set_vertex_attribute(material, self.material, "custom_one", vmath.vector3(1,2,0), graphics.SEMANTIC_TYPE_COLOR)
    test_module_set_vertex_attribute(material, self.material, "custom_two", vmath.vector3(1,2,3), graphics.SEMANTIC_TYPE_NONE)
    test_module_set_vertex_attribute(material, self.material, "custom_three", vmath.vector4(1,2,3,4), graphics.SEMANTIC_TYPE_COLOR)

    test_module_set_constant(material, self.material, "world", make_mat4(11,12,13,14,21,22,23,24,31,32,33,34,41,42,43,44), material.CONSTANT_TYPE_USER_MATRIX4)
    test_module_set_constant(material, self.material, "u_user_arr", { vmath.vector4(99,98,97,96), vmath.vector4(81,82,83,84) }, material.CONSTANT_TYPE_USER)
    test_module_set_constant(material, self.material, "u_user_mat4_arr", { make_mat4(11,12,13,14,21,22,23,24,31,32,33,34,41,42,43,44), make_mat4(101,102,103,104,201,202,203,204,301,302,303,304,401,402,403,404) }, material.CONSTANT_TYPE_USER_MATRIX4)

    test_module_set_texture(material, self.material, "u_sampler2d", graphics.TEXTURE_TYPE_2D)
    test_module_set_texture(material, self.material, "u_samplerCube", graphics.TEXTURE_TYPE_CUBE_MAP)
end
