#! /usr/bin/env python

def configure(conf):
    pass

def build(bld):
    bld.stlib(features = 'cxx cstaticlib',
              includes = '.',
              source = 'record.cpp record_common.cpp',
              target = 'record')

    bld.stlib(features = 'cxx cstaticlib',
              includes = '.',
              source = 'record_null.cpp record_common.cpp',
              target = 'record_null')

    bld.install_files('${PREFIX}/include/record', 'record.h')
