-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

go.property("number", 1)
go.property("hash", hash("test"))
go.property("url", msg.url())
go.property("vec3", vmath.vector3())
go.property("vec4", vmath.vector4(0, 0, 0, 0))
go.property("quat", vmath.quat())
go.property("bool", false)
go.property("material", resource.material("material"))

function update(self)
    -- the properties are set by props_get_set_a.script
    assert(self.number == 2)
    assert(self.hash == hash("test2"))
    assert(self.url == msg.url("a#script"))
    assert(self.vec3 == vmath.vector3(1, 1, 1))
    assert(self.vec4 == vmath.vector4(1, 1, 1, 1))
    assert(self.quat == vmath.quat(1, 1, 1, 1))
    assert(self.bool)
    assert(self.material)
end
