-- Copyright 2020-2026 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

go.property("number", 100)
go.property("url", msg.url())
go.property("hash", hash(""))
go.property("vec3", vmath.vector3())
go.property("vec4", vmath.vector4())
go.property("quat", vmath.quat())
go.property("bool", false)

function init(self)
    assert(self.number == 200)
    local url = msg.url("#comp")
    assert(self.url.socket == url.socket)
    assert(self.url.path == url.path)
    assert(self.url.fragment == url.fragment)
    assert(self.hash == hash("hash"))
    assert(self.vec3 == vmath.vector3(1, 2, 3))
    assert(self.vec4 == vmath.vector4(4, 5, 6, 7))
    assert(self.quat == vmath.quat(8, 9, 10, 11))
    assert(self.bool)
end
