#! /usr/bin/env python

VERSION='0.1'
APPNAME='crash'

srcdir = '.'
blddir = 'build'

import sys, re, os
import waf_dynamo, waf_ddf
from BuildUtility import BuildUtility, BuildUtilityException, create_build_utility
import waflib.Options
import TestContext

test_context = None

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def options(opt):
    opt.load('waf_dynamo')
    opt.load('waf_ddf')

def configure(conf):
    conf.load('waf_dynamo')
    conf.load('waf_ddf')
    waf_ddf.configure(conf)

    build_util = None
    try:
        build_util = create_build_utility(conf.env)
    except BuildUtilityException as ex:
        conf.fatal(ex.msg)
    operating_sys = build_util.get_target_os()

    conf.recurse('src')

    conf.env.append_value('CPPPATH', "default/src")

    conf.env['STLIB_DLIB'] = ['dlib', 'mbedtls', 'zip']
    conf.env['STLIB_DDF'] = 'ddf'
    conf.env['STLIB_RESOURCE'] = 'resource'
    conf.env['STLIB_EXTENSION'] = 'extension'
    conf.env['STLIB_SCRIPT'] = 'script'

    if operating_sys != "osx":
        conf.env['STLIB_UNWIND'] = 'unwind'

    conf.env.append_unique('DEFINES', 'DLIB_LOG_DOMAIN="CRASH"')

    if operating_sys == "win":
        conf.env.append_value('LINKFLAGS', ['dbghelp.lib'])

    conf.env.append_value('CFLAGS', ["-fdebug-compilation-dir=engine/crash", "-fdebug-prefix-map=../src=src", "-fdebug-prefix-map=../../../tmp/dynamo_home=../../defoldsdk"])
    conf.env.append_value('CXXFLAGS', ["-fdebug-compilation-dir=engine/crash", "-fdebug-prefix-map=../src=src", "-fdebug-prefix-map=../../../tmp/dynamo_home=../../defoldsdk"])

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)
