import sys

def configure(conf):
    conf.env['CXXDEFINES_BULLET'] = ['NDEBUG']
    #if sys.platform == "linux2" or sys.platform == "darwin":
    #    conf.env['CXXFLAGS_BULLET'] = ['-O2']
    #else:
    #    conf.env['CXXFLAGS_BULLET'] = ['/O2']

def build(bld):
    bld.add_subdirs('BulletCollision')
    bld.add_subdirs('BulletDynamics')
    bld.add_subdirs('LinearMath')
