name: Build SheenBidi

on:
  workflow_dispatch:
  push:

jobs:
  build:
    uses: ./.github/workflows/build-external-template.yml
    with:
      package_name: 'sheenbidi'
      package_version: '2.9.0'
    secrets:
      dm_packages_url: ${{ secrets.DM_PACKAGES_URL }}
