name: Build LuaJIT

on:
  workflow_dispatch:
    inputs:
      push_changes:
        description: 'Commit built package tarballs to ./packages on the target branch'
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-external-template.yml
    with:
      package_name: 'luajit'
      package_root: 'share/ext/luajit'
      artifact_dir: 'share/ext/build'
      result_folder_name: 'luajit'
      result_lib_name: 'libluajit-5.1'
      package_version: '2.1.0-3e223cb'
      push_changes: ${{ inputs.push_changes }}
      setup_msvc: true
      platforms: >
        [
          { "name": "x86_64-linux", "runner": "ubuntu-22.04", "target": "linux" },
          { "name": "arm64-linux", "runner": "ubuntu-22.04-arm", "target": "linux" },
          { "name": "arm64-macos", "runner": "macOS-14", "target": "macos" },
          { "name": "x86_64-macos", "runner": "macOS-14", "target": "macos" },
          { "name": "arm64-ios", "runner": "macOS-14", "target": "macos" },
          { "name": "x86_64-ios", "runner": "macOS-14", "target": "macos" },
          { "name": "win32", "runner": "windows-2025", "target": "windows" },
          { "name": "x86_64-win32", "runner": "windows-2025", "target": "windows" },
          { "name": "arm64-android", "runner": "ubuntu-22.04", "target": "android" },
          { "name": "armv7-android", "runner": "ubuntu-22.04", "target": "android" }
        ]
      pre_build_command: |
        if [ "$BUILD_PLATFORM_NAME" = "arm64-linux" ]; then
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev:arm64 build-essential
          sudo cp -r /usr/include/aarch64-linux-gnu/. /usr/include/
        fi

        if [ "$BUILD_PLATFORM_TARGET" = "android" ]; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libc6-dev-i386 gcc-multilib
        fi
      build_command: |
        cd share/ext/luajit
        ./build_luajit.sh "$BUILD_PLATFORM_NAME"
      windows_build_command: |
        choco install wget -y
        cd share\ext\luajit
        call build_win32.bat %BUILD_PLATFORM_NAME%
        if not exist ..\build mkdir ..\build
        copy package\*.tar.gz ..\build\
    secrets:
      dm_packages_url: ${{ secrets.DM_PACKAGES_URL }}
