name: Issue Score

on:
  issues:
    types:
      - field_added

jobs:
  update-score:
    permissions:
      contents: read
      issues: write
    uses: defold/github-actions-common/.github/workflows/issue-score.yml@master
    secrets: inherit
