#! /usr/bin/env python

VERSION='0.1'
APPNAME='push'

srcdir = '.'
blddir = 'build'

import waf_dynamo
import waflib.Options
import TestContext

test_context = None

def options(opt):
    opt.load('waf_dynamo')

def init(ctx):
    global test_context
    if 'build' in waflib.Options.commands:
        test_context = TestContext.create_test_context()

def configure(conf):
    conf.load('waf_dynamo')
    conf.recurse('src')

def build(bld):
    global test_context
    bld.recurse('src')
    TestContext.initialize_test_context(test_context, bld)

def shutdown(self):
    waf_dynamo.run_tests(test_context, valgrind = True)
