#! /usr/bin/env python

VERSION='0.1'
APPNAME='push'

srcdir = '.'
blddir = 'build'

import waf_dynamo

def options(opt):
    opt.load('waf_dynamo')

def init(ctx):
    pass

def configure(conf):
    conf.load('waf_dynamo')
    conf.recurse('src')

def build(bld):
    bld.recurse('src')

def shutdown(self):
    waf_dynamo.run_tests(valgrind = True)
