-- Copyright 2020-2024 The Defold Foundation
-- Copyright 2014-2020 King
-- Copyright 2009-2014 Ragnar Svensson, Christian Murray
-- Licensed under the Defold License version 1.0 (the "License"); you may not use
-- this file except in compliance with the License.
--
-- You may obtain a copy of the License, together with FAQs at
-- https://www.defold.com/license
--
-- Unless required by applicable law or agreed to in writing, software distributed
-- under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
-- CONDITIONS OF ANY KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations under the License.

local tests_left = 2

tests_done = false

local function test_done(response, data_str)
    assert(response.status         == 200)
    assert(response.headers.server == "Dynamo 1.0")
    assert(response.response       == data_str)
    tests_left = tests_left - 1
    if tests_left <= 0 then
        tests_done = true
    end
end

local function get_callback(response)

end

function init(self)
    http.request(ADDRESS, "GET",
        function(self, id, response)
            test_done(response, "Hello")
        end)

    http.request(ADDRESS .. "/test_progress", "GET",
        function(self, id, response)
            local data_str = "test_progress_complete"
            if not self.test_1_progress then
                assert(response.bytes_received == #data_str)
                -- no content-length headers
                assert(response.bytes_total == -1)
                self.test_1_progress = true
            else
                test_done(response, data_str)
            end
        end,
        nil, nil, { report_progress = true })
end

